### ISSUE TITLE
Deletion of downloaded files?

### ISSUE THREAD

**Issue by yesnomaybewtf** [davidnewhall/unpackerr#100]
Hi, im new to unpackerr, so forgive me if the question is stupid.
When unpackerr finished extraction, the file is imported, i thought unpackerr will delete the unpacked files and the donloaded files.
Instead, only the extracted files are deleted.
Does an option exist, to also delete the downloaded files?

**Comment by davidnewhall** [comment]
How will your torrents seed if you deleted the downloaded files?

**Comment by yesnomaybewtf** [comment]
Ah, i should have mentioned that im only using usenet.

**Comment by davidnewhall** [comment]
Make sure you're using the latest beta: https://github.com/davidnewhall/unpackerr/releases/tag/v0.8.0-beta2

And set `delete_orig` to `true`: https://github.com/davidnewhall/unpackerr/blob/master/examples/unpackerr.conf.example#L82-L85

**Comment by yesnomaybewtf** [comment]
Great, thank you!
