### ISSUE TITLE
Request: Add support for password protected files rar files.

### ISSUE THREAD

**Issue by yesnomaybewtf** [davidnewhall/unpackerr#101]
Sometimes (or often) usenet downloads are password protected.
The naming of those download is (for example) My_Holiday_Movies{{The_Password}}
I unpackerr able to deal with this kind of files? 
Because actually i got one of this downloads, and unpackerr (in docker) gets panic.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x34cff0]

goroutine 19 [running]:
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).checkRadarrQueue(0x1d00270)
        /unpackerr/pkg/unpackerr/radarr.go:101 +0x2f4
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).retreiveAppQueues(0x1d00270)
        /unpackerr/pkg/unpackerr/apps.go:84 +0x188
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).Run(0x1d00270)
        /unpackerr/pkg/unpackerr/start.go:165 +0x90
created by github.com/davidnewhall/unpackerr/pkg/unpackerr.Start
        /unpackerr/pkg/unpackerr/start.go:134 +0x4d0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by davidnewhall** [comment]
Unpackerr wont know how to use a password. The crash is concerning though. Is this the beta version?

**Comment by yesnomaybewtf** [comment]
Yes, its the beta.
Is it possible to add the feature for unpackerr to detect the password in the brackets and use it for extraction?

**Comment by davidnewhall** [comment]
I have no idea. I've never seen this. I don't use usenet, and I don't have any easy way to test this. I'm also not even sure if the extraction library I use supports rar passwords........... This is probably going to be a "no"

**Comment by davidnewhall** [comment]
This crash is not because of a password protected rar file. It's something else and I'm still trying to figure it out.

**Comment by davidnewhall** [comment]
The crash is now fixed in the latest beta. https://github.com/davidnewhall/unpackerr/releases/tag/v0.8.0-beta3

**Comment by davidnewhall** [comment]
The library I'm using does support passwords. Can you show me a real example? Preferably from the Unpackerr error messaging telling you it can't extract a passwords protected file? That will be super valuable and possible allow me to add this feature for you.

**Comment by yesnomaybewtf** [comment]
Oh thats great.
The format is as i mentioned in the first post.
The password is always inside the double brackets.
Error message while extracting seems to be: rarReader.Next: rardecode: bad header crc


Von meinem iPad gesendet

**Comment by davidnewhall** [comment]
I was more looking for the file name in the error message, not the error itself. You provided a pretty generic fake example, and while I could code for that, it'd be better for me to see a real example.

**Comment by davidnewhall** [comment]
If you jump in Discord I can send you a test build that may work with passwords.

**Comment by yesnomaybewtf** [comment]
Im in!

**Comment by davidnewhall** [comment]
The latest release has this feature included.

**Comment by furchtlos76** [comment]
@davidnewhall  on 23. Mar 2021 you wrote the latest release has this feature in. I am searching for exactly this feature as i am using synology downloadstation for example usenet. the  directorys are often in this format:

Name{{Password}}

like for example

Really.cool.Release{{vXnIxmun2H391JPjkz3N}}

But unfortuatly i get the following error on al directorys i tryed yet. Using official docker. Any idea what is missing? Usiing folder mode only

2022/04/29 20:45:54.209236 folder.go:260: [Folder] Extraction Error: /temp/Really.cool.Release{{vXnIxmun2H391JPjkz3N}}: rarReader.Next: rardecode: incorrect password | stdout

**Comment by davidnewhall** [comment]
@furchtlos76 You're on the wrong issue, please use the one you opened.

**Comment by furchtlos76** [comment]
@davidnewhall  sorry, i am new to github, as this is marked as closed/fixed but the same problem does not work like desciribed i thought to add to this thread. shall i add to the other, even its another problem, then?

**Comment by davidnewhall** [comment]
@furchtlos76 Please provide your configuration, explain what you are doing, and attach the unpackerr logs. **On the issue you opened, not here.**
