### ISSUE TITLE
unpackerr.conf

### ISSUE THREAD

**Issue by rinzes** [davidnewhall/unpackerr#105]
as a new user who just completed the unpacker.conf I would like to recommend that you put in a double ## in front of comments so the user will know not to uncomment them

**Comment by angrycuban13** [comment]
Why? `#` literally means “Comment”.

**Comment by davidnewhall** [comment]
Hi @rinzes! Thank you for your report. 

Can you tell me more about the problem we're trying to solve here? Which lines did you accidentally uncomment? You can tell mee by line number from the [example confg](https://github.com/davidnewhall/unpackerr/blob/master/examples/unpackerr.conf.example) to make it easy. 

Most of the "compressed" comment/code lines already have double comments (for the exact reason you opened this issue). I'm quite curious where you got stuck, and if the error message unpackerr produced made it easy to figure out. 

Thank you!

**Comment by rinzes** [comment]
The example.config you provided was way better to understand however, that example did not get created when I installed on my syno DS920 Docker.  https://pastebin.com/27BB3fa7

**Comment by davidnewhall** [comment]
Got it, thanks for sharing! The config has been changed since the version you are currently running. The next version will have the new config format in it. Hopefully that solves this for anyone else.

Appreciate your report and follow-up!
