### ISSUE TITLE
Chose destination folder for unpacking

### ISSUE THREAD

**Issue by alexbleicker** [davidnewhall/unpackerr#108]
So far I can see, there is no way to configure the output folder to any specific folder, right?

**Comment by davidnewhall** [comment]
That is correct.

**Comment by davidnewhall** [comment]
Did you have another use case in mind?

**Comment by alexbleicker** [comment]
Stagging storage to then long term storage. For example, something is downloaded on temp fast storage, then later when unpacked goes to slower storage tier. Decompressing the files in the same storage it is read from has a substantial impact on performance.

**Comment by davidnewhall** [comment]
I've added the ability to set an extraction path in the latest version. Please let me know if this fits your use case. If not we can tweak it a bit. Thanks for your feedback!
