### ISSUE TITLE
API key is invalid

### ISSUE THREAD

**Issue by jaschuu** [davidnewhall/unpackerr#110]
Getting This error, what API key is it saying is invalid?
I copied the API keys for sonarr and radarr so they can not be wrong?

2021/03/24 15:52:41 Unpackerr v0.9.0 Starting! (PID: 1) 2021-03-24 15:52:41.518630699 +1000 AEST m=+0.000403423
2021/03/24 15:52:41 [ERROR] provided application API Key is invalid, must be 32 characters:

2021/03/24 15:52:41 Unpackerr v0.9.0 Starting! (PID: 1) 2021-03-24 15:52:41.518630699 +1000 AEST m=+0.000403423
2021/03/24 15:52:41 [ERROR] provided application API Key is invalid, must be 32 characters:

**Comment by davidnewhall** [comment]
Does it show the API key after the `:` or is it blank? If it's blank, it means you have extra configuration without a key defined. Can you share your config? `xxxx` out your api keys

**Comment by jaschuu** [comment]
i am using unraid

[image: image.png]

**Comment by stephangrobler** [comment]
Hi, I have the same issue and I only have Lidarr not set up, meaning the API key field is empty.
![image](https://user-images.githubusercontent.com/648346/112263248-aad4c600-8c77-11eb-8e6f-fcd07ab3dd7e.png)

**Comment by jaschuu** [comment]
i am using unraid

![image](https://user-images.githubusercontent.com/28653939/112263386-ee045880-8cba-11eb-84fd-1b8e3b593b3f.png)

**Comment by davidnewhall** [comment]
Try removing the unused URLs. WOrst case, delete those values entirely, but I think blanking them out should work too.

**Comment by jaschuu** [comment]
I removed the lidarr url and got this error
![image](https://user-images.githubusercontent.com/28653939/112263648-5f440b80-8cbb-11eb-9468-3e784b01e022.png)

**Comment by davidnewhall** [comment]
Remove the download path too. Anything that starts with UN_LIDARR needs to be blank if you're not using it.

**Comment by davidnewhall** [comment]
Didn't realize this change would cause so much trouble. Previously there was no validation on these fields and the errors would pop up after a minute or two. I wanted the errors to surface sooner. and here we are.

**Comment by davidnewhall** [comment]
I also use unraid, but I've customized my template, and I have all four starr apps configured, so I never hit this...

**Comment by jaschuu** [comment]
there is not a download path for lidarr
![image](https://user-images.githubusercontent.com/28653939/112264165-2fe1ce80-8cbc-11eb-8dfc-08e8a0374058.png)

**Comment by jaschuu** [comment]
If I leave it as is
![image](https://user-images.githubusercontent.com/28653939/112264278-5f90d680-8cbc-11eb-9b1a-6e9c5a02b8cc.png)

it goes back to this error
![image](https://user-images.githubusercontent.com/28653939/112264311-6e778900-8cbc-11eb-879b-614aa05c0292.png)

**Comment by davidnewhall** [comment]
Yeah I'm reproducing this. There are two fixes: change your tag back to an earlier version or delete the sections you do not use. I'm working on a fix now and I'll publish a new release shortly.

**Comment by jaschuu** [comment]
what is the earlier version tag? 
how do i change that?
I've never had to before

**Comment by davidnewhall** [comment]
Change the repository from `golift/unapckerr` to `golift/unpackerr:0.8.0-beta3`

**Comment by jaschuu** [comment]
also thank you for your quick response

**Comment by davidnewhall** [comment]
Please test the `golift/unpackerr:apifix` tag. Once I get confirmation this fixes it, I'll make a 0.9.1 release.

**Comment by jaschuu** [comment]
the apifix seems to work no errors.

**Comment by davidnewhall** [comment]
Thank you!

**Comment by jaschuu** [comment]
you are welcome, please let me know when I can change my repository back please.

**Comment by davidnewhall** [comment]
Give it about 10-20 minutes for Docker to build the `latest` tag. I'm drafting the release now.

**Comment by jaschuu** [comment]
is this correct? golift/unapckerr:latest

**Comment by davidnewhall** [comment]
In docker word, these two things are equal:  `golift/unapckerr:latest` and `golift/unapckerr` - either one gets the same thing.

**Comment by jaschuu** [comment]
ok, thank you again for your quick fix
