### ISSUE TITLE
Installation on shared seedbox (without root)

### ISSUE THREAD

**Issue by MeTimesThree** [davidnewhall/unpackerr#113]
Hi David,

is there a way to install unpackerr on a shared seedbox where i don't have root access?

I tried changing
INSTALLER="dpkg --force-confdef --force-confold --install"
to
INSTALLER="dpkg --force-not-root --root=$HOME --force-confdef --force-confold --install"

and
/tmp/${FILE}
to
${HOME}/tmp/${FILE}

The full INSTALLER-command evaluates to:
dpkg --force-not-root --root=/home/<USERNAME> --force-confdef --force-confold --install /home/<USERNAME>/tmp/unpackerr_0.9.1-331_amd64.deb

Installation sadly fails with the following error:
dpkg: error: unable to access the dpkg database directory /home/<USERNAME>//var/lib/dpkg: No such file or directory

Is there a way to install it on a shared box?

**Comment by davidnewhall** [comment]
Sure, the binary is on the releases pages. Combine that with a config file and you're good to go. No need to install a package.

**Comment by MeTimesThree** [comment]
Perfect!

I just had to change the two variables:
URL=$($CMD ${LATEST} | egrep "browser_download_url.*(${ARCH})\.linux\.${FILE}\"" | cut -d\" -f 4)
FILE=gz

And replace the path:
/tmp/${FILE}
with
${HOME}/${FILE}

and it succesfully downloaded with the default script.

It can then be installed with the following lines:

mkdir -p "${HOME}/software/unpackerr"
cd "${HOME}/software/unpackerr"
gunzip "${HOME}/${FILE}"

mv "${HOME}/unpackerr.amd64.linux" "${HOME}/software/unpackerr/unpackerr"
chmod u+x "${HOME}/software/unpackerr/unpackerr"
"${HOME}/software/unpackerr/unpackerr" --version

Thank you so much for your amazing work!
