### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by napei** [davidnewhall/unpackerr#114]
On windows this gets detected (still) as a fasle positive for a virus. Presumably from the UPX headers.

![image](https://user-images.githubusercontent.com/8946502/112414430-22891a80-8d76-11eb-8fb0-7afa855a0b85.png)

Just wondering if perhaps, for the sake of simplicity and the fact that it's small anyway the UPX compression could be removed or changedd in some way that doesn't make this happen?

@davidnewhall we discussed this a while back on discord and it appears it's still happening even with the latest release zipped up.

**Comment by davidnewhall** [comment]
UPX: 3-4MB
no UPX: 8-10MB

I can't share non-UPX versions on Discord because they go over 8 MB. I don't think I'll be removing it because with 20+ released compiled binaries it adds up.

**Comment by davidnewhall** [comment]
My understanding is that even without compression there are still false positives. Does this get caught? (no UPX, just ZIP)
[unpackerr.amd64.exe.zip](https://github.com/davidnewhall/unpackerr/files/6201865/unpackerr.amd64.exe.zip)

**Comment by davidnewhall** [comment]
Perhaps I can remove it for just Windows. Let me tinker on that idea.

**Comment by napei** [comment]
![image](https://user-images.githubusercontent.com/8946502/112414913-0174f980-8d77-11eb-8d3a-8239c3b28398.png)
No threat detected. The false positive is from the UPX header present. I see no benefit in 2021 to have a 3MB binary over an 8MB one. If you can't upload them to discord, paste a link to a release binary or pay for nitro tier 1?

**Comment by davidnewhall** [comment]
>  I see no benefit 

I'm just not you. ;)

**Comment by davidnewhall** [comment]
while you're at it, let me know if that binary I sent over works. It has a whole new set of logic for extraction ordering. :)

**Comment by napei** [comment]
> while you're at it, let me know if that binary I sent over works. It has a whole new set of logic for extraction ordering. :)
> re: [golift/xtractr#5](https://github.com/golift/xtractr/pull/5)

It appears to work fine.
![image](https://user-images.githubusercontent.com/8946502/112416007-f15e1980-8d78-11eb-8dca-7d46e5bdc0bd.png)

**Comment by davidnewhall** [comment]
It hasn't extracted anything yet. :D Just keep an eye on it for a day or two. Thank you!

**Comment by davidnewhall** [comment]
I'll cut a beta release in a bit so you can try that out. It'll have the correct version. I built that one before I pulled the current tag.

**Comment by davidnewhall** [comment]
New release is out. Please let me know if you have any problems! https://github.com/davidnewhall/unpackerr/releases/tag/v0.9.2-beta1
