### ISSUE TITLE
Malformed module reference when building from latest source

### ISSUE THREAD

**Issue by madcatsu** [davidnewhall/unpackerr#116]
Hi @davidnewhall 

I picked up a new error today in my build from latest source on Alpine Linux 3.11. This appeared since v0.8.0-beta2.

```build github.com/davidnewhall/unpackerr: cannot load io/fs: malformed module path "io/fs": missing dot in first path element```

This happened when executing ```go build -o /build/unpackerr -ldflags "-w -s"``` since my last successful build on 2021-03-19. Alpine Linux version hasn't changed for this build pipeline recently so I'm wondering if there is an upstream package dependency issue.

**Comment by davidnewhall** [comment]
```
[david@dns-mbp]00:03:03|~/go/src/github.com/davidnewhall/unpackerr$ git grep io/fs
[david@dns-mbp]00:03:08|~/go/src/github.com/davidnewhall/unpackerr$
```

Are you on Go 1.16? Does this happen with `master`?

**Comment by madcatsu** [comment]
Alpine 3.11 Go version is 1.13.13

This is on **master** branch.

Apologies, need to correct my statement above, this is happening when running `go get` before running `go build`

**Comment by davidnewhall** [comment]
I'm pretty sure I've included things that require at least Go 1.14. I'm not even sure how to downgrade to test atm. Can you upgrade?

**Comment by madcatsu** [comment]
Yup, might need to bump to a newer version of Alpine, will let you know what happens :)

**Comment by davidnewhall** [comment]
fwiw, I've been developing on 1.15 for what feels like a really long time. I recently bumped my entire build pipeline to 1.16.2. Had a few hiccups, but everything has been working fine.

**Comment by madcatsu** [comment]
Looks like this is the offending culprit...

```/go/pkg/mod/golift.io/xtractr@v0.0.8-0.20210325050400-2931a0c4c2d3/files.go:8:2: package io/fs is not in GOROOT (/usr/lib/go/src/io/fs)```

Go version = go version go1.15.10 linux/amd64

**Comment by davidnewhall** [comment]
And I'm 100% going to take advantage of some of the new 1.16 features, so I recommend getting all the wya up to date.

**Comment by davidnewhall** [comment]
Well this is good. That change is still in a pull request. https://github.com/golift/xtractr/pull/5

**Comment by madcatsu** [comment]
Cool. I'll check back one the PR is merged :)

My pipeline just runs weekly and only pushes to Docker registry with a successful build, so nothing broken in the wild yet.

**Comment by davidnewhall** [comment]
I just updated the PR and dropped the fix into master on Unpackerr. Lemme know if that fixes it. Thanks!

**Comment by madcatsu** [comment]
Builds and executes on Go 1.15 on Alpine 3.13 - unsure if there are any issues when it's actually running yet so I will test against Sonarr. If I still have problems I'll bump the container to Alpine Edge for now so that it's using Go 1.16.

I've mark as closed and will open a new issue if I run into a problem with Go 1.16 on Alpine 🤞

**Comment by davidnewhall** [comment]
I haven't introduced anything 1.16 specific yet, so 1.15 should work fine. `master` has a "large" set of changes (that xtractr PR), so I appreciate your testing. Thanks for the report!

**Comment by davidnewhall** [comment]
Apparently `io/fs` was added in Go 1.16: https://benjamincongdon.me/blog/2021/01/21/A-Tour-of-Go-116s-iofs-package/

I rolled that back to using an older `os` thing instead, so the 1.16 stuff is "gone" now. This is why it failed on 1.13.

**Comment by davidnewhall** [comment]
That new package is actually going to prove useful when I decide to add tests to the xtractr library.

**Comment by madcatsu** [comment]
Noted. Did you roll that back in xtractr or unpackerr?

**Comment by davidnewhall** [comment]
I rolled it back in that PR. I then `go get` that PR into Unpackerr's `master`. Once I get confirmation that [the original issue](https://github.com/davidnewhall/unpackerr/issues/85) I made that PR for is solved, and enough folks don't report problems with unpackerr, I'll merge it.
