### ISSUE TITLE
delete_delay defaulting to 1s instead of 5m

### ISSUE THREAD

**Issue by DataBitz** [davidnewhall/unpackerr#117]
The documentation says that the default for radarr.delete_delay and sonarr.delete_delay is 5m but from the logs it is reported as 1s.

Sonarr Config: 1 server: http://sonarr:8989, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 1s
--

https://github.com/davidnewhall/unpackerr

**Comment by davidnewhall** [comment]
That's rather interesting. Thanks for the report!

**Comment by davidnewhall** [comment]
The latest release fixes this bug. Thank you again!
