### ISSUE TITLE
Possible bug - "completed file still waiting"

### ISSUE THREAD

**Issue by zyzzma** [davidnewhall/unpackerr#123]
Hi, 

I love this container but unfortunately i keep getting the following error(?) here's the log:

https://imgur.com/a/uE4I3US

I don't know what's wrong?

Thanks for all the work that you do!

**Comment by davidnewhall** [comment]
There are no errors in that screenshot. Those are informational messages.
If you do not see those things in your queue, go into Sonarr or Radarr, click on `Activity`, then click `Options` in the top right and check the box to show all items.

**Comment by zyzzma** [comment]
Thanks for getting back to me so quickly! I did what you said, there was no box to show all items so I manually ticked every box and the same message in the log is still happening

**Comment by davidnewhall** [comment]
Is the item in your queue?

**Comment by zyzzma** [comment]
Yes it is in my sonarr queue

**Comment by davidnewhall** [comment]
The question is: why?
If you get it out of your queue you'll stop seeing that message.

**Comment by zyzzma** [comment]
Oh my thank you so much! Back to sonarr I go!
