### ISSUE TITLE
Error: Renaming temp file

### ISSUE THREAD

**Issue by zyzzma** [davidnewhall/unpackerr#124]
Hi, 

I have the following issue.
Running on Synology NAS docker

Thanks for your time!
See logs - https://imgur.com/a/MybkJzl

**Comment by davidnewhall** [comment]
The rest of the error tells you why it failed. You cut that off in your screenshot.

**Comment by zyzzma** [comment]
I didn't. Here's a full one - https://imgur.com/a/07rZanV

**Comment by davidnewhall** [comment]
That screenshot also cuts off all the errors. The `...` at the ends of each lines is an indicator the line has more data you can't see.

**Comment by zyzzma** [comment]
Oh I see! It says "refusing to overwrite existing file", does that mean it already unpacked and it would be essentially double unpacking? I apologize for all of this, I'm a complete noob as if it wasn't obvious enough. I'm still learning the ropes and appreciate all the effort you put into helping others!

**Comment by davidnewhall** [comment]
> does that mean it already unpacked

In my experience, that's exactly why this happens. It unpacked previously and the starr app never imported it. There may be more to the story, but I don't have enough logs to decipher it all. :)

**Comment by zyzzma** [comment]
I'll take your word for it who would know better than you! !solved thanks for your time today David have a great week!

**Comment by davidnewhall** [comment]
Thank you! You too!
