### ISSUE TITLE
Stanger behaviour with extracted Rars

### ISSUE THREAD

**Issue by joelang1699** [davidnewhall/unpackerr#127]
I'm having a small issue with this and Sonarr where torrent files are correctly detected, extracted and then imported into Sonarr, however it seems because the RAR folder is left, Sonarr doesn't detect the import (which it has processed) it still has the item in the que as it's detecting the RARA folder.

I need it to delete the RAR folder once extracted, this means Sonarr will no longer detect the RARs and subsequently remove from the que. Is this possible?

**Comment by austinwbest** [comment]
What you need to do is use a post processing category with the download client so sonarr changes it after import.

**Comment by joelang1699** [comment]
I suppose I should explain this a bit more. 

I was using Sonarr along with Rtorrent blackhole method, Rtorrent was set to copy the download into a finished folder and extract it. This works, Sonarr imports the extracted file however the original RAR folder is left requiring manual deletion, this is what I'm trying to eliminate.

So I decided to give this a try. I turned off RAR extraction to allow Unpackerr to do the job, the workflow is below.

1. Rtorrent downloads the torrent
2. Rtorrent **copies** it to a 'Finished' folder, this preserves the torrent for seeding
3. Unpackerr extracts the RARs
4. Sonarr detects the file and imports (moves) it.
5. The original RAR folder is left, because of this Sonarr doesn't remove the item from the Queue.
6. Sonarr returns "RAR file detected, will require manual cleanup"

So I'm looking for away for the original RARA folder to be deleted.

**Comment by bakerboy448** [comment]
Why are you using a black hole and not just connected directly into sonarr?  If it's a remote setup - use a remote mount and then a remote path map

but you'd need to script that as the rar files are intentionally left behind so you can not be an asshole and seed

**Comment by joelang1699** [comment]
The reason I use blackhole is is use Rtorrent is because I use the ratio rules/auto labelling with the client for monitoring the seeding process. I prefer having the download client handle the torrents instead of the PVR programs.

**Comment by joelang1699** [comment]
Assuming RTorrent just acts a dumb client, what should the workflow be?

This is on Unraid btw.

**Comment by bakerboy448** [comment]
You can still have rutorrent manage those

but remove the black hole and just link the app directly; you'd want to have the *arr use a post import category to change from the *arr's specific category and then set your times and all from there

**Comment by davidnewhall** [comment]
This part is not making sense to me:
> 5. The original RAR folder is left, because of this Sonarr doesn't remove the item from the Queue.

Sonarr doesn't give two licks about rar files. If it imports the item, it removes it from queue. What is the error you see in Sonarr that indicates why it's leaving the now-imported item in the activity queue?

I've never seen this message:
> 6. Sonarr returns "RAR file detected, will require manual cleanup"

> Assuming RTorrent just acts a dumb client, what should the workflow be?

Honestly, stop doing step 2:
> 2. Rtorrent copies it to a 'Finished' folder, this preserves the torrent for seeding

No one does this. Unpackerr doesn't need this, Sonarr doesn't need this. Configure Sonarr to copy/hard link files (not move) and let Unpackerr process the downloads location directly

**Comment by joelang1699** [comment]
Sorry for the delay in replying.

Okay so I've change the way things by following your instructions. Things seem to be working well.

One more question, do all downloads have to be under one folder? I usually have sub folders in the client according label/category. It just helps organising things a bit more.

**Comment by davidnewhall** [comment]
They can be in subfolders, as long as your paths are set correctly. It's fully configurable.

**Comment by joelang1699** [comment]
I just can't get this to work with sub folders at all. I've attached my unraid docker config.

The other issue is when unpackarr does extract, it extracts **inside** the torrent folder and doesn't delete the extract even after Sonarr/Radarr has successfully
![Uploading Screenshot 2021-06-04 212333.jpg…]()
 imported.

**Comment by davidnewhall** [comment]
To begin with, your paths are wrong. You probably want to add `/downloads/` to the beginning of them. They must always begin with a `/`. It's supposed to extract inside the torrent folder. That's where the starr apps import from. Your log file also looks like a path on your host and not a path in the docker container. You probably want to set that to to `/downloads/unpackerr.log`. Once you have a log file, you can inspect it to figure out why unpackerr can't delete the extracted files.

**Comment by joelang1699** [comment]
The torrents are not saved to the `/downloads ` directory as that's used for nzb downloads. I've got the torrent client downloading to another folder which is `/Torrent-Downloads`

I'm really not understanding how the folder paths are supposed to be setup.

**Comment by joelang1699** [comment]
Okay David I've made the changes. Once I added `/downloads/` as per your instruction everything started to work including the delete unpack function.

I did have to add some remote path mappings as the local folder is one deeper than the remote path.

Thank you to everyone who responded and especially you David.

**Comment by davidnewhall** [comment]
Glad you got it licked!
