### ISSUE TITLE
Extraction Failed. 

### ISSUE THREAD

**Issue by LeoRX** [davidnewhall/unpackerr#128]
Hi  David,

Thank you for the great tool.  Unpackerr generally works well for me.  On occasions, i get items in waiting or failed state.  A manual restart unpack will get things moving and extract all there are ready to extract.  Does it have something to do with my configuration ?  how can I troubleshoot this?

Thanks.

**Comment by davidnewhall** [comment]
The logs should provide all information necessary to determine what's happening, or not happening.

**Comment by LeoRX** [comment]
My bad.  found the paths typo in my config.  strange it still worked most of the time.

**Comment by davidnewhall** [comment]
Sometimes the items in queue have their path in the error message. Unpackerr can find that. Sometimes they do not, and it can't find them. Glad you found the problem!
