### ISSUE TITLE
sample.mkv

### ISSUE THREAD

**Issue by vadarr** [davidnewhall/unpackerr#129]
any way you can have unpackerr remove the sample.mkv or sample.mp4 after the extraction?

**Comment by davidnewhall** [comment]
Probably. Can you explain the problem you're having so we can find you a solution?

**Comment by joelang1699** [comment]
> any way you can have unpackerr remove the sample.mkv or sample.mp4 after the extraction?

I've often found that the sample.mp4/mkv is part of the original pre extraction torrent. Removing it would result in a corrupted torrent.

**Comment by davidnewhall** [comment]
@vadarr Please let me know if you still need a solution. Just re-open this issue.
