### ISSUE TITLE
Radarr 4 API issues

### ISSUE THREAD

**Issue by paulmorabito** [davidnewhall/unpackerr#130]
Hi,

I've recently noticed some issues with unpacking Radarr requests. The logs report:

```
2021/06/02 09:04:40 [ERROR] Radarr (http://192.168.1.191:7878/): api.Get(queue): failed:  (status: 404 Not Found): invalid status code, <200||>299: {
  "message": "NotFound"
}
```

I understand Radarr is making some changes on their API so possibly this is the issue?

**Comment by davidnewhall** [comment]
Did this begin after upgrading to Radarr 4? Unpackerr doesn't work with it yet.

**Comment by paulmorabito** [comment]
Just checked my version and yes, it's been upgraded to 4.0. Noted on above. Thanks.

**Comment by davidnewhall** [comment]
Will try to get a fix out in the next week or so.

**Comment by paulmorabito** [comment]
Thank you!
