### ISSUE TITLE
[Feature Request] Adding Scheduler to extract files

### ISSUE THREAD

**Issue by thundergreen** [davidnewhall/unpackerr#134]
Hello I am running in a very stupid issue. During the day / evening I'd like to watch some Movies. But if unparerr is running und extracting files the read speed is too slow to play some movies. Stuttering and completely stiopping of the movie is the result.

Would it therefore be possible to implement a scheduler for example: Extracting between x and x o'clock? That would make the app really perfect.

**Comment by davidnewhall** [comment]
Curious if you can schedule Radarr to only download during specific hours? Is this a feature any of these apps have? I wonder if you can set a `nice` value for the app when it starts. Is that something you've looked into? What OS are you running on? What causes the stuttering? (cpu usage, disk usage, etc)

**Comment by austinwbest** [comment]
You sure can, run a cron that kills it and another that starts. :)

Bad idea though as RSS will miss alot of stuff as a trade off. 

There is no plans to add schedules to the arr apps. You can kill /start unpackerr in the same manner without impact to the arr apps other than not being able to process the files but that will be the same result with a scheduler.

**Comment by davidnewhall** [comment]
I kinda feel like scheduling when unpackerr runs should be handled by a system task scheduler like systemd. I'll think about adding this into unpackerr, but I feel like there's a better solution somewhere.

**Comment by thundergreen** [comment]
Well I have disk usage too busy to watch movies yes .. stuttering is due to the unpack process itself . I already face a huge issue with my WD HDD which is pretty slowly .. watched on forum s bit didn't get the right hint how to increase read and write speed . Therefore I'd like having unpackerr only to act during night hours when nobody wants to watch a movie.also I think there could be an improvement by watching what radarr sonarr etc is doing not to unpack while radarr moves files .I'm using docker and couldn't get the hardlinks working at all ..o will post my config maybe someone sees the mistake?

**Comment by davidnewhall** [comment]
It looks like you have configured unpacker to write log files _into_ your container. This path should exist on a mounted volume so you don't make the container grow. 
```yaml
      - UN_LOG_FILE=/home/thundergreen/Docker/Configs/unpackerr
```
---
>  I think there could be an improvement by watching what radarr sonarr etc is doing not to unpack while radarr moves files 

What makes you think this is happening? Where are the files being moved from=>to? I bypass this slow disk problem by extracting - and watching - from different source disks. Starr apps move the files from the seed disk to the storage disk after unpackerr extracts them.

> I'm using docker and couldn't get the hardlinks working at all.

This is unrelated to unpackerr, but I'll try to help: How did you determine they're not working? Can you share logs from those applications when hard linking fails?

**Comment by davidnewhall** [comment]
I did a little looking into "docker container scheduling" and most folks suggest using `supervisord`, `systemd` or worst case, `cron`. My recommendation is to turn off the unpackerr container during the day, and start it again in the evening. 

There are probably a dozen different ways to accomplish this. I use unRaid, so I'd following the guidance provided [here](https://forums.unraid.net/topic/53905-docker-startstop-on-timer/). Looks like you're on Linux, so you'd probably use something like `cron` or [Ofelia](https://github.com/mcuadros/ofelia). There are other [docker schedulers](https://medium.com/@ArmandGrillet/comparison-of-container-schedulers-c427f4f7421) out there, how-to guides (kinda old) for [supervisor](https://blog.trifork.com/2014/03/11/using-supervisor-with-docker-to-manage-processes-supporting-image-inheritance/), and how-to guides for using [`timer` units with `systemd`](https://matthiasadler.info/blog/running-scheduled-tasks-in-docker-containers-with-systemd/).

If you get stuck, or need more assistance, please provide your host OS details and how you currently start and stop your docker containers.

**Comment by thundergreen** [comment]
thanks a lt for your feedback.

``` - UN_LOG_FILE=/home/thundergreen/Docker/Configs/unpackerr ``` where are the logs located inside Docker liek this I can map them.

I got the infor that those are not hardlinks like this:

```
thundergreen@EmEvTh-Data-Center:/media/thundergreen/Storage/Media/Movies/The Little Things (2021)$ stat  'The Little Things (2021) Bluray-1080p.mkv'
  File: The Little Things (2021) Bluray-1080p.mkv
  Size: 6530512630      Blocks: 12754920   IO Block: 4096   regular file
Device: 811h/2065d      Inode: 10223840    Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-06-27 23:16:14.548686881 +0200
Modify: 2021-06-26 12:28:50.702406035 +0200
Change: 2021-06-26 23:15:57.388188206 +0200

``` 

Do you see anything wrong in my docker-compose which would make hardlinks not working? I searched and used 

https://trash-guides.info/Hardlinks/How-to-setup-for/Docker/ to setup my docker but it seems hardlinks just not working :(

I can see when radarr is copying files and it takes ags to copy. Hardlnks are instantly right?

**Comment by davidnewhall** [comment]
Put the log file in your download location (generally) like so:
-  `UN_LOG_FILE=/data/torrents/completed/unpackerr.log`

If the file systems are different then hard links will not work. If it's the same file system then they should. Can you share `df -h` and explain where you're copying/hardlink from/to?

**Comment by davidnewhall** [comment]
You may also be able to constrain Unpackerr's ability to overrun your system with some docker tweaks:
https://docs.docker.com/config/containers/resource_constraints/#cpu

I'd probably start with `--cpu-shares=512` or `--cpu-shares=256` and go from there.

**Comment by davidnewhall** [comment]
And you asked about hard links. Yes, doing this will make hard links not work:
```
    volumes:
      - /media/thundergreen/Storage/Media/Series:/data/media/series # tv shows folder
      - /media/thundergreen/Storage/Media/Downloads/Torrents/completed:/data/torrents/completed # download folder
  ```

These two paths need to be in the same `volume` for hard links to work between them. So you'd want to do this instead of the two above:
```
    volumes:
      - /media/thundergreen/Storage/Media:/data/media # Media
```

And then you'd tell your apps (ie. Sonarr) that your downloads are at `/data/media/Downloads/Torrents/completed` and your tv shows are at `/data/media/Series`.

**Comment by thundergreen** [comment]
Hello, any new here on this issue? I am actually woring without the scheduler and your app works perfectly after pimping the onfi correctly .) But anyway i nice scheduler would be nice anyway .)

**Comment by austinwbest** [comment]
> I did a little looking into "docker container scheduling" and most folks suggest using `supervisord`, `systemd` or worst case, `cron`. My recommendation is to turn off the unpackerr container during the day, and start it again in the evening. 
> 
> There are probably a dozen different ways to accomplish this. I use unRaid, so I'd following the guidance provided [here](https://forums.unraid.net/topic/53905-docker-startstop-on-timer/). Looks like you're on Linux, so you'd probably use something like `cron` or [Ofelia](https://github.com/mcuadros/ofelia). There are other [docker schedulers](https://medium.com/@ArmandGrillet/comparison-of-container-schedulers-c427f4f7421) out there, how-to guides (kinda old) for [supervisor](https://blog.trifork.com/2014/03/11/using-supervisor-with-docker-to-manage-processes-supporting-image-inheritance/), and how-to guides for using [`timer` units with `systemd`](https://matthiasadler.info/blog/running-scheduled-tasks-in-docker-containers-with-systemd/).
> 
> If you get stuck, or need more assistance, please provide your host OS details and how you currently start and stop your docker containers.

I think this takes care of it?

**Comment by thundergreen** [comment]
Well it could ..but would be nice having a configuration parameter for this ..thanks anyway ..bit one other question.. I'll open a new issue tonight ..bit is it possible to check disk size before unpacking? It happened two times that my  disk ran full and my docker applications stopped working 🤔🤣

**Comment by austinwbest** [comment]
Having a preallocate space flag I don't think is a bad idea, I would def do a new issue for that and see what David thinks

**Comment by davidnewhall** [comment]
I use this library, and it would have to support this feature. https://github.com/nwaples/rardecode

You'd want to open a feature request there, but chances are it will be declined. It's pretty hard to know the size of the extracted data without reading it all.

**Comment by austinwbest** [comment]
> I use this library, and it would have to support this feature. https://github.com/nwaples/rardecode
> 
> You'd want to open a feature request there, but chances are it will be declined. It's pretty hard to know the size of the extracted data without reading it all.

The size is provided in the queue response I believe?

**Comment by thundergreen** [comment]
I was more thinking about something like a df-h command reading pre
configured Dev/xxxx free space before extracting a file. I might
misunderstand the way to archive this bit this is how I check free space
normally

nitsua ***@***.***> schrieb am Mo., 23. Aug. 2021, 21:48:

**Comment by davidnewhall** [comment]
This really sounds like a bad workaround for a problem that shouldn't exist. If your disk is full, stop downloading stuff? If you don't know it's full, add an alarm. [Notifiarr.com](https://Notifiarr.com) may be able to help you accomplish that. 

If unpackerr fills up the disk, it's going to just start throwing errors; that's expected. If I add a "disk space checker" it's going to illicit more problems from folks with not-full disks getting an error that their disk is full. More areas for problems to arise; I don't like that idea.

I strongly recommend monitoring your disk usage and free space if this is a problem you anticipate. 

**I will not add a scheduler or a disk space checker to unpackerr. Both of these situations can be handled in other ways.**

Good luck!
