### ISSUE TITLE
Feature Request: TAR file support

### ISSUE THREAD

**Issue by astro7467** [davidnewhall/unpackerr#136]
I see only rar unpacking is supported. LIDARR pulls approx 10% tar files - I have a bash script that deals with rar and tar and hoping to replace fully

**Comment by davidnewhall** [comment]
Unpackerr supports most files types including tar files.

**Comment by astro7467** [comment]
Thanks. Just reviewing release history and saw that 🤦‍♂️

**Comment by davidnewhall** [comment]
It uses this library and supports the same formats found in the readme. https://github.com/golift/xtractr
