### ISSUE TITLE
Sonarr API doesn't seem to work, logs show 404 on startup. 

### ISSUE THREAD

**Issue by thisisnotdave** [davidnewhall/unpackerr#137]
I've set up Unpackerr for Sonarr and Radarr, not sure if it matters but I'm running Fedora 31 currently. Radarr works fine but when reviewing the Unpackerr logs I'm seeing 404 errors coming from Sonarr. 

Unpackerr Config:
`################'
'### Episodes ###'
'################'
'[[sonarr]]'
  url = "http://127.0.0.1:8989"
  api_key = "****************"
## File system path where downloaded Sonarr items are located.
  paths = ["/mnt/nfs/Downloads/Incomplete/"]
## Default protocols is torrent. Alternative: "torrent,usenet"
#  protocols = "torrent"
## How long to wait for a reply from the backend.
#  timeout = "10s"
## Setting this to any negative number `-1` disables deleting extracted files.
#  delete_delay = "5m"
## Setting this to true deletes the entire original download folder after import.
#  delete_orig = false
`

Unpackerr Log:

2021/07/08 10:57:12.441429 sonarr.go:102: [ERROR] Sonarr (http://127.0.0.1:8989): api.Get(queue): failed:  (status: 404 Not Found): invalid status code, <200\|\|>299: { "message": "NotFound"}

Am I missing something? I can query the API from a browser without issue.

**Comment by austinwbest** [comment]
> I've set up Unpackerr for Sonarr and Radarr, not sure if it matters but I'm running Fedora 31 currently. Radarr works fine but when reviewing the Unpackerr logs I'm seeing 404 errors coming from Sonarr. 
> 
> Unpackerr Config:
> `################'
> '### Episodes ###'
> '################'
> '[[sonarr]]'
>   url = "http://127.0.0.1:8989"
>   api_key = "****************"
> ## File system path where downloaded Sonarr items are located.
>   paths = ["/mnt/nfs/Downloads/Incomplete/"]
> ## Default protocols is torrent. Alternative: "torrent,usenet"
> #  protocols = "torrent"
> ## How long to wait for a reply from the backend.
> #  timeout = "10s"
> ## How long ago a file must have been imported before deletion. The file must
> ## also not be part of an active queue item. Set this to "1m" to make sure files
> ## are deleted quickly after being imported. Recommend "5m". Uses Go Duration.
> ## Setting this to any negative number `-1` disables deleting extracted files.
> #  delete_delay = "5m"
> ## If you use this app with NZB you may wish to delete archives after extraction.
> ## General recommendation is: do not enable this for torrent use.
> ## Setting this to true deletes the entire original download folder after import.
> #  delete_orig = false
> `
> 
> Unpackerr Log:
> 
> 2021/07/08 10:57:12.441429 sonarr.go:102: [ERROR] Sonarr (http://127.0.0.1:8989): api.Get(queue): failed:  (status: 404 Not Found): invalid status code, <200\|\|>299: { "message": "NotFound"}
> 
> Am I missing something? I can query the API from a browser without issue. 

Are you using v2 of sonarr?

**Comment by thisisnotdave** [comment]
Yes I am, and sorry about the formatting I was trying to fix it up and get distracted with work.

**Comment by bakerboy448** [comment]
Sonarr v2 is EOL and depreciated.

**Comment by thisisnotdave** [comment]
Oh wow, I had no idea v3 was even out! Apologies, and thank you!
