### ISSUE TITLE
Unpackerr output to syslog is marked as "obsolete" on newer distros

### ISSUE THREAD

**Issue by pkreuzt** [davidnewhall/unpackerr#139]
I have recently upgraded my system to Bullseye and been since then receiving this warning on my logs:

```
Jul 27 19:32:56 localhost systemd[1]: /lib/systemd/system/unpackerr.service:17: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
Jul 27 19:32:56 localhost systemd[1]: /lib/systemd/system/unpackerr.service:18: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
```

Not a big problem, but maybe this should be looked upon on next release.

**Comment by davidnewhall** [comment]
Does this unpackerr no longer writes logs into `/var/log` by default?

**Comment by pkreuzt** [comment]
Warnings state output type is getting upgraded to "journal" automatically. I can still read unpackerr logs in syslog and daemon.log as usual. Seems like a facility change on logging configuration due to systemd.
