### ISSUE TITLE
Radarr only - not unpacking API error

### ISSUE THREAD

**Issue by Eddie563** [davidnewhall/unpackerr#143]
I have just logged on to Radarr and have seen a load of non unpacked files waiting to be processed. Unpackerr is showing the following.

[ERROR] Radarr (http://127.0.0.1:7878): c.Req(queue): failed: http://127.0.0.1:7878/api/queue (status: 404/404 Not Found): invalid status code, not 200

Sonarr is fine. I am guessing Radarr has updated something to do with the API in v4.

**Comment by davidnewhall** [comment]
What version are you running?

**Comment by austinwbest** [comment]
Radarr has removed legacy endpoints in v4 so you need to update your unpackerr

**Comment by davidnewhall** [comment]
Please upgrade to the latest version and re-open this issue if you're still getting this error. Thanks!

**Comment by Eddie563** [comment]
Apologies for not responding as i have been away. Likely a dumb question for most but is there an upgrade command?

**Comment by davidnewhall** [comment]
I realize you already upgraded, but the answer to your question depends on how you installed the app the first time.
