### ISSUE TITLE
Unpackerr access denied after upgrade

### ISSUE THREAD

**Issue by Eddie563** [davidnewhall/unpackerr#145]
I started with an issue that the API would not work with Radarr after their v4 update (https://github.com/davidnewhall/unpackerr/issues/143) , I was advised to upgrade Unpacker which i have done and it now reads the API correctly. What I am now running into is that it cannot access the files to unpack it. i have updated the systemd to use an account:group (not running as unpackerr:unpackerr) which has permissions and did a daemon reload, but seems that it still cannot access the files.

the error is:

[Radarr] Completed item still waiting: filename, no extractable files found at: /home/account/rtorrent/download/filename (stat err: stat /home/account/rtorrent/download/filename: permission denied)

**Comment by davidnewhall** [comment]
Not entirely sure what you're looking for here. The permissions or ownership is not correct.

**Comment by Eddie563** [comment]
the linux permissions has not changed from when it was working, the only thing i updated was unpackerr today when i upgraded.

**Comment by davidnewhall** [comment]
>  i have updated the systemd to use an account:group (not running as unpackerr:unpackerr)

Did you edit the systemd service unit file, or did you make an override file? Did the upgrade wipe out your changes? Did you put them back? Do you have any questions for me, or are you waiting for me to ask you questions?

**Comment by Eddie563** [comment]
Apologies. I'll just go back to doing things manually.

**Comment by davidnewhall** [comment]
I'm just trying to figure out what you're requesting on this issue. Without questions from you, I'm just not sure what you need help with, or if you're even requesting help. This seems more like a help request than a bug report, so I have to ask questions to figure out a solution. 

> I'll just go back to doing things manually.

You saying this makes me think either you don't want to answer my questions, or you're taking my question as hostile. I'm not being hostile, I'm just asking questions. Please don't attach feelings or emotions to the questions I ask. They're based in logic and designed to lead a solutions with haste.
