### ISSUE TITLE
Replace relative repo links in README me with absolute links.

### ISSUE THREAD

**Issue by splitsurround** [davidnewhall/unpackerr#147]
Hi!

I've been running the GUI, but for some reason it stopped working and I can't get it to work again. All things being equal, I'd prefer to use docker compose, but the example compose file on your GitHub is giving a 404 error.

Thanks.

**Comment by davidnewhall** [comment]
It opens for me? https://github.com/davidnewhall/unpackerr/blob/master/examples/docker-compose.yml

**Comment by splitsurround** [comment]
That worked for me too! But clicking on the site gave me a 404, weird. Thank you!

**Comment by davidnewhall** [comment]
Did you click on it from DockerHub's website? Docker copies the readme from the repo and breaks half the links. I'll fix that.

**Comment by splitsurround** [comment]
yes I did.

**Comment by davidnewhall** [comment]
Going to leave this open to remind me to fix the links.

**Comment by splitsurround** [comment]
Sounds good-

Do you mind if i ask you another question about the compose file? I
field in everything that I thought was mandatory (same info i filled in
using the Web UI), but I keep getting this error :

unpackerr  | 2021/08/30 21:36:23 [ERROR] webhook without a URL configured;
fix it

unpackerr exited with code 1


I didn't realize that I had to enter anything in the webhook group. Anyhow,
any help would be much appreciated.


Thanks.

**Comment by davidnewhall** [comment]
Remove all the `WEBHOOK` stuff, or comment it out. That file is an example with (almost?) all the variables shown. Many of those you won't need and you should just remove (or comment) them. You can look at (and read, re-read) the example config file to get an idea what things you "need" -> https://github.com/davidnewhall/unpackerr/blob/master/examples/unpackerr.conf.example

Everything has a default and almost every setting (except things like urls and keys) are optional.

**Comment by splitsurround** [comment]
that's what I thought, thank you. I'll keep investigating...
