### ISSUE TITLE
Love Unpackerr, but sometimes it just doesn't work

### ISSUE THREAD

**Issue by splitsurround** [davidnewhall/unpackerr#148]
Hey there! Occasionally (and I can't figure out why) I'll get this error when I look at what's happening in terminal in OS X (this is running the Web UI or docker compose)

"[Radarr] Completed item still waiting: Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES, no extractable files found at: /Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES (stat err: stat /Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES: no such file or directory)"

So it's saying there's no .rar. file AND the directory doesn't exist, but both things aren't true.

Thoughts? Generally, it just works, this only happens I'd say about.... 20% of the time.

Thank you for any insight!

**Comment by davidnewhall** [comment]
Are you running this natively on macOS, or in Docker? If in Docker, please show me your volume mappings.

What is the full name of the rar file in that folder?

**Comment by splitsurround** [comment]
I was running it natively in OS X but also fired up Docker, thinking that maybe the web UI wasn't working. I'm afraid I'm a bit of a luddite with Docker so I'm not sure what to type to show you my volume mappings. Here's the rar name though:

escape.room.2019.rerip.1080p.bluray.x264-drones.rar

**Comment by davidnewhall** [comment]
If you're running natively on macOS, and this folder exists ` /Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES` then I'd suspect a permissions issue preventing the app from getting there. If you're getting the error that folder doesn't exist in Docker: that's totally expected because it doesn't exist in Docker.

**Comment by splitsurround** [comment]
Interesting. Ok, so I should look into how to make the permissions on my entire "download" drive folder be correct?

Thank you!

**Comment by davidnewhall** [comment]
I think that's the first thing to validate. I don't know much about your setup (yet), and permissions issues are rare, but based on what you're describing it sounds like the most plausible problem.

**Comment by davidnewhall** [comment]
I just want to ask again.... the Radarr movie Escape Room is inside a folder named `FLAC Music`?

**Comment by splitsurround** [comment]
Yes, correct. One a volume called "Music Box".

**Comment by austinwbest** [comment]
Why in the world is a downloaded & pending movie in a folder called FLAC Music which is in another called Music Box...

**Comment by splitsurround** [comment]
it's just old nomenclature for an old workflow. But this is an external mounted drive that serves only for downloads. ALL downloads for Radarr, Sonarr, etc, go in the "FLAC MUSIC" folder. Does it matter what it's called? If so I can certainly rename it.

**Comment by davidnewhall** [comment]
It shouldn't matter, but it sure seems odd, and since your issue is literally "Can't find the files" I just wanted to validate that's accurate.

**Comment by splitsurround** [comment]
the odd thing, to me, is that it works fine most of the time. So clearly it sees the volume ok, at least some of the time.

**Comment by davidnewhall** [comment]
"works most of the time" is normally a Docker problem. Did you install via brew, or are you running the gui app?

**Comment by splitsurround** [comment]
GUI

**Comment by davidnewhall** [comment]
you can try turning on debug. Not sure if it will help, but perhaps. I'll make a new build for you a in few and attach it to my next comment. I've made a lot of changes recently around finding files, so perhaps I fixed whatever this is....

**Comment by splitsurround** [comment]
oh ok thank you, I definitely appreciate it! I'll be standing by...

**Comment by davidnewhall** [comment]
Give this a whirl. [Unpackerr.app.zip](https://github.com/davidnewhall/unpackerr/files/7131436/Unpackerr.app.zip)

**Comment by splitsurround** [comment]
installed! It's running through it's paces looking at everything, I'll update you when there's news to share, thanks

**Comment by splitsurround** [comment]
ok this is interesting. I manually went to the folder in question and extracted the rar, and it took a long time. when done there was NO movie file, which would make what unpackerr is reporting correct. I copied the whole folder to my local drive and extracted it and it worked fine, so...I bet you're right, there was a permissions issue. If it happens again however, should I ping you?

**Comment by davidnewhall** [comment]
How did you extract the rar? What app wrote the files? How do you normally start that app? 

Show me the output of these terminal commands, please:
```
ls -ld "/Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES"
ls -ld "/Volumes/Music Box/FLAC Music"
ls -ld "/Volumes/Music Box"
```

And see if this writes files or produces errors:
```
cd "/Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES"
unrar x escape.room.2019.rerip.1080p.bluray.x264-drones.rar
```

If you don't have `unrar`, install it with brew: `brew install unrar`. If you don't have brew, then uh.. install that too: https://brew.sh

**Comment by splitsurround** [comment]
1. drwxrwxrwx@ 95 jgreber  staff  3230 Sep  8 13:43 /Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES
2.  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
3. drwxrwxr-x@ 13 jgreber  staff  510 Feb 21  2021 /Volumes/Music Box

**Comment by davidnewhall** [comment]
This produced an error?

```
ls -ld "/Volumes/Music Box/FLAC Music"
```

**Comment by splitsurround** [comment]
I extracted the rar by double clicking on it, which launches The Unarchiver app. Not sure what you mean by what app wrote the files.

Normally, if I'm manually un-raring something, I double click the .rar file to start it. However, while some apps just unpack it then, this one asks for a location- I wonder if that might be causing an issue?

**Comment by splitsurround** [comment]
I just did that command (ls -ld "/Volumes/Music Box/FLAC Music") again, and got this. I think I mis-typed the first time:

drwxrwxrwx  1456 jgreber  staff  49504 Sep  8 14:00 /Volumes/Music Box/FLAC Music

**Comment by davidnewhall** [comment]
What app wrote this folder and the contents? `/Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES` The answer is usually a torrent or usenet downloader. Then, I ask how you start that app? Double-click an icon? brew services?

**Comment by davidnewhall** [comment]
Please share the output of this command:
```
ls -ld@ /Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES /Volumes/Music Box
```

This should contain the extended attributes applied to these folders.

**Comment by splitsurround** [comment]
greber-fever:unpackerr jgreber$ ls -led@ "/Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES" "/Volumes/Music Box"
drwxrwxr-x@ 13 jgreber  staff   510 Feb 21  2021 /Volumes/Music Box
	com.apple.FinderInfo	  32 
drwxrwxrwx@ 95 jgreber  staff  3230 Sep  8 13:43 /Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES
	com.apple.quarantine	  63 



ANd I understand your question now. I have overseerr working with Radarr and Sonarr, all linked to the Transmission app. That is an always on app for me, but I start it by launching it from the OS X dock.

**Comment by davidnewhall** [comment]
okay. I'm rather stumped at this point. It seems as though you're running all the apps as the same user, your user, and your user has full access to all these folders. I don't see any attributes or ACLs that would cause unpackerr to not find those files, or the containing directory as the error indicates. The folder itself has the quarantine attribute, but that should not prevent unpackerr from finding it. You can try removing that just to test... 
```
sudo xattr -d com.apple.quarantine "/Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES"
```

**Comment by splitsurround** [comment]
well to be fair I did the permissions thing after it "didn't work", but I hear ya.  Here's what I got when I ran the command:

greber-fever:unpackerr jgreber$ sudo xattr -d com.apple.quarantine "/Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES"
Password:
greber-fever:unpackerr jgreber$

**Comment by davidnewhall** [comment]
yeah sudo will ask for your Mac password. should be no output after that. Looks like it worked. 
Run this again and confirm the `@` is gone from the permissions:
```
ls -led@  "/Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES"
```

```
# It was:
drwxrwxrwx@ 95 jgreber staff 3230 Sep 8 13:43 /Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES

# it should change to:
drwxrwxrwx 95 jgreber staff 3230 Sep 8 13:43 /Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES

**Comment by splitsurround** [comment]
yep:

drwxrwxrwx  98 jgreber  staff  3332 Sep  8 14:28 /Volumes/Music Box/FLAC Music/Escape.Room.2019.RERIP.1080p.BluRay.x264-DRONES

**Comment by davidnewhall** [comment]
maybe unpackerr will find it now? 🤞 I'm out of ideas at this point. :(

**Comment by splitsurround** [comment]
You're good man. Thanks so much for the hand holding. I'll try to test it again with something and will update this thread.  thanks again.

**Comment by splitsurround** [comment]
Well, it seems good, it worked on the first show that was rar'd last night. Thanks again!

**Comment by davidnewhall** [comment]
If you run into more problems, please re-open this issue, or make a new one and reference this one. Thanks!
