### ISSUE TITLE
Multiple issues on version 0.9.8 (deb package, arm64)

### ISSUE THREAD

**Issue by pkreuzt** [davidnewhall/unpackerr#150]
Following upgrade, I'm having these new issues:

- URLs for *arr services have changed format. Before it was enough with "http://127.0.0.1:port", now I need to add base_url to get it working ("http://127.0.0.1:port/base_url"). Most of my *arr apps have not upgraded since previous unpackerr version, so it must be a change here. Not a big issue, just documenting here if anyone runs into this.

- Logs show messages from unpackerr trying to extract files that are from the "wrong" app. Like classifying a compressed movie added via Radarr supposedly belonging to Sonarr queue. I've seen this even with files added to torrent client manually that don't belong to any *arr app. Watch folder is not enabled in my config.

- Extracted and imported files are not removed. Tried uncommenting "delete_delay=5m" setting on config (which was not necessary before, likely default) but doesn't work either.

**Comment by davidnewhall** [comment]
1. Correct, it ued to follow redirects, and now it complains about a wrong URL. I may adjust this a bit later since redirects are OK for GET requests and that's all unpackerr does (today).
2. This is pretty hard to believe since none of the code in unpackerr actually changed: just external libraries. Can you show me logs that depict this behavior?
3. Again, none of that code changed. Please show me the logs.

**Comment by pkreuzt** [comment]
Enabled debug to get a bit more info. I'll copy some extracts:

```
2021/09/12 00:21:45.302763 handlers.go:75: [Sonarr] Waiting for Start Delay: Las formas antiguas (The Old Ways) (2020)
 [BluRay Rip][AC3 5.1 Castellano][www.maxitorrent.com] (1m0s remains)
2021/09/12 00:21:45.302958 sonarr.go:144: [DEBUG] Sonarr (http://127.0.0.1:8989/sonarr): completed (torrent:100%): Las
 formas antiguas (The Old Ways) (2020) [BluRay Rip][AC3 5.1 Castellano][www.maxitorrent.com] (Ep: 0)
2021/09/12 00:21:45.303092 handlers.go:75: [Sonarr] Waiting for Start Delay: Black Rain (1m0s remains)
2021/09/12 00:21:45.303160 sonarr.go:144: [DEBUG] Sonarr (http://127.0.0.1:8989/sonarr): completed (torrent:100%): Bla
ck Rain (Ep: 0)
2021/09/12 00:21:45.303374 handlers.go:191: [DEBUG] Sonarr: Errors encountered looking for Gamer.DVD.XviD.[www.Divxtot
aL.com] path: ["stat /mnt/descargas/completas/Gamer.DVD.XviD.[www.DivxtotaL.com]: no such file or directory"]
2021/09/12 00:21:45.303455 handlers.go:209: [DEBUG] Sonarr: Configured paths do not exist; could not find alternative 
path in error message for Gamer.DVD.XviD.[www.DivxtotaL.com]
2021/09/12 00:21:45.303555 handlers.go:75: [Sonarr] Waiting for Start Delay: Gamer.DVD.XviD.[www.DivxtotaL.com] (1m0s 
remains)
```
Those are movies added via Radarr. Moreover, I read this:

```
2021/09/12 00:21:45.304615 handlers.go:75: [Sonarr] Waiting for Start Delay: Biblioteca Completa Sidera Visus - 2015-02-07 (1m0s remains)
2021/09/12 00:21:45.304746 sonarr.go:144: [DEBUG] Sonarr (http://127.0.0.1:8989/sonarr): completed (torrent:100%): Biblioteca Completa Sidera Visus - 2015-02-07 (Ep: 0)
```
This is not a movie nor a series, it's just a SF book collection I added manually to transmission. Not in Radarr or Sonarr, and I have no Readarr configured.

**Comment by davidnewhall** [comment]
All of these things are in your Sonarr Queue. Sonarr is just hiding them from you. Go to `Activity -> Options` (in the top right). Check the box to show unknown items. To fix it, you need to setup a "category or tag" in your download client, and assign it to Sonarr. Then when you download stuff manually Sonarr won't pick it up. You want to do this with any Starr apps you use. ![Screen Shot 2021-09-12 at 2 35 26 AM](https://user-images.githubusercontent.com/2402929/132982685-78e11536-78d4-474d-ac30-ce4c40f296dc.png)

**Comment by pkreuzt** [comment]
OK, I understand *arr apps do retrieve a full list of transfers from the torrent client, then pick up "their" ones to show, and filter out foreign others. Categories _should_ be unnecessary, since Sonarr (or any other *arr) already knows which ones it has to manage internally. It's Unpackerr the one who doesn't know. Shouldn't it worry only about the (already filtered) list of transfers it gets from Sonarr?

**Comment by austinwbest** [comment]
That isn't accurate at all of I am understanding you. Categories are absolutely needed or else the queue would be a train wreck.

The ones you listed should not be in unknown as they are in a delay start status.

Honestly unpackerr could ignore those but it doesn't hurt anything to track them in the logs too.
