### ISSUE TITLE
Radarr and Sonarr in one download folder creates issues

### ISSUE THREAD

**Issue by Melantrix** [davidnewhall/unpackerr#152]
I've configured Unpackerr today because of a certain series that needed to be extracted for every episode. Everything went smoothly until i restarted the docker and i saw it was unpacking a finished episode again. (it was already successfully extracted). 

After some searching i saw that it detected every episode two times, once from Sonarr and once from Radarr. I have checked my config file and that seems all right -> for each instance i have uncommeted the header, i've added the unique url, the api key and the path. 

The only thing i can think of that creates this issue is that in my case both Sonarr and Radarr uses the same download agent which moves completed downloads to the same folder. So both are watching /completed.

So somehow, the api communication is not used to detect the queue? i'm not sure what to do here, is there any possibility to check this or fix this? For now i've disabled the Radarr part of the configuration and it is working correctly now.

**Comment by davidnewhall** [comment]
You'll need to configure sonarr and radarr correctly by adding tags or labels. Simple as that.

**Comment by austinwbest** [comment]
That won't be the case. You can have 10 instances downloading to the same place, arr apps don't care. They monitor the label you have set in them and that's all. Id recommend making sure that is setup right in the arr apps.

**Comment by davidnewhall** [comment]
To see what unpackerr sees: Click Activity then Options in the top right. Check the box to include unknown items.￼

**Comment by Melantrix** [comment]
> To see what unpackerr sees: Click Activity then Options in the top right. Check the box to include unknown items.￼

ah okay, never knew that. i'm not using tags so i'll look into that to fix it. Thanks for the help.

**Comment by Melantrix** [comment]
Hmm, while i appreciate the quick response i'm not sure using labels or tags fixes this for me. I'm  not using any tags or labels. If i understand them correctly its a way to use different settings/profiles for different items. But as i said, i don't need that. 

Why does Unpackerr even look at the unkown items? Apparently there is already a distinction within the *ARR apps to be able to ignore items from another *ARR app. Can't Unpacker use the same method?

**Comment by austinwbest** [comment]
You have to setup the labels in the arr apps  correctly.

Settings > download clients.

Each arr app has a label it watches, that is what is listed in the activity of each app. Unpackerr watches the same queue endpoint.

**Comment by davidnewhall** [comment]
Unpackerr looks at unknown items because they are in the queue. Any app that integrates will see them too. Recommend avoiding unknown items by setting labels for your downloads. What you are reporting right now is the second most commonly reported problem. Many folks don't set up their starr apps correctly.￼ ez fix though.

**Comment by davidnewhall** [comment]
Let me know if you need more assistance.
