### ISSUE TITLE
Add ability to delete only the txt extraction log file for 'Folder'.

### ISSUE THREAD

**Issue by jgosnell56** [davidnewhall/unpackerr#159]
Need a way to disable the extraction log that is placed in the same folder as the extracted files.  I see how to stop the primary logging in the config folder but not the secondary extraction log.

**Comment by davidnewhall** [comment]
What is the problem you believe this solution will solve?

**Comment by jgosnell56** [comment]
In my particular case, when I tell Sonarr to remove delete the series and remove folders, the folders are not fully removed because the Unpackerr logfile is in the directory so I am left with series folders that only contain that log file instead of the folders being deleted.  Same goes for Radarr and even Qbitorrent.  None of the applications can do a full delete because that file is in the folder.  Hope that make sense.

**Comment by davidnewhall** [comment]
Normally, Unpackerr deletes this file when it deletes the stuff it extracted. Any idea what that cleanup process isn't happening? Did you disable `delete_after`? If yes, why?

**Comment by bakerboy448** [comment]
wait a minute - removing a series from sonarr has nothing to do with a download directory

it almost sounds like you're downloading to and extracting within your library/root folders?

**Comment by jgosnell56** [comment]
Yes, you guys are right on the directory.  I went back to double check my setup and Sonarr/Radarr does move the extracted file to their directories which means they are not relevant.  It is only Qbit that cannot delete the full directory due to the logfile.  I do not have delete_after enabled because I seed my torrents for a period of time after download.  Also, I download some movie torrents directly with Qbit into a separate folder that PLEX has access to for a library.  In that situation, Qbit can remove all downloaded files and Plex can remove the actual video file but neither remove the entire folder because of the log.  
I realize I may have a unique situation here.  Just curious if that log can be disabled so the between Qbit and Plex, the entire folder can be removed.

**Comment by davidnewhall** [comment]
You just need to turn delete_after on. Not delete_orig.

**Comment by jgosnell56** [comment]
That will delete the extracted files, right? In the instance of the separate area that Plex uses, the delete_after will remove the extracted video file and therefore not available in Plex.

**Comment by davidnewhall** [comment]
Can you share your entire unpacker config? (don't need api keys)

**Comment by jgosnell56** [comment]
> Unpackerr won't extract something if it's not in radarr/sonarr/etc.

It does when I use the "watch folder" feature.

**Comment by davidnewhall** [comment]
Yeaaaaa, okay, I think I get it. You're making unpackerr extract directly into a library folder. Like baker said. hmmmm

**Comment by jgosnell56** [comment]
`##      Unpackerr Example Configuration File      ##
## The following values are application defaults. ##
## Environment Variables may override all values. ##
####################################################

# [true/false] Turn on debug messages in the output. Do not wrap this in quotes.
# Recommend trying this so you know what it looks like. I personally leave it on.
debug = false

# Disable writing messages to stdout. This silences the app. You should set a log
# file below if you set this to true.
quiet = true

# Write messages to a log file. This is the same data that is normally output to stdout.
# This setting is great for Docker users that want to export their logs to a file.
# The alternative is to use syslog to log the output of the application to a file.
# Default is no log file; this is unset. log_files=0 turns off auto-rotation.
# Default files is 10 and size(mb) is 10 Megabytes; both doubled if debug is true.
# Windows paths must use two backslashes: "C:\\Some\\Path\\Unpacker.log" (true everywhere).
#log_file = "/config/unpackerr.log"
#log_files = 10
#log_file_mb = 10

# How often to poll sonarr and radarr.
# Recommend 1m-5m. Uses Go Duration.
interval = "2m"

# How long an item must be queued (download complete) before extraction will start.
# One minute is the historic default and works well. Set higher if your downloads
# take longer to finalize (or transfer locally). Uses Go Duration.
start_delay = "10m"

# How long to wait before removing the history for a failed extraction.
# Once the history is deleted the item will be recognized as new and
# extraction will start again. Uses Go Duration.
retry_delay = "5m"

# How many files may be extracted in parallel. 1 works fine.
# Do not wrap the number in quotes. Raise this only if you have fast disks and CPU.
parallel = 2

# Use these configurations to control the file modes used for newly extracted
# files and folders. Recommend 0644/0755 or 0666/0777.
file_mode = "0666"
dir_mode = "0777"

##-Notes-#######################################################################
## The following sections can be repeated if you have more than one Sonarr,   ##
## Radarr or Lidarr, Readarr, Folder or Webhook.                              ##
## You must uncomment the [[header]] and api_key at a minimum for Starr apps. ##
################################################################################

################
### Webhooks ###
################
# Sends a webhook when an extraction queues, starts, finishes, and is deleted.
# Created to integrate with notifiarr.com.
# Also works natively with Discord.com, Telegram.org, and Slack.com webhooks.
# Can possibly be used with other services by providing a custom template_path.
###### Don't forget to uncomment [[webhook]] and url at a minimum !!!!
#[[webhook]]
#  url    = "https://notifiarr.com/notifier.php?integration=unpackerr&api=api_key_from_notifiarr_com"
#  name   = ""    # Set this to hide the URL in logs.
#  silent = false # do not log success (less log spam)
#  events = [0]   # list of event ids to include, 0 == all.
## Advanced Optional Webhook Configuration
#  nickname      = ""    # Used in Discord and Slack templates as bot name, in Telegram as chat_id.
#  channel       = ""    # Also passed into templates. Used in Slack templates for destination channel.
#  exclude       = []    # list of apps to exclude, ie. ["radarr", "lidarr"]
#  template_path = ""    # Override internal webhook template for discord.com or other hooks.
#  ignore_ssl    = false # Set this to true to ignore the SSL certificate on the server.
#  timeout       = "10s" # You can adjust how long to wait for a server response.
#  content_type  = "application/json" # If your custom template uses another MIME type, set this.

################
### Episodes ###
################
[[sonarr]]
url = "http://10.10.10.10:8989"
api_key = "9f5cd63bfc224ac3a74c46bcfb08561a"
## File system path where downloaded Sonarr items are located.
paths = ["/torrents/TorrentFiles"]
## Default protocols is torrent. Alternative: "torrent,usenet"
protocols = "torrent"
## How long to wait for a reply from the backend.
timeout = "20s"
## How long ago a file must have been imported before deletion. The file must
## also not be part of an active queue item. Set this to "1m" to make sure files
## are deleted quickly after being imported. Recommend "5m". Uses Go Duration.
## Setting this to any negative number `-1` disables deleting extracted files.
#  delete_delay = "5m"
## If you use this app with NZB you may wish to delete archives after extraction.
## General recommendation is: do not enable this for torrent use.
## Setting this to true deletes the entire original download folder after import.
  delete_orig = false

################
#### Movies ####
################
#[[radarr]]
#  url = "http://127.0.0.1:7878"
#  api_key = "0123456789abcdef0123456789abcdef"
## File system path where downloaded Radarr items are located.
#  paths = ["/downloads"]
## Default protocols is torrents. Alternative: "torrent,usenet"
#  protocols = "torrent"
## How long to wait for a reply from the backend.
#  timeout = "10s"
## How long ago a file must have been imported before deletion. The file must
## also not be part of an active queue item. Set this to "1m" to make sure files
## are deleted quickly after being imported. Recommend "5m". Uses Go Duration.
## Setting this to any negative number `-1` disables deleting extracted files.
#  delete_delay = "5m"
## If you use this app with NZB you may wish to delete archives after extraction.
## General recommendation is: do not enable this for torrent use.
## Setting this to true deletes the entire original download folder after import.
#  delete_orig = false

################
#### Albums ####
################
#[[lidarr]]
#  url = "http://127.0.0.1:8686"
#  api_key = "0123456789abcdef0123456789abcdef"
## File system path where downloaded Lidarr items are located.
#  paths = ["/downloads"]
## Default protocols is torrent. Alternative: "torrent,usenet"
#  protocols = "torrent"
## How long to wait for a reply from the backend.
#  timeout = "10s"
## How long ago a file must have been imported before deletion. The file must
## also not be part of an active queue item. Set this to "1m" to make sure files
## are deleted quickly after being imported. Recommend "5m". Uses Go Duration.
## Setting this to any negative number `-1` disables deleting extracted files.
#  delete_delay = "5m"
## If you use this app with NZB you may wish to delete archives after extraction.
## General recommendation is: do not enable this for torrent use.
## Setting this to true deletes the entire original download folder after import.
#  delete_orig = false

################
# Publications #
################
#[[readarr]]
#  url = "http://127.0.0.1:8787"
#  api_key = "0123456789abcdef0123456789abc"
## File system path where downloaded Readarr items are located.
#  paths = ["/downloads"]
## Default protocols is torrent. Alternative: "torrent,usenet"
#  protocols = "torrent"
## How long to wait for a reply from the backend.
#  timeout = "10s"
## How long ago a file must have been imported before deletion. The file must
## also not be part of an active queue item. Set this to "1m" to make sure files
## are deleted quickly after being imported. Recommend "5m". Uses Go Duration.
## Setting this to any negative number `-1` disables deleting extracted files.
#  delete_delay = "5m"
## If you use this app with NZB you may wish to delete archives after extraction.
## General recommendation is: do not enable this for torrent use.
## Setting this to true deletes the entire original download folder after import.
#  delete_orig = false

##-Folders-#######################################################################
## This application can also watch folders for things to extract. If you copy a ##
## subfolder into a watched folder (defined below) any extractable items in the ##
## folder will be decompressed. This has nothing to do with Starr applications. ##
##################################################################################
[[folder]]
## Windows paths must use two backslashes: "C:\\Some\\Folder\\To\\Watch"
path = "/torrents/musicvids"
## Path to extract files to. The default (leaving this blank) is the same as `path` (above).
extract_path = "/torrents/musicvids/temp"
## Delete extracted or original files this long after extraction. Set to 0 to disable all deletes. Uses Go Duration.
#  delete_after = "10m"
## Delete extracted files after successful extraction? true/false, no quotes. Honors delete_after.
# delete_files = true
## Delete original items after successful extraction? true/false, no quotes. Honors delete_after.
#  delete_original = false
## Move extracted files into original folder? If false, files go into an _unpackerred folder.
move_back = true`

**Comment by bakerboy448** [comment]
Why have media downloaded outside of the *Arrs?
If manually queued up, add it to *Arr's client category and it'll be imported (or easily  manually imported from activity if not parsable or some reason)

**Comment by davidnewhall** [comment]
> Why have media downloaded outside of the *Arrs?

"musicvids"

**Comment by jgosnell56** [comment]
It downloads using the Qbit RSS feed.  I cannot get any of the *arr's to grab that media.

**Comment by davidnewhall** [comment]
After unpackerr extracts the files into `/torrents/musicvids/` what happens with them? Plex sees that folder as a library?

**Comment by davidnewhall** [comment]
Can you jump on [Discord](https://golift.io/discord)? This may be easier. :P

**Comment by jgosnell56** [comment]
Yes, in general chat or in a DM to someone?

**Comment by davidnewhall** [comment]
TODO: Add feature to `[folder]` that allows deleting the extraction log txt file after extractions are successful.
