### ISSUE TITLE
Add ability to call a URL every xx minutes as a way of monitoring that Unpackerr is running

### ISSUE THREAD

**Issue by hansenc0705** [davidnewhall/unpackerr#160]
I use [Uptime Kuma](https://github.com/louislam/uptime-kuma) to monitor all aspects of my Media Management solution and would like to monitor Unpackerr with it was well.

One of the methods Uptime Kuma supports is monitoring via a PUSH URL. A simple call of the URL it provides when setting up the monitor is enough to keep it happy as long as the call comes every X minutes.

![image](https://user-images.githubusercontent.com/10247644/143596116-ceb35d03-b401-4cac-9e45-2bf943ec1a71.png)

Happy to answer questions or provide additional details. Right now I'm using a scheduled task that checks for the process and if its running it will ping the URL but it would be awesome to have something integrated if possible.

**Comment by davidnewhall** [comment]
Steps:
1. Setup a watch folder.
1. Setup a web hook.
1. Put a folder in your watch folder.
1. Add a tiny zip file to this new folder.
1. Configure your task scheduler to rename the folder as often as you want unpackerr to hit that web hook.

**Comment by hansenc0705** [comment]
I ended up creating a powershell script that checks for the process and will miss the Uptime Kuma PUSH URL check in if it's not found but this doesn't test functionality.

I like your idea and will play around with that. Thanks

**Comment by davidnewhall** [comment]
I use betteruptime.com This is what I do.

**Comment by austinwbest** [comment]
I use Notifiarr which the dev added a process monitor apeci for this reason 😜

**Comment by davidnewhall** [comment]
Hi @hansenc0705 Curious if made this work out?

**Comment by hansenc0705** [comment]
Yes. That build this morning tested good.

**Comment by davidnewhall** [comment]
oooo got it! :)

**Comment by davidnewhall** [comment]
Let me know if we can do anything else!
