### ISSUE TITLE
TrueNAS, Unpackerr in Jail: rarReader.Next: rardecode: invalid file block

### ISSUE THREAD

**Issue by Paradoxum** [davidnewhall/unpackerr#163]
deleted logfile, restarted service, new logfile; https://atomicrhino.net/upload/ZeroBin/?68e7014646d2b7d2#Fx0l1aaKR/t3BefhsW//vMVsA5m6Y+IuYpsGIIsr4Gc=

conf file; https://atomicrhino.net/upload/ZeroBin/?a8a10bfeec15c2fc#YOuSa9pAAz921JKgw7bKLLTgmsINWymduNUADZjYfyQ=

problem seems to be: 2021/12/30 13:36:29.732674 handlers.go:165: Extraction Error: Family.Guy.S20E04.1080p.WEB.H264-CAKES: **rarReader.Next: rardecode: invalid file block**, but can't find anything on it.

Extracts the files fine to a new _unpackerred dir, then on completion deletes both and nothing in the log but that.

**Comment by davidnewhall** [comment]
Discussing on Discord. This seems to be a corrupted file.

**Comment by davidnewhall** [comment]
This happened to 19 out of 20 downloads, and appears to be something specific to the TrueNAS configuration. Trying to find more info.

**Comment by davidnewhall** [comment]
Were you able to get this working? You kinda fell off the Discord.
