### ISSUE TITLE
"Queue is empty" on Radarr, but Unpackerr keeps deleted movies in its queue and extracts them.

### ISSUE THREAD

**Issue by c10l** [davidnewhall/unpackerr#164]
I deleted a bunch of items from Radarr, and it shows queue as empty.

Unpackerr doesn't seem to be aware of the deletion though, and keeps those downloads in its queue.

I'm not sure what other information you require. I believe (although I'm not sure anymore at this point) they have been deleted from Radarr after the download was complete but before anything was extracted.

**Comment by davidnewhall** [comment]
In Radarr, navigate to Activity Queue, then click Options in the top-right, and check the box to show all items.

**Comment by c10l** [comment]
Hah, I wasn't aware of that. Deleting them from there makes it work as expected. Thanks!
