### ISSUE TITLE
Support for multiple subdirs (recursive unpack)

### ISSUE THREAD

**Issue by samip5** [davidnewhall/unpackerr#165]
Some downloads tend to have a wierd folder structure, could this be added as supported? The subs should get extracted next to the media files.

root path -> Season x -> Episode x -> rar files
root path -> Season x -> Episode x -> Subs -> rar files

**Comment by davidnewhall** [comment]
I'm sorry, but I don't understand what problem you're describing.

**Comment by samip5** [comment]
> I'm sorry, but I don't understand what problem you're describing.

Unpackerr doesn't appear to unpack when there's 2+ subdirs aka recursively.

**Comment by davidnewhall** [comment]
I've never had that problem. Can you share the logs with me? It may indicate why files were skipped.

**Comment by samip5** [comment]
They don't even show up in logs, so that's probably why.. :(

**Comment by davidnewhall** [comment]
Were you able to figure this out? I still need more data (log file?) to understand the problem you're describing. If you don't see your items in the log file, then perhaps some paths are not configured correctly. Knowing more about your configuration may help me help you.

**Comment by samip5** [comment]
Unfortunately no log to give, as it was not seeing by Unpackerr at all and thus not extracted.

It was an season pack of 12 seasons.

**Comment by davidnewhall** [comment]
oh, yeah, Sonarr doesn't support packs with more than 1 season, and thus won't properly import them. It gives Unpackerr problems too.
