### ISSUE TITLE
Doesn't detect archives files with part# in file name

### ISSUE THREAD

**Issue by Kazz3r24** [davidnewhall/unpackerr#167]
I've watched the unpackerr logs for the last few minutes with several successful extractions of .rar archives; however I'm noticing that archives which include part#.rar in the file name aren't detected at all. These are similar archives that you'd normally see with nzb's which would have a par2 file or part00.rar I believe, but that doesn't exist with this archive for whatever reason.
The archive extracts fine when highlighting all .rar files in explorer and selecting "Extract Here". 

Unpackerr is currently running on an Ubuntu server, and works perfectly except with a select few torrents which are like this.

Archive as seen in Windows Explorer:

![image](https://user-images.githubusercontent.com/15070472/147951265-c8a9a726-534c-4e13-bfaa-7f304b3b9b17.png)

This log snippet just shows that Sonarr and Unpackerr are communicating correctly and extractions when compliant are happening.

`Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676242 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:93%): Werq.The.World.S02E08.iNTERNAL.1080p.WEB.h264-SECRETOS (Ep: 115613)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676246 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:85%): Werq.The.World.S02E09.1080p.WEB.H264-TXB (Ep: 115614)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676250 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115556)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676254 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115557)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676258 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115558)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676261 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115559)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676265 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115560)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676269 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115561)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676272 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115562)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676276 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115563)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676280 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115564)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676283 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115565)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676287 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115566)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676291 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115567)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676295 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115568)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676301 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115569)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676305 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115570)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676309 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115571)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676313 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115572)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676316 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115573)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676324 handlers.go:46: [Sonarr] Imported: Werq.The.World.S02E03.1080p.WEB.h264-SECRETOS (delete in 5m0s)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676329 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S02E03.1080p.WEB.h264-SECRETOS (Imported, elapsed: 0s)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676334 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S02E07.1080p.WEB.h264-SECRETOS (Extracted, Awaiting Import, elapsed: 1m14s)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676338 handlers.go:59: [DEBUG] Sonarr: Status: Naruto (2002) Complete Series & Movies [DUAL-AUDIO] [720p] [HEVC] [x265] (Waiting, pre-Queue, elapsed: 88h19m0s)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676342 handlers.go:59: [DEBUG] Sonarr: Status: Naruto Shippuuden US DVD Remux (Waiting, pre-Queue, elapsed: 80h7m0s)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676345 handlers.go:40: [DEBUG] Already imported? Werq.The.World.S02E04.1080p.WEB.h264-SECRETOS
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676349 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S02E04.1080p.WEB.h264-SECRETOS (Deleted, elapsed: 2m55s)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676353 handlers.go:42: [DEBUG] Sonarr: Awaiting Delete Delay (2m0s remains): Werq.The.World.S02E06.1080p.WEB.h264-SECRETOS
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676356 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S02E06.1080p.WEB.h264-SECRETOS (Imported, elapsed: 3m0s)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676360 handlers.go:42: [DEBUG] Sonarr: Awaiting Delete Delay (4m0s remains): Werq.The.World.S01E09.1080p.WEB.x264-SECRETOS
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676370 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S01E09.1080p.WEB.x264-SECRETOS (Imported, elapsed: 1m0s)
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676377 logs.go:143: [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [1 extracted] [3 imported] [0 failed] [1 deleted]
Jan  3 10:51:48 orion unpackerr[10261]: 2022/01/03 10:51:48.676381 logs.go:145: [Unpackerr] Totals: [0 retries] [91 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.603120 radarr.go:117: [Radarr] Updated (http://127.0.0.1:7878/): 0 Items Queued
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.610487 sonarr.go:116: [Sonarr] Updated (http://127.0.0.1:8989): 26 Items Queued
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.615109 handlers.go:84: [Sonarr] Completed item still waiting: Naruto (2002) Complete Series & Movies [DUAL-AUDIO] [720p] [HEVC] [x265], no extractable files found at: /mnt/Echo/Downloads/TV/Naruto (2002) Complete Series & Movies [DUAL-AUDIO] [720p] [HEVC] [x265] (stat err: <nil>)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.615127 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): completed (torrent:100%): Naruto (2002) Complete Series & Movies [DUAL-AUDIO] [720p] [HEVC] [x265] (Ep: 0)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619424 handlers.go:84: [Sonarr] Completed item still waiting: Naruto Shippuuden US DVD Remux, no extractable files found at: /mnt/Echo/Downloads/TV/Naruto Shippuuden US DVD Remux (stat err: <nil>)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619438 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): completed (torrent:100%): Naruto Shippuuden US DVD Remux (Ep: 0)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619445 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:74%): Werq.The.World.S02E05.1080p.WEB.h264-SECRETOS (Ep: 115610)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619449 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:62%): Werq.The.World.S02E01.1080p.WEB.h264-SECRETOS (Ep: 115606)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619453 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:13%): Werq.The.World.S02E02.1080p.WEB.h264-SECRETOS (Ep: 115607)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619457 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:96%): Werq.The.World.S02E10.1080p.WEB.H264-TXB (Ep: 115615)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619461 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:94%): Werq.The.World.S02E08.iNTERNAL.1080p.WEB.h264-SECRETOS (Ep: 115613)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619465 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:86%): Werq.The.World.S02E09.1080p.WEB.H264-TXB (Ep: 115614)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619488 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115556)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619495 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115557)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619499 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115558)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619502 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115559)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619506 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115560)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619510 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115561)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619514 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115562)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619518 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115563)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619521 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115564)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619525 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115565)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619529 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115566)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619533 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115567)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619536 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115568)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619540 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115569)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619544 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115570)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619556 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115571)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619560 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115572)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619565 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): downloading (torrent:47%): Below.Deck.Sailing.Yacht.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: 115573)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619571 handlers.go:59: [DEBUG] Sonarr: Status: Naruto (2002) Complete Series & Movies [DUAL-AUDIO] [720p] [HEVC] [x265] (Waiting, pre-Queue, elapsed: 88h20m0s)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619576 handlers.go:59: [DEBUG] Sonarr: Status: Naruto Shippuuden US DVD Remux (Waiting, pre-Queue, elapsed: 80h8m0s)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619579 handlers.go:40: [DEBUG] Already imported? Werq.The.World.S02E04.1080p.WEB.h264-SECRETOS
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619583 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S02E04.1080p.WEB.h264-SECRETOS (Deleted, elapsed: 3m55s)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619587 handlers.go:42: [DEBUG] Sonarr: Awaiting Delete Delay (1m0s remains): Werq.The.World.S02E06.1080p.WEB.h264-SECRETOS
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619591 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S02E06.1080p.WEB.h264-SECRETOS (Imported, elapsed: 4m0s)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619594 handlers.go:42: [DEBUG] Sonarr: Awaiting Delete Delay (3m0s remains): Werq.The.World.S01E09.1080p.WEB.x264-SECRETOS
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619597 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S01E09.1080p.WEB.x264-SECRETOS (Imported, elapsed: 2m0s)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619601 handlers.go:42: [DEBUG] Sonarr: Awaiting Delete Delay (4m0s remains): Werq.The.World.S02E03.1080p.WEB.h264-SECRETOS
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619604 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S02E03.1080p.WEB.h264-SECRETOS (Imported, elapsed: 1m0s)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619609 handlers.go:46: [Sonarr] Imported: Werq.The.World.S02E07.1080p.WEB.h264-SECRETOS (delete in 5m0s)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619612 handlers.go:59: [DEBUG] Sonarr: Status: Werq.The.World.S02E07.1080p.WEB.h264-SECRETOS (Imported, elapsed: 0s)
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619620 logs.go:143: [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [0 extracted] [4 imported] [0 failed] [1 deleted]
Jan  3 10:52:48 orion unpackerr[10261]: 2022/01/03 10:52:48.619624 logs.go:145: [Unpackerr] Totals: [0 retries] [91 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]`

**Comment by davidnewhall** [comment]
Please share the log from Unpackerr where it says it can't find any archives in `/mnt/Echo/Downloads/TV/The.Proof.Is.Out.There.S01E03.1080p.WEB.H264-WHOSNEXT`

**Comment by Kazz3r24** [comment]
Sorry, at first glance I didn't see the file in question at all in the logs. This is what I found with a second look.

Unpackerr could see the directory, it's possible I didn't wait long enough for the extraction to start - sitting watching things makes time crawl. I have a feeling that Unpackerr didn't extract the file because I had already manually done it and Sonarr imported from there. I'll have to wait for another instance like this to see if I was just being impatent.

`Jan  3 10:56:48 orion unpackerr[10261]: 2022/01/03 10:56:48.633974 handlers.go:75: [Sonarr] Waiting for Start Delay: The.Proof.Is.Out.There.S01E03.1080p.WEB.H264-WHOSNEXT (1m0s remains)
Jan  3 10:56:48 orion unpackerr[10261]: 2022/01/03 10:56:48.633978 sonarr.go:151: [DEBUG] Sonarr (http://127.0.0.1:8989): completed (torrent:100%): The.Proof.Is.Out.There.S01E03.1080p.WEB.H264-WHOSNEXT (Ep: 115161)
Jan  3 10:56:48 orion unpackerr[10261]: 2022/01/03 10:56:48.634688 handlers.go:59: [DEBUG] Sonarr: Status: The.Proof.Is.Out.There.S01E03.1080p.WEB.H264-WHOSNEXT (Waiting, pre-Queue, elapsed: 0s)
Jan  3 10:57:48 orion unpackerr[10261]: 2022/01/03 10:57:48.615351 handlers.go:38: [Sonarr] Imported: The.Proof.Is.Out.There.S01E03.1080p.WEB.H264-WHOSNEXT (not extracted, removing from history)
Jan  3 10:57:48 orion unpackerr[10261]: 2022/01/03 10:57:48.615354 handlers.go:59: [DEBUG] Sonarr: Status: The.Proof.Is.Out.There.S01E03.1080p.WEB.H264-WHOSNEXT (Waiting, pre-Queue, elapsed: 1m0s)`

**Comment by davidnewhall** [comment]
Looks like it was about to extract it, but it was imported before the wait time elapsed. fwiw, par01.rar files [are supported](https://github.com/golift/xtractr/blob/master/files.go#L110-L112). It's been a long time since someone reported an incompatible naming scheme (#140).

Please let me know if you run into any problems; happy to help!
