### ISSUE TITLE
Item added to and remains in queue despite not being an archive [stat err: <nil>]

### ISSUE THREAD

**Issue by peterpiglet** [davidnewhall/unpackerr#169]
Hi, thus far unpackerr has been running smoothly, awesome piece of code :-)

I can see in my logs that there is one item queued `[1 waiting]`, which is not an archive and therefore results in an error `[stat err: <nil>]` when unpacking is attempted:

```
2022/01/11 11:17:34 [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [1 extracted] [0 imported] [0 failed] [0 deleted]
2022/01/11 11:17:34 [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
2022/01/11 11:18:34 [Sonarr] Updated (http://***.***.***.**:*****): 2 Items Queued
2022/01/11 11:18:34 [Sonarr] Completed item still waiting: *********** 2021 2160p WEB-DL HDR10 FLAC 5.1 H265-SHD, no extractable files found at: /downloads/complete/*********** 2021 2160p WEB-DL HDR10 FLAC 5.1 H265-SHD (stat err: <nil>)
```

The contents of the folder are three files none of which is an archive:

```
'*********** 2021 2160p WEB-DL HDR10 FLAC 5.1 H265-SHD.PNG'
'NFO SHD MKV HDR.nfo'
'*********** 2021 2160p WEB-DL HDR10 FLAC 5.1 H265-SHD.mkv'
```

This issue will resolve itself when I remove that folder/the files. I am still wondering why this folder or its contents are somehow recognized as an archive to be unpacked?

Cheers

**Comment by bakerboy448** [comment]
Enable show unknown in activity queue options in \*Arr

**Comment by peterpiglet** [comment]
I have enabled the show unknown setting in sonarr and the file `*********** 2021 2160p WEB-DL HDR10 FLAC 5.1 H265-SHD.mkv` is now depicted in the list.

However, unpackerr still lists the corresponding directory containing the `.nfo`, `.png` and `.mkv` file as an archive location and puts out the error `[stat err: <nil>]` when unpacking is attempted. The log files are identical as before:

```
2022/01/11 11:17:34 [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [1 extracted] [0 imported] [0 failed] [0 deleted]
2022/01/11 11:17:34 [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
2022/01/11 11:18:34 [Sonarr] Updated (http://***.***.***.**:*****): 2 Items Queued
2022/01/11 11:18:34 [Sonarr] Completed item still waiting: *********** 2021 2160p WEB-DL HDR10 FLAC 5.1 H265-SHD, no extractable files found at: /downloads/complete/*********** 2021 2160p WEB-DL HDR10 FLAC 5.1 H265-SHD (stat err: <nil>)
```

This happens only for this specific directory. There are many other directories which are not miss recognized as archive locations and on the other hand archive locations are correctly unpacked. My first thought was that this specific directory name `*********** 2021 2160p WEB-DL HDR10 FLAC 5.1 H265-SHD` might cause a hiccup with some RegEx recognition. Although that is a wild guess...

**Comment by austinwbest** [comment]
that isn't an error, nil is null is nothing. It says there isn't anything to extract there so if there is you would need to provide a `ls- ltra` or similar of the folder to see in it

**Comment by peterpiglet** [comment]
Ah, okay I see. Thanks for clearing that up. I think I get the process now.

Thanks for the help.

**Comment by davidnewhall** [comment]
Unpackerr is just telling you something is stuck in your sonar queue. It's not an error, and it's not trying to extract it (because it has no compressed files). The fix is to figure out why it's stuck in the queue.

**Comment by peterpiglet** [comment]
Very well put. That’s what I gathered now. I also know why it’s stuck in the queue, but that is related to my specific docker container setup.

thank you :-)
