### ISSUE TITLE
Support for password, but not in the filename

### ISSUE THREAD

**Issue by phampyk** [davidnewhall/unpackerr#172]
Hello!! I'm so excited to find this as I've been looking for something like this for a while now. I've been checking if it supports password protected files, but I could only find it is when is in the name of the file.
Could it be possible to have another way to support passwords? I was thinking maybe a file in the same folder like "password.txt" that unpackerr could use as a "list" of passwords to try.

I get a lot of rar & zip files from the same source that all have the same password, but it's not on the name of the file itself, like the other case.

Thank you so much.

**Comment by davidnewhall** [comment]
Not an unreasonable idea. Would storing the list of passwords in the config file seem sufficient, or would a separate password file work better?

**Comment by phampyk** [comment]
Sorry for the very late reply,
Yes, on the config file is okay, I can just add them there without any problem.
Thank you so much

**Comment by davidnewhall** [comment]
I started working on this, and will eventually get it in. Just giving you an update.
