### ISSUE TITLE
Disable automatic _unpackerred suffix?

### ISSUE THREAD

**Issue by daomengRen** [davidnewhall/unpackerr#173]
when I am in the watch folder, I set the extraction path. After the extraction is successful, the "_unpackerred" field will be added after the file name. Currently, in addition to deleting the source file or Move extracted items back into the original folder, can I configure the variable, to un-add this field to the filename

**Comment by davidnewhall** [comment]
If I'm understanding your question correctly, setting move_back to true should do what you want. `_unpackerred` is only added to the folder name, so if you move your files back to the original folder they'll have the correct location.

Please provides more details about what outcome you would like and I can help you configure it get there.

**Comment by daomengRen** [comment]
I know this will solve the problem, but I want the extracted and source files to be in a different directory

**Comment by davidnewhall** [comment]
There is not currently any way to prevent the suffix. The only option at the moment is to create a small script that moves your files to another location. You can execute this after the extraction finishes using the _command hook_ feature built into Unpackerr.

**Comment by daomengRen** [comment]
okay, thank you

**Comment by daomengRen** [comment]
In the docker environment, is it added like this：
>       - UN_CMDHOOK_0_SHELL=true
>       - UN_CMDHOOK_0_COMMAND=./example.sh

Is this the case, because in the example, I don't see an example

**Comment by davidnewhall** [comment]
Yeah, that should work. You probably don't need `UN_CMDHOOK_0_SHELL=true` when running a script, but it should work still.

**Comment by alexbleicker** [comment]
I'm wondering what is the best way to handle renaming folders automatically, I'm open to any suggestions :)

**Comment by davidnewhall** [comment]
@alexbleicker You need this for the `[[folder]]` feature, right?

**Comment by davidnewhall** [comment]
If y'all want to try the docker tag `golift/unpackerr:unstable` it no longer keeps the suffix. Let me know how it works out.
