### ISSUE TITLE
How to use --user instead of $PUID

### ISSUE THREAD

**Issue by eihns** [davidnewhall/unpackerr#175]
Im using it on unraid in folder watch mode. ( https://github.com/davidnewhall/unpackerr/issues/50 )

Since it didnt work, i bought a unrar script but it seems like this also is not the yellow of the egg haha

Anyway im back, seems to work better, but WHY does he change the permissions? Windows tells me i need root to remove files or directorys...? a quick search around for permissions didnt bring anything useful up

```
drwxrwxrwx 1 nobody users 1044 Feb  8 02:47 054.movie.German.1944.DL.DVDRiP.XViD-HVC/
drwxr-xr-x 1 root   root    12 Feb  8 02:39 054.movie.German.1944.DL.DVDRiP.XViD-HVC_unpackerred/
```

even after i use "move back"

```
root@Unraid-Server:~# ls -l /mnt/user/downloads/completed/Serien/extra-3.2015-09-09.German.720p.HDTV.x264
total 1378640
-rw-r--r-- 1 root   root  705834675 Feb  8 02:53 atax-extra-3-2015-09-16-720p.mkv
```

`2022-02-08 03:28:11.4|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /user/downloads/completed/Serien/some-ATAX-xpost. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder
`

why?

**Comment by davidnewhall** [comment]
Try adding `--user=999` to the docker run command. See screenshot for how to do that in unRaid. Replace 999 with whatever user you want to own those files.
![Screen Shot 2022-02-07 at 10 33 31 PM](https://user-images.githubusercontent.com/2402929/152931453-5f964f97-c7b9-47c1-99a2-881bba4c2c1c.png)

**Comment by eihns** [comment]
thanks for your edit, it didnt helped me, because i googled around for hours to find it myself, just came back to report its working now... :-)

thanks
