### ISSUE TITLE
keep getting tthis error and not sure what to do 

### ISSUE THREAD

**Issue by fiqabumm** [davidnewhall/unpackerr#177]
[ERROR] Sonarr (http://192.168.1.23:8989/): api.Get(queue): httpClient.Do(req): Get "http://192.168.1.23:8989/api/v3/queue?includeUnknownSeriesItems=true&page=1&pageSize=2000&sortDir=asc&sortKey=timeleft": EOF

**Comment by davidnewhall** [comment]
Still a problem? Make sure you're on Sonarr v3.
