### ISSUE TITLE
Can't seem to setup all of my Sonarr instanses.

### ISSUE THREAD

**Issue by bassterror** [davidnewhall/unpackerr#178]
Hello, I'm absolutely loving this app, but I can't seem to config it correct. 
This is my config:

```
################
### Episodes ###
################
[[sonarr]]
  url = "http://172.17.0.8:8989"
  api_key = "1785f3225e124663a16022036c2bfd95"

[[sonarr]]
  url = "http://172.17.0.11:8989"
  api_key = "462b3f42814f43c09da4abebbb08633f"

[[sonarr]]
  url = "http://172.17.0.5:8989"
  api_key = "7028029b081a49329862934a93fe8699"

################
#### Movies ####
################
[[radarr]]
  url = "http://172.17.0.12:7878"
  api_key = "e261506b34df43a0acb3e057da29fe49"

[[radarr]]
  url = "http://172.17.0.13:7878"
  api_key = "2ba3b8bacae7420aa4f67129b1344d16"

################
#### Albums ####
################
[[lidarr]]
  url = "http://172.17.0.15:8686"
  api_key = "ac8d93af32784cb1bdee651a1bf58c1a"
```
In the log, you can see that at the start it says that "API Key may be incorrect". After that, my 2 Radarr instances, 1 Sonarr instance, and the Lidarr instance seem to be working, because Unpackerr "reads" their queues. It also says that my second Sonarr throws 401 and the third Sonarr is missing (no log for it). I just can't understand why some of them are working and some of them are not. I checked the API keys, IPs, and ports (these are internal Docker IPs) several times and I can't seem to figure this out. Thank you in advance!

[unpackerr.log](https://github.com/davidnewhall/unpackerr/files/8120954/unpackerr.log)
[unpackerr.conf](https://github.com/davidnewhall/unpackerr/files/8120957/unpackerr.conf.txt)

**Comment by bassterror** [comment]
I'm sorry, I don't understand any of the above. What baseurl, paths, and double space?

**Comment by davidnewhall** [comment]
What URL is in your browser bar? Put that into your unpackerr config.

**Comment by bassterror** [comment]
The first time I used those IPs but something went south and I thought that I should use the internal docker ones. I guess it was some other mistake that I made back then. Anyway, Unpacker is working now. Thank you!
As for the hard links, mentioned above, my setup is exactly like that. Where do you guys see that I'm using something else?

**Comment by davidnewhall** [comment]
> (still receiving "API Key may be incorrect" at the start of the application though

This may indicate you're missing a url base on your application urls. ie: this `url = "http://172.17.0.5:8989"` should maybe be `url = "http://172.17.0.5:8989/sonarr"` etc. 

Log into Sonarr, go to General Settings and see if a URL Base is configured.

**Comment by anat0lius** [comment]
I'm also getting this error, but only when I deploy the container. 

```
2022/03/21 21:41:57 [ERROR] Checking Sonarr Path: redirected to login page while checking URL http://192.168.1.11:8989/sonarr/: API Key may be incorrect
2022/03/21 21:41:57 [ERROR] Checking Radarr Path: redirected to login page while checking URL http://192.168.1.11:7878/radarr/: API Key may be incorrect
```

After that it seems ok:

```
2022/03/21 21:41:57 ==> GoLift Discord: https://golift.io/discord <==
2022/03/21 21:41:57 ==> Startup Settings <==
2022/03/21 21:41:57  => Sonarr Config: 1 server: http://192.168.1.11:8989/sonarr/, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/downloads"]
2022/03/21 21:41:57  => Radarr Config: 1 server: http://192.168.1.11:7878/radarr/, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: true, delete_delay: 5m0s, paths:["/downloads"]
...
2022/03/21 21:41:57 [Radarr] Updated (http://192.168.1.11:7878/radarr/): 0 Items Queued
2022/03/21 21:41:57 [Sonarr] Updated (http://192.168.1.11:8989/sonarr/): 0 Items Queued
```

I do have base url configured and login enabled.

**Comment by davidnewhall** [comment]
@anat0lius It's ignorable in your case. I wrote that code while testing on starr apps with auth disabled. It could use some tweaks to produce fewer false positives.
