### ISSUE TITLE
[ERROR] Folder (cannot watch): no space left on device

### ISSUE THREAD

**Issue by robflate** [davidnewhall/unpackerr#180]
I'm attempting to set `UN_FOLDER_0_PATH` to my Prowlarr download folder. This is where I send downloads from manual searches in Prowlarr. Basically, downloads that don't originate from an *arr app. I get the error;

`[ERROR] Folder (cannot watch): no space left on device` The locally mapped folder has plenty of space. I just tested it by downloading a .rar (Prowlarr search > qBittorrent)  and it just sits in the folder but Unpackerr doesn't unrar it.

Although Unpackerr seems to be working otherwise, I can't actually confirm it until one of my *arr apps downloads something with a rar file which is rare but I do occasionally get .rar files from Lidarr, which is why I installed Unpackerr.

For context, here's my log file;

```
2022/03/06 23:02:00 Unpackerr v0.9.9 Starting! (PID: 1) 2022-03-06 23:02:00.068556271 +0000 GMT m=+0.000884944
2022/03/06 23:02:00 ==> GoLift Discord: https://golift.io/discord <==
2022/03/06 23:02:00 ==> Startup Settings <==
2022/03/06 23:02:00  => Sonarr Config: 1 server: http://192.168.90.248:8989, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/data/torrent/complete"]
2022/03/06 23:02:00  => Radarr Config: 1 server: http://192.168.90.250:7878, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/data/torrent/complete"]
2022/03/06 23:02:00  => Lidarr Config: 1 server: http://192.168.90.249:8686, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/data/torrent/complete"]
2022/03/06 23:02:00  => Readarr Config: 1 server: http://192.168.90.247:8787, apikey:true, timeout:10s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["/data/torrent/complete"]
2022/03/06 23:02:00  => Folder Config: 1 path: /data/torrent/prowlarr, extract to: /data/torrent/prowlarr (delete after:0s, delete orig:false, log file: true, move back:false, event buffer:20000)
2022/03/06 23:02:00  => Using env variables only. Config file not found.
2022/03/06 23:02:00  => Parallel: 1
2022/03/06 23:02:00  => Interval: 15s
2022/03/06 23:02:00  => Start Delay: 1m0s
2022/03/06 23:02:00  => Retry Delay: 5m0s, max: 3
2022/03/06 23:02:00  => Debug / Quiet: false / false
2022/03/06 23:02:00  => Directory & File Modes: 755 & 644
2022/03/06 23:02:00  => Log File: /unpackerr/unpackerr.log (10 @ 10Mb)
2022/03/06 23:02:00  => Webhook Configs: 0 URLs
2022/03/06 23:02:00  => Command Hook Configs: 0 cmds
2022/03/06 23:02:00 [ERROR] Folder (cannot watch): no space left on device
2022/03/06 23:02:00 [Folder] Watching (fsnotify): /data/torrent/prowlarr
2022/03/06 23:02:00 [Folder] Polling @ 1s: /data/torrent/prowlarr
2022/03/06 23:02:00 [Lidarr] Updated (http://192.168.90.249:8686): 2 Items Queued, 2 Retrieved
2022/03/06 23:02:00 [Radarr] Updated (http://192.168.90.250:7878): 0 Items Queued
2022/03/06 23:02:00 [Readarr] Updated (http://192.168.90.247:8787): 0 Items Queued, 0 Retrieved
2022/03/06 23:02:00 [Sonarr] Updated (http://192.168.90.248:8989): 2 Items Queued
```

and here's my docker-compose.yml;

```
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DATA:/data
      - $CONFIG/unpackerr/unpackerr.log:/unpackerr/unpackerr.log
    environment:
      - TZ=$TZ
      # General config
      - UN_LOG_FILE=/unpackerr/unpackerr.log
      # Sonarr Config
      - UN_SONARR_0_URL=http://192.168.90.248:8989
      - UN_SONARR_0_API_KEY=$SONARR_API_KEY
      - UN_SONARR_0_PATHS_0=/data/torrent/complete
      # Radarr Config
      - UN_RADARR_0_URL=http://192.168.90.250:7878
      - UN_RADARR_0_API_KEY=$RADARR_API_KEY
      - UN_RADARR_0_PATHS_0=/data/torrent/complete
      # Lidarr Config
      - UN_LIDARR_0_URL=http://192.168.90.249:8686
      - UN_LIDARR_0_API_KEY=$LIDARR_API_KEY
      - UN_LIDARR_0_PATHS_0=/data/torrent/complete
      # Readarr Config
      - UN_READARR_0_URL=http://192.168.90.247:8787
      - UN_READARR_0_API_KEY=$READARR_API_KEY
      - UN_READARR_0_PATHS_0=/data/torrent/complete
      # Folder Config
      - UN_FOLDER_0_PATH=/data/torrent/prowlarr
      - UN_FOLDER_0_EXTRACT_PATH=/data/torrent/prowlarr
    user: $PUID:$PGID
```

**Comment by davidnewhall** [comment]
This feature works pretty well on native installations with local file systems. What file system is your container on? Is it local, or NFS/CIFS? Does unpackerr have permissions to write to `/data/torrent/prowlarr` ?

If you add a _folder_ into `/data/torrent/prowlarr` does unpackerr write something in the log about it?

**Comment by robflate** [comment]
- The container is on the local filesystem.
- Both qBittorrent and Unpackerr run as the same user with write permissions on `/data/torrent/prowlarr`.
- Adding a folder to `/data/torrent/prowlarr` shows the following log;

`today at 21:12:262022/03/08 21:12:26 [Folder] Tracking New Item: /data/torrent/prowlarr/test`

**Comment by davidnewhall** [comment]
oh, so maybe it's working? Put a folder with a compressed file in it into your watched folder.

**Comment by robflate** [comment]
Aha! It **is** working...it even extracts other rar files inside the main rar...nice!

So how do I get extracterr to see a compressed file in the **root** of `/data/torrent/prowlarr`? That doesn't work.

**Comment by davidnewhall** [comment]
You don't. :) That doesn't work.

**Comment by davidnewhall** [comment]
It was made for downloaded folders. Almost every download you get is going to be in a folder.

**Comment by robflate** [comment]
Understood. Unfortunately the first random torrent I tried that contained a compressed file was not in a folder!

Thanks for your time and thanks for the great app. Appreciate it.

**Comment by davidnewhall** [comment]
It happens from time to time. When those come up, you can just make a folder and hard link the file into it.

**Comment by ilanKushnir** [comment]
Hi, I'm having the same issue
but in my case prowlarr downloaded it in a folder (`/downloads/prowlarr/the-compressed-file`)
so why with this config it doesn't extract it?

https://github.com/ilanKushnir/kws-cluster/blob/main/cluster/apps/media/unpackerr/helm-release.yaml#L34-L37

**Comment by davidnewhall** [comment]
@ilanKushnir This issue is resolved. If you need assistance please jump on Discord or open a new issue.
