### ISSUE TITLE
Quick dumb question

### ISSUE THREAD

**Issue by YouveGotMeowxy** [davidnewhall/unpackerr#181]
Which is the correct way to add multiple paths for unpackerr to monitor, in the config file?

Like this?:

    paths = ["/Media/.downloads/.torrents/music","/Media/.downloads/.usenet/music"]

or like this?:

    paths = ["/Media/.downloads/.torrents/music,/Media/.downloads/.usenet/music"]

(note the quotes  and comma separating the 2 paths).

I tried both, but the startup log seems to give no hint whether one is right or wrong.

**Comment by austinwbest** [comment]
Quote each path, separated by commas
