### ISSUE TITLE
What happens when there's an overlap in watched folders that involves Sonarr/Radarr?

### ISSUE THREAD

**Issue by ChristianMalazarte** [davidnewhall/unpackerr#183]
Will I experience any problems if I have Unpackerr enabled for Sonarr/Radarr and then also enable the Folder Watcher to monitor the main Downloads folder?

- Downloads
--- FTP Source 1
--- FTP Source 2
--- Sonarr/Radarr folder 1
--- Sonarr/Radarr folder 2
--- Misc
--- Etc

**Comment by davidnewhall** [comment]
The folder feature only watches 1 level deep, so if your above folder structure is correct, it shouldn't hurt anything. Normally, you don't want to make the folder feature watch the same folder you use for an app; it will cause double extractions.

**Comment by ChristianMalazarte** [comment]
Okay thanks that's good to know.
