### ISSUE TITLE
resumes unpacking same folder over and over

### ISSUE THREAD

**Issue by Arvid78** [davidnewhall/unpackerr#184]
As stated.
Unpackerr never stop unpacking every folder in my folder.
Does not remove unpacked files, guess thats a setting i missed out.

So outcome is that when everything is unpacked  unpackerr restarts from top and start unpack and when thats done states that it cant overwrite the file (since its already there)

ok not the best of information from me but has someone had the same as me?

Running unpackerr on Unraid server

**Comment by davidnewhall** [comment]
Why isn't the file being imported by Sonarr or Radarr? What's the error message?

**Comment by davidnewhall** [comment]
Please provide the logs.

**Comment by Arvid78** [comment]
Wow dang ur fast.
The files är imported by sonarr and radarr.

Its only the unpack feature that repeats

**Comment by Arvid78** [comment]
On my phone right now and have troubles adding log with it. 
I will try later again when im at my computer

**Comment by davidnewhall** [comment]
If the file is imported (and no longer in the activity queue), Unpackerr shouldn't extract it again. If it comes back into the activity queue after being extracted, it will extract it again. This sounds like the Starr app doing something strange. Is it only 1 download, or are they all doing this?

**Comment by Arvid78** [comment]
Just remembered that i did a restart of unpacker due to a backup.

So unpackerr dont loop 24/7 unpacking 
but at every app restart unpackerr starts all over unpacking everything and gives the error that the file cant be overwtitten (the unpacked files never deletes after being copied to sonarr/radarr directories).

**Comment by davidnewhall** [comment]
Please read this in its entirety. It applies to you. https://github.com/davidnewhall/unpackerr/wiki/FAQ

**Comment by Arvid78** [comment]
Ill look Into that tomorrow when i have more time on my hands.

I just saw that a had alot of files in the activity que. Never had that before.
Might showed up with the update i installed right before i did the backup.

Ill report back  with results

**Comment by Arvid78** [comment]
Ok so My issue is.

All downloads goes into the download folder, so radarr shows sonarrs series as unknown and sonarr shows radarrs movies as unknown.

I cant figure out how to fix it

**Comment by bakerboy448** [comment]
Use categories as the FAQ discusses

The help text in both apps is fairly clear about that as well.

> Adding a category specific to Radarr avoids conflicts with unrelated non-Radarr downloads. Using a category is optional, but strongly recommended.

> Adding a category specific to Sonarr avoids conflicts with unrelated non-Sonarr downloads. Using a category is optional, but strongly recommended

**Comment by Arvid78** [comment]
Wow finally every unpacked file is deleted and unpackerr dont unpack at every restart.
Unpackerr log looks much better then what im used to.

I actually had to search the web for categories, i didnt know it was in the download client settings inside sonarr and radarr.

But now all fix and works like a charm.

Big thanks for the help
