### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ecatapano** [davidnewhall/unpackerr#185]
Hello all, I am now to unpackerr and from what I can see it can be a handy tool. However, I am having a hard time setting it and getting it to work. I have my server set up on a mac mini and I downloaded and installed the .dmg file and was able to get to the config files and logs. It seems I am missing something but cannot figure it out. Any help would be greatly appreciated! 

<img width="1793" alt="Screen Shot 2022-03-24 at 9 10 42 AM" src="https://user-images.githubusercontent.com/99295796/159924661-5ba0af4c-e5ef-40ae-b0da-e779a005f5d6.png">

<img width="880" alt="Screen Shot 2022-03-24 at 9 09 50 AM" src="https://user-images.githubusercontent.com/99295796/159924659-2ed3191e-56aa-4be8-8bc6-1620dafa6ecf.png">

**Comment by bakerboy448** [comment]
Read the config file closer

> ##-Notes-#######################################################################
## The following sections can be repeated if you have more than one Sonarr,   ##
## Radarr or Lidarr, Readarr, Folder or Webhook.                              ##
## You must uncomment the [[header]] and api_key at a minimum for Starr apps. ##
################################################################################

**Comment by ecatapano** [comment]
Thank you! Sorry for overlooking that... I am not much of a coder either but the server is now found!
