### ISSUE TITLE
Not detecting files on Windows local folder

### ISSUE THREAD

**Issue by alexbleicker** [davidnewhall/unpackerr#188]
I've edited the config file and used the full path as "Y:\\Compressed Downloads" using 2 back slashes as instructed on the manual, still it does not detect any .rar files put in there at the room or inside subfolders. I check the status log, and nothing comes up. Am I missing something?

**Comment by davidnewhall** [comment]
Did ya figure this out?

**Comment by alexbleicker** [comment]
I found out it was my mistake not uncommenting the [[folder]]
