### ISSUE TITLE
Tracking new item keeps unpacking folder that have been already unpacked and moved

### ISSUE THREAD

**Issue by alexbleicker** [davidnewhall/unpackerr#190]
I noticed if I browse a sub folder inside the folder that is being tracked, is triggers a Tracking new item, I'm not sure if this is because I moved the unpacked folder somewhere else and it "thinks" it needs to unpack it again.

I noticed this happening on its own as well, without needing me to browse any folder

**Comment by davidnewhall** [comment]
I'll need to see logs to follow your paraphrasing.

**Comment by davidnewhall** [comment]
You can upload them to https://logs.notifiarr.com and DM me the link on Discord if you'd like.

**Comment by davidnewhall** [comment]
Please re-open if you have logs of the issue you're describing. Would love to help you out!
