### ISSUE TITLE
No such files when there indeed is no extractable files.

### ISSUE THREAD

**Issue by lolfloppydisc** [davidnewhall/unpackerr#198]
Have an issue where unpackerr "holds" the files because it cant find any extractable files and dont skip this.

**Comment by davidnewhall** [comment]
It sounds like you have unknown items in your starr apps. Click the wiki link at the top of this page then click FAQ and read the entire thing. It applies to you.

**Comment by lolfloppydisc** [comment]
I checked the settings in lidarr/sonarr/radarr and all of them had Unknown items enabled.
For example, in my sonarr if I download an episode without rar files unpacker tries to look for archives but cant find any and thus holding the file and preventing import.

I hope there is something else I'm doing wrong =)

**Comment by davidnewhall** [comment]
Unpackerr doesn't hold anything and doesn't prevent any import. Please show me the logs that make you believe this behavior is occurring. What is the error in sonarr for the thing that is not importing?

**Comment by lolfloppydisc** [comment]
Thank you for the fast feedback.

This is what sonarr says:
2022/04/27 11:12:50.978432 handlers.go:84: [Sonarr] Completed item still waiting: Moon.Knight.S01E05.720p.HEVC.x265-MeGusta, no extractable files found at: /downloads/tv-shows/Moon.Knight.S01E05.720p.HEVC.x265-MeGusta (stat err: <nil>)
2022/04/27 11:12:50.978486 sonarr.go:151: [DEBUG] Sonarr (http://192.168.10.104:8989): completed (torrent:100%): Moon.Knight.S01E05.720p.HEVC.x265-MeGusta (Ep: 1163)

**Comment by davidnewhall** [comment]
Those are just informational messages. It's telling you something is stuck in queue. Next step is to go to sonarr and see why.
