### ISSUE TITLE
Add filename-embedded password support to Folder feature.

### ISSUE THREAD

**Issue by furchtlos76** [davidnewhall/unpackerr#199]
I installed your great tool via docker on a synology. Just want to use it with downloadstation. Added the variables
UN_FOLDER_0_PATH
UN_FOLDER_0_EXTRACT_PATH
UN_DEBUG

And as i understood in the issues it should extract rars in folders what have the password in {{password}} form. But even if i move a .zip file it shows the same. Unreadable. Is there any other thing i  have to configure in variables? i even runed the docker in root mode,  ut still the same. changeing permissions of the folders in filestation on the synology did not help. And i cant find a way to open a shell of this docker to  check permissions and so on on the CLI. /bin/bash or /bin/sh both not found. Is there any other trick?

This is what the logs throw out:

2022/04/29 19:14:40.978331 folder.go:69:  => Folder Config: 1 path: /temp/, extract to: /finished/ (delete after:0s, delete orig:false, log file: true, move back:false, event buffer:20000)
2022/04/29 19:16:09.301241 folder.go:335: [DEBUG] Folder: Ignored File Event: /temp/foldername{{password}} (unreadable)

**Comment by furchtlos76** [comment]
I could get THIS problem fixed, it was the problem i mounted the folders with tailing / /temp/ and /finished/ when only doing /temp and /finished that works. Thanks alot

**Comment by davidnewhall** [comment]
You're good now?

**Comment by furchtlos76** [comment]
@davidnewhall yes at least this problem is fixed, took me hours, to find out it makes the problems because of that stupiud tailing slash :-) BUT i just added another bug/or problem now

**Comment by furchtlos76** [comment]
@davidnewhall sorry for doing that bug report wrong. In Issue #101 another user had the same problem. Files or better folders of those rar files, have the password to unrar the encrypted files in the directory name. this is quite common, at least on usenet. The directory names are like in #101 described like this:

Name{{Password}}

like for example

Really.cool.Release{{vXnIxmun2H391JPjkz3N}}

But unfortuatly i get the following error on all directorys i tryed yet to automaticaly unpack with unpackerr. Using official docker. Any idea what is missing? Usiing folder mode only. The log says incorrect password, But when i copy/paste what is inside {{   }} like in the example vXnIxmun2H391JPjkz3N it IS the correct password and unpacks with total commander for example.

2022/04/29 20:45:54.209236 folder.go:260: [Folder] Extraction Error: /temp/Really.cool.Release{{vXnIxmun2H391JPjkz3N}}: rarReader.Next: rardecode: incorrect password | stdout

**Comment by davidnewhall** [comment]
Files without passwords extract OK?

**Comment by furchtlos76** [comment]
Yes. Others are fine. 

022-04-29T21:09:14.120440270Z | stdout | 2022/04/29 21:09:14.118602 queue.go:202: [DEBUG] Extracting File: /temp/Testrelease/Downloads.zip to /fertig/Testrelease_unpackerred
-- | -- | --
2022-04-29T21:09:14.119848838Z | stdout | 2022/04/29 21:09:14.117979 folder.go:242: [Folder] Queued: /temp/Testrelease, queue size: 0

**Comment by davidnewhall** [comment]
I don't actually think the password-in-a-filename feature works for Folders. It only works for Starr apps. Will have to add this.

**Comment by furchtlos76** [comment]
But maybe i just did missunderstand the thread in issue #101 as i read it, you added the support to unpack those files that have the password inside the foldername (not filename) by extracting the password out of the {{}} part at the end of the dirname.

**Comment by davidnewhall** [comment]
I did. For Starr apps, not for watched folders. The code runs here https://github.com/davidnewhall/unpackerr/blob/ade1bb33b3f36d0616a385371233d8f20d3e069b/pkg/unpackerr/handlers.go#L93 and that only fires when a starr app finishes a download. I need to add it here: https://github.com/davidnewhall/unpackerr/blob/ade1bb33b3f36d0616a385371233d8f20d3e069b/pkg/unpackerr/folder.go#L222-L223

**Comment by furchtlos76** [comment]
It looks like this

Directory: Cool.Release{{v656nIxmuN2H391JPjkz3N}}
Files inside this directory: 
kekfhutuhjn37528785276235n.part01
kekfhutuhjn37528785276235n.part02
kekfhutuhjn37528785276235n.part03
kekfhutuhjn37528785276235n.part04

To extract those i copy and paste the party {{v656nIxmuN2H391JPjkz3N}} without the {{ and }} and can unpack it.

**Comment by furchtlos76** [comment]
> 

ahh ok, than i missunderstood this. I was just searching for some tool that does alot of work when using synology dowloadstation to download. as the inbuild unpacker does not work very good and not with password  (well you have to add a password list). Please add this to the wishlist, dont know how hard it is to add this to the docker.

**Comment by davidnewhall** [comment]
It's a +1 line change. Should be able to have something for you to try in a day or two.

**Comment by furchtlos76** [comment]
> It's a +1 line change. Should be able to have something for you to try in a day or two.

Wow! Please send me some link to send you a tipp like paypal or so, as this would be wonderfull! Thanks alot!

**Comment by davidnewhall** [comment]
No worries. I don't accept money for my work. Give it to your favorite charity.

**Comment by davidnewhall** [comment]
@furchtlos76 Try this docker tag `golift/unpackerr:unstable`
Let me know if that is able to extract your password protected archives. Thanks!

**Comment by furchtlos76** [comment]
Thanks soooooo much! Works perfect! Gerat support!!!!
