### ISSUE TITLE
Multi backend config template/structure

### ISSUE THREAD

**Issue by Anon0511** [davidnewhall/unpackerr#201]
Hey,

thanks for your work and this great application.

Could we maybe get an example for multiple backends added to the example config? https://github.com/davidnewhall/unpackerr/blob/master/examples/unpackerr.conf.example

I'm wondering if I just have to use a block twice or if I also need to switch the config flags like `url` to the numbered variables like `UN_READARR_0_URL` in the config file.

Thanks

Cheers

**Comment by davidnewhall** [comment]
Just repeat the block. See line 48.

https://github.com/davidnewhall/unpackerr/blob/master/examples/unpackerr.conf.example#L48

**Comment by Anon0511** [comment]
Oh I missed this then. Sry
