### ISSUE TITLE
Request: -d, --daemon command line option on Windows that doesn't try to create systray icon

### ISSUE THREAD

**Issue by IamGimli** [davidnewhall/unpackerr#204]
So this request would make it easier to deamonize unpackerr on Windows.

For context, I was able to make unpackerr run as a service on Windows using nssm (https://nssm.cc/). Unpackerr loads correctly but then it crashes with the following error:

```
2022/05/12 07:32:10 [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x60 pc=0xf973f6]

goroutine 24 [running]:
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).updateTray(0xc0002eb810, 0xb6b265?, 0x1eac27a0c40?, 0x58?, 0x1ea9d4e0598?, 0x60?, 0xc000048c00?, 0xc000087f20?, 0x0?, 0x0, ...)
	/home/travis/gopath/src/github.com/davidnewhall/unpackerr/pkg/unpackerr/tray.go:206 +0xb6
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).logCurrentQueue(0xc0002eb810)
	/home/travis/gopath/src/github.com/davidnewhall/unpackerr/pkg/unpackerr/logs.go:149 +0x7f4
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).Run(0xc0002eb810)
	/home/travis/gopath/src/github.com/davidnewhall/unpackerr/pkg/unpackerr/start.go:230 +0x257
created by github.com/davidnewhall/unpackerr/pkg/unpackerr.Start
	/home/travis/gopath/src/github.com/davidnewhall/unpackerr/pkg/unpackerr/start.go:153 +0x396
```

I believe this happens when unpackerr tries to load the systray icon, which isn't available to services as they run without a user context available. Unpackerr started manually as a logged-on user on the same system works flawlessly.

**Comment by davidnewhall** [comment]
Can you try passing/setting the environment variable `USEGUI` (maybe `%USEGUI%` on Windows) to `false` ?

`USEGUI=false`

**Comment by IamGimli** [comment]
Yes, that actually worked! I set it as a system variable under "Advanced System Settings"/"Environment Variables", started the unpackerr-service I created using nssm and it now works perfectly without having a user logged-on.

If you'd like, I could write up instructions to make unpackerr a service under Windows for your documentation.

**Comment by IamGimli** [comment]
Done! Thank you for your help and for unpackerr!
