### ISSUE TITLE
Folder watcher does not work on case sensitive filesystems

### ISSUE THREAD

**Issue by lps-rocks** [davidnewhall/unpackerr#217]
The folder watcher flags a folder as 'unreadable' when used on a case-sensitive filesystems. This is likely due to case normalization somewhere in the process.

Reproducable by:

- using a case-sensitive ZFS dataset (or other case-sensitive filesystem)
- specify an all lower-case watch path
- create unpackable directory with upper/lower case mixed property and watch unpackerr ignore the directory because it's 'unreadable'.

**Comment by davidnewhall** [comment]
First thought: Almost everyone uses a case sensitive file system. Except Mac users...

**Comment by lps-rocks** [comment]
I tested this by switching from case-sensitive to case-insensitive ZFS dataset. Once switching to case-insensitive, it began working. Let me see if i can find a better / more robust way to test this.

**Comment by davidnewhall** [comment]
Try ext4?

**Comment by davidnewhall** [comment]
I'm not able to reproduce this. Please re-open if you can.
