### ISSUE TITLE
Installing on Truenas Core

### ISSUE THREAD

**Issue by Dime274** [davidnewhall/unpackerr#218]
Sorry to post this as an issue but I am not sure where else to ask. I am trying to install unpackerr in Truenas Core but can't figure it out. I have installed plex,transmission, jackett, radarr, and sonarr succesfully but those are featured in the "community" plugins on Truenas. I read through the unpackerr github page but the instructions for free BSD are not detailed enough and I cant get it to install. Can you point me in the right direction?

**Comment by davidnewhall** [comment]
Jump on Discord and let's chat about it. Going to be a lot easier than this forum if we can collaborate in real time.
