### ISSUE TITLE
Whisparr Support?

### ISSUE THREAD

**Issue by hongkongkiwi** [davidnewhall/unpackerr#226]
Is it possible to support Whisparr? It should be straightfoward as it has a similar API to sonarr/radarr/readarr

**Comment by hongkongkiwi** [comment]
Just saw your answer to Mylar support. Looks like this might be a no go since there is no Go api for it (yet).

**Comment by davidnewhall** [comment]
It supports Whisparr if you add it as a Radarr instance. One day I'll add Whisparr to the official starr API, just not in hurry since the app isn't completely ready yet.

**Comment by davidnewhall** [comment]
@hongkongkiwi Can you test a build with whisparr support?
