### ISSUE TITLE
Add support for Lidarr

### ISSUE THREAD

**Issue by MammothJerk** [davidnewhall/unpackerr#23]
https://github.com/lidarr/Lidarr/

I'm not sure how involved it would be to add support for lidarr since it's very similar to both radarr and sonarr.

**Comment by davidnewhall** [comment]
Probably really easy, I just never got around to it because my music tracker went away. :P

**Comment by davidnewhall** [comment]
Can you [send me](mailto:david@sleepers.pro) the output of your lidarr queue api with at least 1 item in queue? Looking at the [docs](https://github.com/lidarr/Lidarr/wiki/API), this should do it:
```
curl -H "Accept: application/json" http://localhost:8686/api/v1/queue?apikey=${YOUR_API_KEY}
```

I just need the json structure really to make sure it matches what [they provide ](https://github.com/lidarr/Lidarr/wiki/Queue#returns-jsonarray)and it hasn't changed.

**Comment by davidnewhall** [comment]
This might be working. I don't think I have a way to download anything to actually test though. 
```
2020/02/13 09:42:16 Unpackerr v0.6.1-127 Starting! (PID: 1)
2020/02/13 09:42:16 Radarr Updated (http://radarr:7878/radarr): 0 Items Queued
2020/02/13 09:42:16 Sonarr Updated (http://sonarr:8989/sonarr): 1 Items Queued
2020/02/13 09:42:16 Lidarr Updated (http://lidarr:8686/lidarr): 0 Items Queued
```

**Comment by davidnewhall** [comment]
I could still use that API output, I'm told it contains the download path which would allow me to remove the setting from the config. Please share. :D

**Comment by MammothJerk** [comment]
Was just about to send you the API output, is it still needed?

**Comment by davidnewhall** [comment]
yes, thank you! It has the output path! That means I can make that setting optional in the config. Thanks!!!!

**Comment by davidnewhall** [comment]
I dropped a new release, hoping it builds a docker image. You can give it a try. It supports Lidarr. You'll have to configure your download path though :P

**Comment by davidnewhall** [comment]
When it finishes building in ~15 min the tag should be `golift/unpackerr:master`

**Comment by davidnewhall** [comment]
Welp it went to `latest` so you can grab that.

**Comment by davidnewhall** [comment]
`master` tag is building now and removes the need for the `path` setting for lidarr. ~20min

**Comment by MammothJerk** [comment]
grabbing it from dockerhub with CA on unraid doesn't seem to wanna populate any fields, i've tried both :latest and :master to no avail. from the looks of it i would have to input all the field manually  😭 

![](https://i.imgur.com/mADJsZ8.png)

**Comment by MammothJerk** [comment]
getting this error now, sonarr and radarr works
`2020/02/13 13:45:43.550388 start.go:204: [ERROR] Lidarr (http://192.168.1.111:8686): json.Unmarshal(response): json: cannot unmarshal number 9423210.0 into Go struct field LidarrRecord.records.size of type int64`

**Comment by davidnewhall** [comment]
Yeah unfortunately there is no unraid template for this yet. You can use the deluge-unpacker template and change the variables, or just make your own. Either works.

I just committed a fix for the number/int error you got. `master` should update shortly with the fix. You also no longer need to provide the path for Lidarr, but I wonder if it'll work for you....
