### ISSUE TITLE
[REQUEST] Possibility to pause SabNZBD while extracting

### ISSUE THREAD

**Issue by Tuumke** [davidnewhall/unpackerr#230]
To improve diskspeeds, it might be nice to have the ability to pause SabNZBD while unpacking? For me at least it improves unpack and download speeds. For some reason, SabNZBD doesn't seem to unpack some .rar archives.

**Comment by bakerboy448** [comment]
SABnzbd doesn't need unpackerr

are you the unpacked release from sab is rar files and needs to be recursively unpacked?

you just need to enable `Enable recursive unpacking` in Sab's flags

**Comment by bakerboy448** [comment]
> It just doesn't extract it for some reason.. Sab and deluge both download to same folder.

that's not advised and you should not be mixing clients' folders.  That also likely means you're not using categories while it is strongly advised and recommended to do so

**Comment by davidnewhall** [comment]
You could always write a command hook to pause and unpause SAB. Unpackerr does not "talk" to SAB today, and I have no intention on making it do so.

**Comment by davidnewhall** [comment]
I'd like to know more about the problem.

> For me at least it improves unpack and download speeds.

By how much? Is this generally a problem, or just something you notice when you happen to look at it?

Most folks don't sit and watch their download/unpacks; it just happens in the background.

**Comment by davidnewhall** [comment]
Please let me know if I can help further. Happy to discuss your situation and help find a solution.
