### ISSUE TITLE
Add option for when using "folder.extract_path" to not create a subfolder

### ISSUE THREAD

**Issue by mizz141** [davidnewhall/unpackerr#233]
Would it be possible to have Unpackerr not generate subfolders when unpacking rars?

I'm in the process of automating unpacking a lot of manga and dumping them into my library, currently the process is as follows:

Upload some series, move it into the unpackerr watched folder, let it extract to a sync folder, copy the folder over into the library, delete and re-create the sync folder.

Problem is, when using "folder.extract_path" it generates yet another folder, in practice it looks something like this:

sync
> manga name < (this folder is created by unpackerr)
>> manga name < (this folder already exists in the rar)
>>>manga name.cbz < (the readable files I need)

What I want it to do is ditch the creation of the first subfolder and just dump the contents of the rar, i.E

sync
> manga name < (the folder from the rar)
>> manga name.cbz < (the readable files)

**Comment by davidnewhall** [comment]
The problem with that approach is that if your source has two files that contain the same items. They'll attempt to overwrite each other. Unpackerr keeps the folder structure the same as the source. What you're describing is how Unpackerr used to behave and it lead to errors and items failing to extract because they matched items in the destination folder tat were extracted from another archive.

**Comment by davidnewhall** [comment]
The solution is probably to make a cmdhook that runs a script to `mv` the extracted files to the location you want them.

**Comment by mizz141** [comment]
The problem with the mv approach would be then deleting the other folder

best I can do with my knowledge of scripts would be simply moving all the files into the folder above, still leaving an empty folder which could lead to issues down the line.

sync
> manga name
>> manga name.cbz < (files moved out of folder)
>> manga name < (this folder would still exists)

As I've seen from the logs, unpackerr creates a temporary directory inside the watched folder (named manga name_unpackerred or sth) which everything gets unpacked into, and then moved out into the sync folder of, so the problem of overwriting files doesn't look like an issue, correct me if I'm wrong on that one tho.

**Comment by davidnewhall** [comment]
> The problem with the mv approach would be then deleting the other folder

That's where `rm` comes in clutch.

> best I can do with my knowledge of scripts

Increasing your knowledge will unlock many doors in the realm of automation.

> the problem of overwriting files doesn't look like an issue

If you have a folder with two zip files that contain the same content, one will attempt to overwrite the other. That's unlikely happening in your scenario, but if you're downloading stuff from the Internet it could certainly happen. The temporary folder name just matches the folder it's extracting with a suffix appended.
