### ISSUE TITLE
first time user, lost with unpacker

### ISSUE THREAD

**Issue by niviljacob** [davidnewhall/unpackerr#234]
A kind user on reddit pointed me to unpacker and i was very excited to use it, but for some reason, unpacker does not unpack any files. 
i fixed all file permission issues and teh logs are clean. I do not use a config file and my config is pretty much OOTB. Env: Unraid 6.11.1, File structure set up using TRaSH guide [/data/[torrents/media]/[movies/tv/music]/, download client is deluge.
![image](https://user-images.githubusercontent.com/49085047/202369190-174d4cbd-f5db-4efb-b66c-e74b2ea49a14.png)

![image](https://user-images.githubusercontent.com/49085047/202369821-2086ddd9-edc4-4dfe-a099-a977b6209d46.png)

The download is complete, which consist of a multi rar archive. radarr says 100% complete, but cant find any files at location.

what am i missing? i appreciate any advise as its my first time in linux environment.

**Comment by davidnewhall** [comment]
Go back 1 screen, select advanced, and show me this screenshot. For Radarr and Sonarr too.
![](https://media.discordapp.net/attachments/781625367391371274/986684482251796560/Screen_Shot_2022-06-15_at_10.31.32_AM.png)

**Comment by niviljacob** [comment]
[image: image.png]
unpacker

[image: image.png]
deluge

[image: image.png]
radarr

[image: image.png]
sonarr

Nivil Thomas

**Comment by bakerboy448** [comment]
Images did not appear to attach / end up on git

**Comment by niviljacob** [comment]
![image](https://user-images.githubusercontent.com/49085047/202512244-7fa94a31-25fc-4448-963b-81f0186ece61.png)

![image](https://user-images.githubusercontent.com/49085047/202512309-35896cee-7cba-4dc4-af41-f4ea590f5b83.png)

![image](https://user-images.githubusercontent.com/49085047/202512333-d1d47956-38ef-4ff5-bf50-589ee4f144c8.png)

![image](https://user-images.githubusercontent.com/49085047/202512360-f21d3bbf-6076-4929-8344-5e0cfd8b45f9.png)

**Comment by bakerboy448** [comment]
change unpackerr to /data/torrents:/mnt/user/data/torrents 

so your paths are consistent

**Comment by davidnewhall** [comment]
Let us know if you need any more assistance!

**Comment by niviljacob** [comment]
It worked like a charm. thank you so much.  just so i understand, why was having the same container path in all three locations important? was that a permissioning issue?

**Comment by bakerboy448** [comment]
The paths need to be consistent.

sonarr said the release was /data/torrents.

that path didn't in unpackerrs world
