### ISSUE TITLE
FreeBSD install instructions do not work.

### ISSUE THREAD

**Issue by niel** [davidnewhall/unpackerr#238]
The path used for wget command results in a 404 error.

**Comment by davidnewhall** [comment]
Seems like some forward rule is broken. Thanks for bringing this to my attention. You can use this URL in the meantime.
https://raw.githubusercontent.com/davidnewhall/unpackerr/master/scripts/install.sh

**Comment by davidnewhall** [comment]
I updated the url in the readme and will update it again only after it works the way it should. Thanks!

**Comment by davidnewhall** [comment]
fwiw, I've since removed the install script entirely. Manual install is recommended.
