### ISSUE TITLE
Possible to add integration with Prowlarr?

### ISSUE THREAD

**Issue by yiveynod** [davidnewhall/unpackerr#244]
Hi!
Thank you for a fantastic application. I use multiple instances of it on my unraid server.

Would it by any chance be possible to add the ability to connect with Prowlarr?

Sometimes downloading is done through Prowlarr WEBUI and it would be great if it automatically unpacks.

**Comment by bakerboy448** [comment]
Prowlarr has no queue to query/check - so there's nothing to check.

You'd probably just need to setup the folder watcher

**Comment by davidnewhall** [comment]
I'm afraid Baker is correct here. AFAIK Prowlarr has no queue. So there's no way for unpackerr to ask it when something is done downloading and no way for unpackerr to ask it when something has been imported. Setting up the folder watch feature on downloads in the prowlarr-tagged download directory should achieve your goal.

**Comment by yiveynod** [comment]
Alright! Thanks!
