### ISSUE TITLE
File path defined but not valid

### ISSUE THREAD

**Issue by Little709** [davidnewhall/unpackerr#31]
Sorry back again. It's very good to see that you're making progress!

I've defined a path in the config file. AND the config file is found so that cannot be the issue. It also sees the path that i've defined. But later in the log it says that it. I am just being stupid or is this a bug?

Executing usermod...
usermod: no changes
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] 01-configure-app: executing...
Copying custom "unpackerr.conf"...
[cont-init.d] 01-configure-app: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020/02/16 11:41:18 [INFO] Unpackerr v0.7.0-beta2-79 Starting! (PID: 215)
2020/02/16 11:41:18 ==> Startup Settings <==
2020/02/16 11:41:18 => Sonarr Configured: 1 server: http://xxx:8989
2020/02/16 11:41:18 => Radarr Configured: 1 server: http://xxx:7878
2020/02/16 11:41:18 => Lidarr Configured: 0 servers
2020/02/16 11:41:18 => Folder Configured: 1 path: /mnt/user/Downloads (delete after:10m0s, delete orig:false, move back:true)
2020/02/16 11:41:18 => Parallel Extracts: 1
2020/02/16 11:41:18 => Poll Interval: 2m0s
2020/02/16 11:41:18 => Poll Timeout: 10s
2020/02/16 11:41:18 => Delete Delay: 5m0s
2020/02/16 11:41:18 => Start Delay: 1m0s
2020/02/16 11:41:18 => Retry Delay: 5m0s
2020/02/16 11:41:18 => Debug Logs: true
2020/02/16 11:41:18.237386 start.go:82: [DEBUG] Starting Cleanup Routine (interval: 1 minute)
2020/02/16 11:41:18.237577 folder.go:87: [ERROR] Folder (cannot watch): stat /mnt/user/Downloads: no such file or directory

**Comment by davidnewhall** [comment]
What is your goal?

**Comment by davidnewhall** [comment]
Did you get it working?

**Comment by davidnewhall** [comment]
The rest of this output you provided looks OK. Is the app able to connect to sonar and radar? Is it working, or are things amiss?

**Comment by Little709** [comment]
I'm sorry! Yeah it's working now!
