### ISSUE TITLE
get Unpackerr to use the path from Sonarr

### ISSUE THREAD

**Issue by armsby** [davidnewhall/unpackerr#32]
can you please add an options so the Unpackerr will use that path for files as they are reported by Sonarr.

 I know that Sonarr does not have path as part of the answer but it is there in the warning message, and could be taken from there

**Comment by davidnewhall** [comment]
I intend to, but this only works for Sonarr v3. **Sonarr v2 does not have the output path in the API.** Lidarr already gets the path automatically since it's in the API.

**Comment by davidnewhall** [comment]
I'll think about it though, and look at the output a bit more.
