### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by jcarroll182** [davidnewhall/unpackerr#33]
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x554d41]

goroutine 123 [running]:
golift.io/rar.RarExtractor(0xc000e3dd40, 0x53, 0xc0032460a0, 0x4a, 0x0, 0x203000)
/go/pkg/mod/golift.io/rar@v0.0.1/gorar.go:38 +0x121
github.com/davidnewhall/deluge-unpacker/delugeunpacker.(*DelugeUnpacker).processArchives(0xc00016e000, 0xc00028e060, 0x2f, 0xc0032460a0, 0x4a, 0xc000bde0b0, 0x1, 0x1, 0xc00086b9a0)
/deluge-unpacker/delugeunpacker/extracts.go:165 +0x1bc
github.com/davidnewhall/deluge-unpacker/delugeunpacker.(*DelugeUnpacker).extractFiles(0xc00016e000, 0xc00028e060, 0x2f, 0xc000b0efa0, 0x41, 0xc000bde0b0, 0x1, 0x1)
/deluge-unpacker/delugeunpacker/extracts.go:140 +0x4d6
github.com/davidnewhall/deluge-unpacker/delugeunpacker.(*DelugeUnpacker).HandleCompleted(0xc00016e000, 0xc00028e060, 0x2f, 0x93d176, 0x6)
/deluge-unpacker/delugeunpacker/pollers.go:226 +0x3b4
created by github.com/davidnewhall/deluge-unpacker/delugeunpacker.(*DelugeUnpacker).CheckRadarrQueue
/deluge-unpacker/delugeunpacker/pollers.go:195 +0x309

**Comment by davidnewhall** [comment]
deluge-unpacker is the old code.

**Comment by davidnewhall** [comment]
This was likely caused by an incomplete file being extracted. I added some code to catch this and properly report an error instead of crash. Thanks for the report!
