### ISSUE TITLE
Partial .mkv output from Rar error not being deleted.

### ISSUE THREAD

**Issue by diablc** [davidnewhall/unpackerr#35]
My setup is seedbox > syncthing >unpackerr > sonar/radarr/lidarr > plex

I am issues with unpackerr decompressing a rar file rar>r01>r02>r03>error (because r04 hasn't finished downloading)  instead of deleting the partially decompressed file it shows it as completed and passes it along to from processing. So now i have 4-10 minutes shows occasionally that should be 30 minutes and movies that are 45 minutes long that should be 2 hours.  I have adjusted wait times, but sometimes syncthings takes a while to download all the rar files because it might lose connection or whatever the case.

**Comment by davidnewhall** [comment]
Any chance you captured the logs when this happened?

**Comment by davidnewhall** [comment]
I'd like to help with this and make it better, but I need some communication. :D

**Comment by davidnewhall** [comment]
Maybe you can setup syncthing to sync to a different directory and move the files into place?
