### ISSUE TITLE
Unpackerr sits at "Awaiting Import" even though *arr has already imported

### ISSUE THREAD

**Issue by rodworks1239** [davidnewhall/unpackerr#37]
2020/03/06 10:54:57.231249 apps.go:71: [Radarr] Updated (http://192.168.1.50:7878/): 0 Items Queued
2020/03/06 10:54:57.232444 apps.go:51: [Sonarr] Updated (http://192.168.1.50:8989/): 3 Items Queued
2020/03/06 10:54:57.232827 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 10:54:57.234201 handlers.go:76: [Sonarr] Completed item still waiting: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb, no extractable files found at: /media/The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2020/03/06 10:54:57.234390 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Completed (torrent:-9223372036854775808%): The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: Foxhead)
2020/03/06 10:54:57.234655 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Downloading (torrent:100%): The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Ep: In the Pines, In the Pines)
2020/03/06 10:54:57.234912 pollers.go:121: [DEBUG] Sonarr: Status: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 1h23m30s, found: true)
2020/03/06 10:54:57.235013 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Waiting, pre-Queue, elapsed: 56m0s, found: true)
2020/03/06 10:54:57.235195 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Waiting, pre-Queue, elapsed: 56m0s, found: true)
2020/03/06 10:54:57.235358 logs.go:57: [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [1 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 10:55:57.225789 logs.go:57: [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [1 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 10:56:57.232769 apps.go:71: [Radarr] Updated (http://192.168.1.50:7878/): 0 Items Queued
2020/03/06 10:56:57.233401 apps.go:51: [Sonarr] Updated (http://192.168.1.50:8989/): 3 Items Queued
2020/03/06 10:56:57.233864 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 10:56:57.235851 handlers.go:76: [Sonarr] Completed item still waiting: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb, no extractable files found at: /media/The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2020/03/06 10:56:57.236089 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Completed (torrent:-9223372036854775808%): The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: Foxhead)
2020/03/06 10:56:57.242240 handlers.go:91: [Sonarr] Extraction Queued: /media/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP, extractable files: 1, items in queue: 0
2020/03/06 10:56:57.242361 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Completed (torrent:100%): The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Ep: In the Pines, In the Pines)
2020/03/06 10:56:57.242472 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Waiting, pre-Queue, elapsed: 58m0s, found: true)
2020/03/06 10:56:57.242640 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Queued, elapsed: 0s, found: true)
2020/03/06 10:56:57.242714 pollers.go:121: [DEBUG] Sonarr: Status: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 1h25m30s, found: true)
2020/03/06 10:56:57.242778 logs.go:57: [Unpackerr] Queue: [1 waiting] [1 queued] [0 extracting] [1 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 10:56:57.245298 handlers.go:99: Extraction Started: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP, items in queue: 0
2020/03/06 10:56:57.245837 start.go:85: [DEBUG] Extracting File: /media/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP/the.outsider.2020.s01e07.internal.1080p.web.h264-amrap.rar to /media/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP_unpackerred
2020/03/06 10:57:25.417550 start.go:85: [DEBUG] Renamed Temp File: /media/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP_unpackerred/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP.mkv -> /media/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP.mkv
2020/03/06 10:57:25.418325 start.go:85: [DEBUG] Renamed Temp File: /media/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP_unpackerred/_unpackerred -> /media/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP/_unpackerred
2020/03/06 10:57:25.418904 start.go:79: Deleted (recursively): /media/The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP_unpackerred
2020/03/06 10:57:25.419120 handlers.go:105: Extraction Finished: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP => elapsed: 28s, archives: 1, extra archives: 0, files extracted: 1, wrote: 3581MiB
2020/03/06 10:57:57.225754 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 10:58:57.232070 apps.go:71: [Radarr] Updated (http://192.168.1.50:7878/): 0 Items Queued
2020/03/06 10:58:57.232714 apps.go:51: [Sonarr] Updated (http://192.168.1.50:8989/): 3 Items Queued
2020/03/06 10:58:57.232963 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 10:58:57.235094 handlers.go:76: [Sonarr] Completed item still waiting: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb, no extractable files found at: /media/The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2020/03/06 10:58:57.235294 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Completed (torrent:-9223372036854775808%): The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: Foxhead)
2020/03/06 10:58:57.235443 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Downloading (torrent:100%): The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Ep: In the Pines, In the Pines)
2020/03/06 10:58:57.235677 pollers.go:121: [DEBUG] Sonarr: Status: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 1h27m30s, found: true)
2020/03/06 10:58:57.235812 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Waiting, pre-Queue, elapsed: 1h0m0s, found: true)
2020/03/06 10:58:57.235896 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 1m32s, found: true)
2020/03/06 10:58:57.236065 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 10:59:57.225926 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 11:00:57.231494 apps.go:71: [Radarr] Updated (http://192.168.1.50:7878/): 0 Items Queued
2020/03/06 11:00:57.232188 apps.go:51: [Sonarr] Updated (http://192.168.1.50:8989/): 3 Items Queued
2020/03/06 11:00:57.232422 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 11:00:57.233378 handlers.go:76: [Sonarr] Completed item still waiting: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb, no extractable files found at: /media/The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2020/03/06 11:00:57.233464 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Completed (torrent:-9223372036854775808%): The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: Foxhead)
2020/03/06 11:00:57.233547 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Downloading (torrent:100%): The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Ep: In the Pines, In the Pines)
2020/03/06 11:00:57.233643 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 3m32s, found: true)
2020/03/06 11:00:57.233723 pollers.go:121: [DEBUG] Sonarr: Status: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 1h29m30s, found: true)
2020/03/06 11:00:57.233814 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Waiting, pre-Queue, elapsed: 1h2m0s, found: true)
2020/03/06 11:00:57.233905 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 11:01:57.225774 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 11:02:57.231320 apps.go:71: [Radarr] Updated (http://192.168.1.50:7878/): 0 Items Queued
2020/03/06 11:02:57.232201 apps.go:51: [Sonarr] Updated (http://192.168.1.50:8989/): 3 Items Queued
2020/03/06 11:02:57.232380 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 11:02:57.233923 handlers.go:76: [Sonarr] Completed item still waiting: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb, no extractable files found at: /media/The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2020/03/06 11:02:57.234050 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Completed (torrent:-9223372036854775808%): The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: Foxhead)
2020/03/06 11:02:57.234133 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 11:02:57.234228 pollers.go:121: [DEBUG] Sonarr: Status: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 1h31m30s, found: true)
2020/03/06 11:02:57.234312 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Waiting, pre-Queue, elapsed: 1h4m0s, found: true)
2020/03/06 11:02:57.234426 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 5m32s, found: true)
2020/03/06 11:02:57.234559 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 11:03:57.225853 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 11:04:57.233102 apps.go:71: [Radarr] Updated (http://192.168.1.50:7878/): 0 Items Queued
2020/03/06 11:04:57.233818 apps.go:51: [Sonarr] Updated (http://192.168.1.50:8989/): 3 Items Queued
2020/03/06 11:04:57.233914 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 11:04:57.233997 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 11:04:57.234086 apps.go:94: [DEBUG] Sonarr (http://192.168.1.50:8989/): Downloading (torrent:100%): The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Ep: Foxhead)
2020/03/06 11:04:57.234174 pollers.go:121: [DEBUG] Sonarr: Status: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 1h33m30s, found: true)
2020/03/06 11:04:57.234254 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Waiting, pre-Queue, elapsed: 1h6m0s, found: true)
2020/03/06 11:04:57.234332 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 7m32s, found: true)
2020/03/06 11:04:57.234408 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 11:05:57.225773 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 11:06:57.232733 apps.go:71: [Radarr] Updated (http://192.168.1.50:7878/): 0 Items Queued
2020/03/06 11:06:57.233551 apps.go:51: [Sonarr] Updated (http://192.168.1.50:8989/): 2 Items Queued
2020/03/06 11:06:57.233852 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 11:06:57.234017 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 11:06:57.234392 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 9m32s, found: true)
2020/03/06 11:06:57.234635 pollers.go:121: [DEBUG] Sonarr: Status: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 1h35m30s, found: true)
2020/03/06 11:06:57.234960 handlers.go:34: [Sonarr] Imported: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (not extracted, removing from history)
2020/03/06 11:06:57.235247 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E08.Foxhead.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb (Waiting, pre-Queue, elapsed: 1h8m0s, found: false)
2020/03/06 11:06:57.235348 logs.go:57: [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
root@Unraid:~#

**Comment by rodworks1239** [comment]
![Screen Shot 2020-03-06 at 11 17 33 AM](https://user-images.githubusercontent.com/52292844/76101287-2fd13c80-5f9c-11ea-9488-12fb2ffec3d2.png)

**Comment by rodworks1239** [comment]
2020/03/06 11:18:57.231210 apps.go:71: [Radarr] Updated (http://192.168.1.50:7878/): 0 Items Queued
2020/03/06 11:18:57.231335 apps.go:51: [Sonarr] Updated (http://192.168.1.50:8989/): 2 Items Queued
2020/03/06 11:18:57.231560 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 11:18:57.231833 apps.go:89: [DEBUG] Sonarr (http://192.168.1.50:8989/): Item Waiting for Import: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP
2020/03/06 11:18:57.232064 pollers.go:121: [DEBUG] Sonarr: Status: The.Outsider.2020.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 21m32s, found: true)
2020/03/06 11:18:57.232253 pollers.go:121: [DEBUG] Sonarr: Status: Star.Trek.Picard.S01E07.iNTERNAL.1080p.WEB.H264-AMRAP (Extracted, Awaiting Import, elapsed: 1h47m30s, found: true)
2020/03/06 11:18:57.232427 logs.go:57: [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/03/06 11:19:57.225897 logs.go:57: [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [2 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

**Comment by rodworks1239** [comment]
Solved by switching to a different version container.

**Comment by davidnewhall** [comment]
This bug has popped up a few times, but the latest release should not have this problem..

**Comment by rodworks1239** [comment]
This was the Hotio version, switched to the Golift version and works perfectly.

**Comment by davidnewhall** [comment]
Do you possibly have the start of the logs you pasted earlier, where the application started and printed the version?

**Comment by rodworks1239** [comment]
No, the Hotio version cuts off the log.  I was running the latest version if that helps.  Got referred here when I posted the issue on the unraid forum.

**Comment by davidnewhall** [comment]
Thanks for the info! Please open another issue if you run into more bugs.

**Comment by rodworks1239** [comment]
Ok, I think I'm having the issue again now.  Made no changes since it worked fine 2 days ago.
[unpackerr.log](https://github.com/davidnewhall/unpackerr/files/4304022/unpackerr.log)

**Comment by rodworks1239** [comment]
![Screen Shot 2020-03-08 at 7 13 25 PM](https://user-images.githubusercontent.com/52292844/76172936-eede5100-6170-11ea-818f-52cf2eb5d6f9.png)

**Comment by davidnewhall** [comment]
These logs are great! Thank you! I think this might be a Radarr-specific problem. Most moves don't come compressed, so that app is hard to test. I'm going to go eyeball my code for a while and see if I can figure out what happened here. The logs make it clear there's a bug. The item clearly left the Radarr queue and then just didn't get recognized as imported. 

Please let me know if you experience this again.

**Comment by davidnewhall** [comment]
I think I see what happened, and this might be a bug in Radarr, I'm not sure.

This line triggered the extraction (the download was marked completed):
```
2020/03/08 15:35:57.011193 apps.go:114: [DEBUG] Radarr: (http://192.168.1.50:7878/): Completed (torrent:100%): Jumanji.The.Next.Level.2019.1080p.BluRay.x264-YOL0W
```

The extraction finished a little over a minute later:
```
2020/03/08 15:39:08.932423 handlers.go:105: Extraction Finished: Jumanji.The.Next.Level.2019.1080p.BluRay.x264-YOL0W => elapsed: 1m12s, archives: 1, extra archives: 0, files extracted: 1, wrote: 8946MiB
```

Then, a new download was seen in the Radarr queue, this is the unexpected log line:
```
2020/03/08 15:39:57.013822 apps.go:114: [DEBUG] Radarr: (http://192.168.1.50:7878/): Downloading (torrent:100%): Jumanji.The.Next.Level.2019.1080p.BluRay.x264-YOL0W_unpackerred
```
^^ notice the name. This data comes directly from Radarr, so I'm not sure how or why this happened.

Then the original item that was just extracted showed up as "incomplete." Notice is says _downloading_ (which means it's not done). I believe this is where the bug was triggered. Something that should be either _complete_ or _nonexistent_ just _restarted_.
```
2020/03/08 15:41:57.010706 apps.go:114: [DEBUG] Radarr: (http://192.168.1.50:7878/): Downloading (torrent:100%): Jumanji.The.Next.Level.2019.1080p.BluRay.x264-YOL0W
```

It stayed this way for a while until (before) `2020/03/08 15:45:57` when it was no longer in the queue.

I'm going to try to work around this situation in the code, but if you are running Radarr v3 (or some beta version), you may want to report this anomaly there. If not, I dunno, I hope I can fix this and/or it doesn't happen often! Will let you know as soon as I can. Thanks again!

**Comment by davidnewhall** [comment]
Everything tells me the item is still showing up the Radarr `Activity` Queue. Please let me know if it is. :D

**Comment by rodworks1239** [comment]
> Everything tells me the item is still showing up the Radarr `Activity` Queue. Please let me know if it is. :D

Yes, when I get this issue the movie sits in the activity que until I manually delete.

**Comment by rodworks1239** [comment]
![Screen Shot 2020-03-09 at 7 36 01 PM](https://user-images.githubusercontent.com/52292844/76266245-3af6c780-623d-11ea-9253-a994b42bc223.png)

**Comment by davidnewhall** [comment]
Radarr imported the movie, and then left it in the activity queue? Unpackerr will not delete it until it leaves the queue. This sounds like a bug in Radarr.

**Comment by rodworks1239** [comment]
Seems like Radarr sees the .rar files and thinks they still need to be processed and leaves it in the que.  When my torrent client did the unpacking, radarr and sonarr would both leave folders with the .rar files even after importing the media successfully.

I'll keep an eye on it and post the logs if it happens again.

**Comment by davidnewhall** [comment]
Radarr doesn't "see" .rar files. It seems .mkv (video files) and imports them. Did it import the mkv and then leave the item in queue? I've never seen that happen in Radarr.

**Comment by rodworks1239** [comment]
Yes, it's imported, see the radarr screen shot above.  The times are comparable to the logs.

**Comment by davidnewhall** [comment]
I wish I could come up with a reason for this, but all I can determine is Radarr had a bug. I found an old github issue where @hotio recommended "changing the category" in the download client to make Radarr "lose track" of the download. That may be a useful workaround if this happens again.

**Comment by hotio** [comment]
My image doesn't cut off the logs, they are nicely written to the log file and with DEBUG=yes they are viewable from within unraid until unraid rolls them over....also you are running a mono version known to cause issues fyi...

**Comment by davidnewhall** [comment]
Yeah, my best advice is to try another/new/different/better Radarr container. Like I said, this really looks like a Radarr bug to me.

**Comment by rodworks1239** [comment]
Updated the container and ran a file through it successfully. Thanks for your help.

[unpackerr.log](https://github.com/davidnewhall/unpackerr/files/4322076/unpackerr.log)
