### ISSUE TITLE
Not an issue, just a question. Does unpackerr extract in place?

### ISSUE THREAD

**Issue by pairofcrocs** [davidnewhall/unpackerr#38]
Hi David! Very cool program, I really want to start working with it, but I have a simple question before I do so.

So I have my download client create a new folder for every file that starts downloading such as
`/Downloads/newmovie/`
Does upackerr create the file inside of that folder, or does it leave it in the downloads folder? That may have sounded really confusing, below is what I'm basically talking about.

1. `/Downloads/newmovie.mkv`
or
2.` /Downloads/newmovie/newmovie.mkv`

thanks!

**Comment by davidnewhall** [comment]
`/Downloads/newmovie_unpackerr/newmovie.mkv` is where it's extracted to. Once extraction finishes, all extracted files are moved into `/Downloads/newmovie/`.

**Comment by davidnewhall** [comment]
In other words, it does exactly what Radarr expects to import the movie and subs.
