### ISSUE TITLE
Sits in waiting forever

### ISSUE THREAD

**Issue by y0da822** [davidnewhall/unpackerr#39]
Any idea why i see this?  Can the file be seeding?

What am i missing?

2020/04/09 19:06:08.878602 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/04/09 19:07:08.646438 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

**Comment by davidnewhall** [comment]
What's the status of the items in Sonarr and Radarr? Turning on debug mode will print more data.

**Comment by y0da822** [comment]
I thought I had debug mode on. Will post more logs shortly. 

Sonarr just has that orange icon after completion and says no files elegible for import. 

I want to add that when deluge finishes downloading I have it move to a completed folder and it seeds from there but unpackerr seems to see it there as that’s where I pointed the unpackerr container.

**Comment by davidnewhall** [comment]
You may have debug mode on, but you did not provide any of those logs. Look through the logs, it should become obvious what's hung up and why. If not, please provide more of your logs and perhaps a screenshot of Sonarr. The more data you provide the easier it is to tell what's happening.

**Comment by y0da822** [comment]
Other than status stating that things are downloading, this is what I see.

2020/04/10 07:42:08.821482 pollers.go:121: [DEBUG] Sonarr: Status: xxxxx-NERO (Waiting, pre-Queue, elapsed: 2h24m0s, found: true)
2020/04/10 07:42:08.821502 pollers.go:121: [DEBUG] Sonarr: Status: xxxxx-AVS (Waiting, pre-Queue, elapsed: 12h44m0s, found: true)
2020/04/10 07:42:08.821519 pollers.go:121: [DEBUG] Sonarr: Status: xxxxx-NERO (Waiting, pre-Queue, elapsed: 32m0s, found: true)
2020/04/10 07:42:08.821539 logs.go:57: [Unpackerr] Queue: [3 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

This is what sonarr shows

![image](https://user-images.githubusercontent.com/54944216/78988548-3bfe6b80-7aff-11ea-827a-88e6690c890a.png)

**Comment by y0da822** [comment]
I just paused one of the torrents - still wouldn't process it.  Confused.  Then I removed the torrent from deluge itself and it said sonarr imported the file, but it didnt and didnt extract - had to manually extract and manually import

**Comment by davidnewhall** [comment]
Here's the problem.
```
2020/04/10 07:46:08.823050 handlers.go:76: [Sonarr] Completed item still waiting: xxxxxxxWEB.H264-NERO, no extractable files found at: /downloads/complete/xxxxxxx.H264-NERO
```
It found no rar file in that path.

**Comment by y0da822** [comment]
There is stuff there - but what about these 3 happening right now


2020/04/10 15:50:08.813300 pollers.go:121: [DEBUG] Sonarr: Status: Greys.Anatomy.S07E03.MULTi.1080p.WEB.H264-NERO (Waiting, pre-Queue, elapsed: 10h32m0s, found: true)
2020/04/10 15:50:08.813320 pollers.go:121: [DEBUG] Sonarr: Status: PAW.Patrol.S01E22.Pups.and.the.Lighthouse.Boogie.-.Pups.Save.Ryder.720p.WEBRip.x264.AAC (Waiting, pre-Queue, elapsed: 34m0s, found: true)
2020/04/10 15:50:08.813338 pollers.go:121: [DEBUG] Sonarr: Status: Greys.Anatomy.S02E01.MULTi.1080p.WEB.H264-NERO (Waiting, pre-Queue, elapsed: 8h40m0s, found: true)
2020/04/10 15:50:08.813360 logs.go:57: [Unpackerr] Queue: [3 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
2020/04/10 15:51:08.646400 logs.go:57: [Unpackerr] Queue: [3 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

**Comment by davidnewhall** [comment]
You're not pasting the part of the log that tells you the answer to the question you're asking.

**Comment by y0da822** [comment]
youre right - hold on - i can be an ignoramus and I am sure thats where this is headed.

**Comment by y0da822** [comment]
2020/04/10 15:54:08.827825 handlers.go:76: [Sonarr] Completed item still waiting: Greys.Anatomy.S02E01.MULTi.1080p.WEB.H264-NERO, no extractable files found at: /downloads/complete/Greys.Anatomy.S02E01.MULTi.1080p.WEB.H264-NERO

docker run -d --init \
--name=unpackerr \
--restart unless-stopped \
-v /home/administrator/htpc/config/unpackerr/unpackerr.conf:/etc/unpackerr/unpackerr.conf \
-v /etc/localtime:/etc/localtime:ro \
-v /home/administrator/htpc/downloads/complete:/downloads \
madcatsu/unpackerr-alpine-daemon:latest \
-c /etc/unpackerr/unpackerr.conf

administrator@p2-plexseed1:~/htpc/downloads/complete/Greys.Anatomy.S02E01.MULTi.1080p.WEB.H264-NERO$ ls
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r00  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r13  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r26  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r39
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r01  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r14  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r27  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r40
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r02  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r15  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r28  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r41
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r03  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r16  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r29  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r42
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r04  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r17  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r30  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r43
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r05  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r18  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r31  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r44
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r06  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r19  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r32  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r45
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r07  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r20  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r33  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r46
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r08  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r21  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r34  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r47
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r09  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r22  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r35  greys.anatomy.s02e01.multi.1080p.web.h264-nero.rar
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r10  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r23  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r36  greys.anatomy.s02e01.multi.1080p.web.h264-nero.sfv
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r11  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r24  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r37
greys.anatomy.s02e01.multi.1080p.web.h264-nero.r12  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r25  greys.anatomy.s02e01.multi.1080p.web.h264-nero.r38
administrator@p2-plexseed1:~/htpc/downloads/complete/Greys.Anatomy.S02E01.MULTi.1080p.WEB.H264-NERO$ pwd
/home/administrator/htpc/downloads/complete/Greys.Anatomy.S02E01.MULTi.1080p.WEB.H264-NERO
administrator@p2-plexseed1:~/htpc/downloads/complete/Greys.Anatomy.S02E01.MULTi.1080p.WEB.H264-NERO$

**Comment by davidnewhall** [comment]
Change this
```
-v /home/administrator/htpc/downloads/complete:/downloads 
```
to this
```
-v /home/administrator/htpc/downloads:/downloads 
```

**Comment by y0da822** [comment]
ok - why though?  what am I missing?

**Comment by davidnewhall** [comment]
Unpackerr is looking in `/download/completed/<movie>` for rar files. You've mounted the `completed` folder at `/downloads` instead of the `downloads` folder. So it ends up looking for rar files at `/home/administrator/htpc/downloads/complete/complete`

**Comment by y0da822** [comment]
ahhh thats what your program is doing I guess?  I didnt see that anywhere - just figured I had to point it where deluge said this is where completed downloads go.

**Comment by davidnewhall** [comment]
The `/downloads` path should be identical on deluge, sonarr, radarr and unpackerr containers.

**Comment by y0da822** [comment]
LOl - i read that too - really it all needs to be pointed at same level - thank you

**Comment by davidnewhall** [comment]
Please re-open or make another issue if you run into more problems. Hope it works out!!

**Comment by y0da822** [comment]
already working!  Thanks!
