### ISSUE TITLE
Install on Windows without Docker?

### ISSUE THREAD

**Issue by profucius** [davidnewhall/unpackerr#41]
Hi there, excellent looking application. I've been looking for something like this for a long time.

Currently, I am unable to install Docker on my computer, however I do have Sonarr, Radarr, etc etc running on here via their installers. Is there a way I can install this on my Windows machine without Docker?

I have Python, MongoDB, NodeJS, etc already installed, if that helps.

**Comment by davidnewhall** [comment]
There's a windows `.exe` file on the [Releases](https://github.com/davidnewhall/unpackerr/releases) page. Combine that with [a config file](https://github.com/davidnewhall/unpackerr/blob/master/examples/unpackerr.conf.example), and this should run just fine on Windows. Let me know if you have any specific questions I can help with!

**Comment by profucius** [comment]
Oh I see, is it titled amd64.exe.zip? I didn't recognize that as a windows release, most other GitHub releases I find are labeled as "Windows". I'll give that a try!

**Comment by davidnewhall** [comment]
That is correct! It's compiled 64 bit for a 64 bit Windows OS. `amd64` and `x86_64` are the designators for that. Windows is just weird. :D

**Comment by napei** [comment]
Relevant to this issue, would be great to have this implemented as a service/daemon like sonarr/radarr. Perhaps supporting windows services and also linux systemd etc. I'm running this on docker in Windows, previously I was using task scheduler to fire it off in the background.

**Comment by davidnewhall** [comment]
I have no idea how to build an installer or setup a service in windows. :(

**Comment by napei** [comment]
> I have no idea how to build an installer or setup a service in windows. :(

Check out [https://github.com/mh-cbon/go-msi](https://github.com/mh-cbon/go-msi) for building msi packages, and there are examples for writing a windows service [here](https://github.com/golang/sys/blob/master/windows/svc/example/service.go)

There is also https://github.com/judwhite/go-svc for writing services. I personally haven't done this, but I think that these options are pretty baseline for what people do.

**Comment by davidnewhall** [comment]
Appreciate the links. I still want to look into this more, but haven't had time. **Leaving this issue open so I don't lose this context.**

**Comment by Techie5879** [comment]
Having trouble with how to install this on windows, took a look at the links but cant figure out...any help?

**Comment by austinwbest** [comment]
Copy the executable and the conf to C:\ProgramData\unpackerr and run it from there (to simplify your life)
Open the conf and edit it accordingly with your api keys, etc

**Comment by Techie5879** [comment]
what should be the extension of the conf file? or should I just name it CONF?

**Comment by austinwbest** [comment]
![image](https://user-images.githubusercontent.com/8321115/100381797-c391df80-2fe7-11eb-9708-ea2cfc69ecdb.png)

**Comment by Techie5879** [comment]
Thanks! I'll be trying it now

**Comment by Techie5879** [comment]
A few more questions and then I think it will be all cleared up:
Suppose both Sonarr and Radarr download to `D:\sonarr_radarr_down`, and, lets say, the Sonarr folder is `D:\TV`. The files downloaded via Sonarr (using Deluge) are being stored in `D:\TV\show_name\Season_No\`, under which each episode has a folder that contains the rared files.

I have set my Sonarr and Radarr download directories as `D:\sonarr_radarr_down`, but I also want to be able to delete the extracted files from the extracted folder after importing is finished but keep it in the Sonarr media library. Do I need to edit the bottom-most section of the conf file?

**Comment by davidnewhall** [comment]
No, do not use the `Folder` feature for arr apps. The only thing that can be difficult to configure is the `path`, but on a single system (no Docker) it's much easier. Just run it, watch the log/output for a bit and see if it has the right paths in the messages. If not, quit it, fix the paths, and try again. It overall pretty easy. It will deleted the extracted files after sonarr/radarr import them.
