### ISSUE TITLE
Possible to move the completed files to a subfolder instead of the parent-root?

### ISSUE THREAD

**Issue by SilentFez** [davidnewhall/unpackerr#42]
Been running into some trouble with a couple of files that have packed subtitles where the subtitle archive have the same name as the main movie archive. Example scenario:

```
Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup
└--Subs
|  └--some-movie.2160p.subs.rar
|     └--some-movie.2160p.idx
|     └--some-movie.2160p.rar <------ Shares the same name as the main movie archive below
|        └--some-movie.2160p.sub
└--Proof
└--some-movie.2160p.rar <-----------------------------------------------------------------
└--some-movie.2160p.r00
└--some-movie.2160p.r01
```

Looking at the log, the subtitle archive gets copied over to the main folder and that in turn overwrites the main movie archive.
```
2020/07/27 13:39:39.191494 handlers.go:99: Extraction Started: Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup, items in queue: 0,
2020/07/27 13:39:39.280461 start.go:85: [DEBUG] Extracting File: /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup/Subs/some-movie.2160p-subs.rar to /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup_unpackerred,
2020/07/27 13:39:44.019320 start.go:85: [DEBUG] Extracting File: /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup_unpackerred/some-movie.2160p.rar to /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup_unpackerred,
2020/07/27 13:39:59.684392 start.go:85: [DEBUG] Extracting File: /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup/some-movie.2160p.rar to /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup_unpackerred,
2020/07/27 13:40:06.394948 start.go:85: [DEBUG] Renamed Temp File: /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup_unpackerred/_unpackerred -> /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup/_unpackerred,
2020/07/27 13:40:06.512903 start.go:85: [DEBUG] Renamed Temp File: /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup_unpackerred/some-movie.2160p.idx -> /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup/some-movie.2160p.idx,
2020/07/27 13:40:06.675444 start.go:85: [DEBUG] Renamed Temp File: /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup_unpackerred/some-movie.2160p.rar -> /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup/some-movie.2160p.rar,
2020/07/27 13:40:06.824229 start.go:85: [DEBUG] Renamed Temp File: /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup_unpackerred/some-movie.2160p.sub -> /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup/some-movie.2160p.sub,
```

A solution to this would be to put the files in a subfolder instead of copying the files to the parent-root or have the option to exclude the subs-folder from extraction.

Renamed Temp File: /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup_unpackerred/some-movie.2160p.rar -> /downloads/Some.Movie.2020.2160p.UHD.BluRay.x265-SomeGroup/**_unpackerred**/some-movie.2160p.rar

Other then this very specific scenario, the software have been working flawlessly. 
Thanks for putting together this awesome project, have tried so many different archive solutions and unpackerr just solves it all!

Edit: Did some checks and it seems most movies that comes with subtitles have this problem.

**Comment by davidnewhall** [comment]
Interesting. I'll look into this in next few days. Thank you for the report!!

**Comment by davidnewhall** [comment]
I'm pretty sure what I'm going to do here is.. not move `.rar` files back into the download folder. I think the people packing these movies are to blame here. Hiding a file inside another file that will overwrite your main file seems sketch to me, but it is what it is, and I'll try to work around that bug.

**Comment by SilentFez** [comment]
Sweet, much appreciated. 

> 
> 
> I'm pretty sure what I'm going to do here is.. not move `.rar` files back into the download folder. 

That sounds good!

> 
> 
> Hiding a file inside another file that will overwrite your main file seems sketch to me, but it is what it is, and I'll try to work around that bug.

Yeah, it could have been easily avoided by the releasegroups that does it, weird one indeed.

**Comment by davidnewhall** [comment]
I took the approach of: do not overwrite any existing files when moving things back. If you're using my docker image, try the `bugs` tag.

**Comment by davidnewhall** [comment]
I saw this new code in action with a `file_id.diz` file. It refused to overwrite it. I think this should be fixed now.

**Comment by SilentFez** [comment]
Sweet, havent had the time to test it, but this sounds great! Thanks for the fix.

**Comment by davidnewhall** [comment]
It's only in `master` atm. If you use docker, pull the `master` tag.

**Comment by SilentFez** [comment]
Can confirm that it is working, thanks again!
