### ISSUE TITLE
Help with path to downloads

### ISSUE THREAD

**Issue by influx3k** [davidnewhall/unpackerr#44]
Hi, does the download path in unpackerr.conf have to be the actual full path on the host or the path in the container?

For example, my downloads folder on the host is at:

/mnt/Mxx/downloads

and the path in the container is just

/downloads

So I'm not sure which path to put in the .conf file.

I guess I'm confused because when I created the container part of my docker run was creating a volume that maps the two like so...

docker run -d -v /mnt/Mxx/downloads:/downloads -v /home/pxxxxxxx/Docker/unpackerr/unpackerr.conf:/etc/unpackerr/unpackerr.conf golift/unpackerr

So in my .conf I just left it as path = "/downloads" because shouldn't that be mapped to the actual full path on the host?  Any help would be appreciated!  Still new to Docker and Radarr, Sonarr, etc.

Thank you!

Todd B

**Comment by davidnewhall** [comment]
> So in my .conf I just left it as path = "/downloads" because shouldn't that be mapped to the actual full path on the host?

I think maybe you made a typo in this sentence, and I'm not sure if it's the `"/downloads"` path, or the fact that you called that the path on your **host** and _not_ your **container**. `/downloads` is the container path, and that sounds like where the app, running inside the container, should look for downloads. As long as `/downloads` is the path you gave your download client in it's container, everything should work out swimmingly with that path setting. 

Unpackerr also looks at the error message returned by radarr and sonarr to try to "override" your setting and use whatever they use. This works out well for most folks. Are you getting errors? They should show you the path it's trying to read from, and you can hopefully deduce if it's correct or not.

**Comment by influx3k** [comment]
Hi, sorry for any confusion. I mean that since it’s mapped in Docker, that Transmission is looking in /downloads in the container but that is actually mapped to /mnt/Mxx/downloads on disk of the host. Pretty sure I had my terminology right.

I gave the conf file /downloads (just left it how it was), which is the same as the download client in its container. So it should work, but I didn’t get an extracted file when I did a test, so I thought maybe it was something with my paths. Any ideas?

I’ll check for any errors tomorrow, aboutntic all it a night. Thanks for your help!

**Comment by davidnewhall** [comment]
Please provide the logs from the application to troubleshoot the behavior. It provides enough information that I can usually pin the problem down pretty quickly. `docker logs <container>` should print them out. Use `docker ps` to find the `<container>`.

**Comment by influx3k** [comment]
Ok, I looked at the logs and I think I found the problem.  Transmission stores finished downloads in /downloads/complete and I had just put /downloads in the conf file.  Now I did mount the volume at the higher level /downloads though, but put /downloads/complete in the conf file.

**upackerr.conf:**

`[[sonarr]]
   url = "http://pxxxxx.bxxxxxxxx.lan:8989"
   api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
   # File system path where downloaded Sonarr items are located.
   path = "/downloads/complete"

[[radarr]]
  url = "http://pxxxxxx.bxxxxxxx.lan:7878"
  api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  # File system path where downloaded Radarr items are located.
  path = "/downloads/complete"

[[lidarr]]
  url = "http://pxxxxx.bxxxxxxxx.lan:8686"
  api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"`

**docker run command:**

`docker run -d -v /mnt/Mxx/downloads:/downloads -v /home/pxxxxx/Docker/unpackerr/unpackerr.conf:/etc/unpackerr/unpackerr.conf golift/unpackerr`

That should be Ok right?  Log shows it's looking in /downloads/complete

Also, I noticed that in the example unpackerr.conf file that there is no path line under [[lidar]] ?  Is that correct?

**Comment by davidnewhall** [comment]
Yeah that all seems OK.  Lidarr integration gets the path from Lidarr API; Lidarr is newer and different.

**Comment by influx3k** [comment]
Ok, got it working.  Any way to get it to deleted the extracted files when complete.  Would that be the delete_after = "10m"delete_after = “10m” line?

--
Todd Benivegna // todd@benivegna.com

**Comment by davidnewhall** [comment]
It will delete them. Yes, `delete_after` refers to how long to wait before deleting. 10m is usually good. Takes about 20m total IIRC.

**Comment by influx3k** [comment]
Yes I saw after I replied that it got deleted some time later. However delete_after is commented out?

--
Todd Benivegna // todd@benivegna.com

**Comment by davidnewhall** [comment]
Commenting it out will default to 1s, so files will delete pretty quickly after extraction.
