### ISSUE TITLE
[ERROR] Radarr (http://radarr:7878): c.Req(queue): failed: http://radarr:7878/api/queue (status: 401/401 Unauthorized)

### ISSUE THREAD

**Issue by travisboss** [davidnewhall/unpackerr#45]
Getting this error and it seems to do with the api?

I am also unsure if this is a radarr issue or unpackerr issue.  I set up a compose file for unpackerr and use the hostname 'radarr' this works with 'sonarr' but in my testing I also tried the internal docker IP along with the host IP and get this same error.

I also refreshed my api key and tried a new one but radarr keeps giving this error.  Thoughts?

`[ERROR] Radarr (http://radarr:7878): c.Req(queue): failed: http://radarr:7878/api/queue (status: 401/401 Unauthorized)`

**Comment by travisboss** [comment]
This was my issue neither unpackerr or radarr.

**Comment by davidnewhall** [comment]
Sorry I didn't answer sooner. I honestly wasn't sure what to say. Looks like a bad api key from the error... Glad you figured it out!
