### ISSUE TITLE
Setting Delete After to 0 doesn't disable deletion

### ISSUE THREAD

**Issue by HalianElf** [davidnewhall/unpackerr#47]
Running hotio's image. I have these environment variables
```
      - "UN_FOLDER_0_PATH=/data/torrents/unsorted"
      - "UN_FOLDER_0_DELETE_AFTER=0"
      - "UN_FOLDER_0_DELETE_ORIGINAL=false"
      - "UN_FOLDER_0_MOVE_BACK=false"
```
Notes on the configuration say to set delete_after to 0 to disable which is what I did. Downloaded a torrent with a rar in it and it basically instantly deleted it after extraction.

Relevant logs:
```
2020/08/31 05:53:12 Unpackerr v0.7.0-173 Starting! (PID: 218) 2020-08-31 05:53:12.552316956 -0400 EDT m=+0.005836391
2020/08/31 05:53:12 ==> Startup Settings <==
2020/08/31 05:53:12  => Sonarr Config: 1 server: http://sonarr:8989 @ /downloads (apikey: true, timeout: 10s)
2020/08/31 05:53:12  => Radarr Config: 1 server: http://radarr:7878 @ /downloads (apikey: true, timeout: 10s)
2020/08/31 05:53:12  => Lidarr Config: 1 server: http://lidarr:8686 (apikey: true, timeout: 10s)
2020/08/31 05:53:12  => Folder Config: 1 path: /data/torrents/unsorted (delete after:0s, delete orig:false, move back:false)
2020/08/31 05:53:12 [Folder] Watching: /data/torrents/unsorted/
2020/09/02 17:19:10 [Folder] Tracking New Item: /data/torrents/unsorted/some_file
2020/09/02 17:20:12 [Folder] Queued: /data/torrents/unsorted/some_file, queue size: 0
2020/09/02 17:20:12 [Folder] Extraction Started: /data/torrents/unsorted/some_file, items in queue: 0
2020/09/02 17:24:51 [Folder] Extraction Finished: /data/torrents/unsorted/some_file => elapsed: 4m39s, archives: 1, extra archives: 0, files extracted: 74, written: 1785MiB
2020/09/02 17:24:58 Deleted (recursively): /data/torrents/unsorted/some_file_unpackerred
2020/09/02 17:35:12 [] Finished, Removed History: /data/torrents/unsorted/some_file
```

**Comment by davidnewhall** [comment]
Are you actually trying to usefully use the `folder` feature in this application? Or are you trying to integrate with sonarr/radarr? To date, no one uses the `folder` configs; it's not for the *arr apps. The behavior of the environment variables you've configured is described in the [example config file](https://github.com/davidnewhall/unpackerr/blob/master/examples/unpackerr.conf.example#L64-L74). Please let me know what behavior you're attempt to achieve and I'll help get your config dialed in.

**Comment by davidnewhall** [comment]
Worked with Halian on Discord. Determined this looks like a bug where the folder logic is deleting the `_unpackerred` temp folder when `move_back` is set to `false`. When that's false, the extract folder shouldn't be deleted. Seems like a bug.

**Comment by davidnewhall** [comment]
This will be fixed in the next release. If you want to try it now, use the `bugs` Docker tag (on the `golift/unpackerr` image).

**Comment by davidnewhall** [comment]
A working beta version is available with even more bug fixes. Please try it out and let me know how it works out for you. https://github.com/davidnewhall/unpackerr/releases/tag/v0.7.2-beta7

On docker: `docker pull golift/unpackerr:0.7.2-beta7`
