### ISSUE TITLE
No extractable files found: Linux with all apps on one server/file system

### ISSUE THREAD

**Issue by SimonSR** [davidnewhall/unpackerr#48]
Hi,
I am having an issue, can't figure out what I'm doing wrong :) 

I am getting the error below:
```
Sep  7 13:31:16 debian-transmission unpackerr[4196]: 2020/09/07 13:31:16 [Sonarr] Updated (http://localhost:8989): 1 Items Queued
Sep  7 13:31:16 debian-transmission unpackerr[4196]: 2020/09/07 13:31:16 [Radarr] Updated (http://localhost:7878): 0 Items Queued
Sep  7 13:31:16 debian-transmission unpackerr[4196]: 2020/09/07 13:31:16 [Sonarr] Completed item still waiting: (edited out), no extractable files found at: /media/debian-transmission/Storage/Downloads/Completed/(edited out)
Sep  7 13:31:16 debian-transmission unpackerr[4196]: 2020/09/07 13:31:16 [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
```
My settings for unpackerr sonarr/radarr are:
```
[[sonarr]]
   url = "http://localhost:8989"
   api_key = "myapikey"
   path = "/media/debian-transmission/Storage/Downloads/Completed"

[[radarr]]
  url = "http://localhost:7878"
  api_key = "myapikey"
  path = "/media/debian-transmission/Storage/Downloads/Completed"
```
Please advice as to why I am an idiot :)
Thanks

**Comment by davidnewhall** [comment]
It looks like Sonarr has something in the queue with no name. What do you see in the Sonarr `activity` queue?

**Comment by davidnewhall** [comment]
Is there a `.rar` file in `/media/debian-transmission/Storage/Downloads/Completed/(edited out)` ?

**Comment by SimonSR** [comment]
Yes

**Comment by davidnewhall** [comment]
Is this running in a jail? a chroot? a docker container?

**Comment by SimonSR** [comment]
Installed this file: unpackerr_0.7.0-82_amd64.deb
All is running on same host

**Comment by SimonSR** [comment]
In ubuntu 20.04

**Comment by SimonSR** [comment]
ps aux | grep unpack
nobody      5889  0.0  0.2 1000136 8624 ?        Ssl  13:43   0:00 /usr/bin/unpackerr
debian-+    6384  0.0  0.0  20200   728 pts/0    S+   13:49   0:00 grep --color=auto unpack

**Comment by davidnewhall** [comment]
what `user` and `group` owns the files in `/media/debian-transmission/Storage/Downloads/Completed/` ?

**Comment by SimonSR** [comment]
debian-transmission owns as both user and groud

**Comment by davidnewhall** [comment]
Okay, try this.. edit `/lib/systemd/system/unpacker.service` and change the `User=` line to `User=debian-transmission`. You can also add `Group=debian-transmission` if you want. Then run `sudo systemctl daemon-reload` and `sudo systemctl restart unpackerr`

**Comment by SimonSR** [comment]
It worked, thank you :) Looking forward to it

**Comment by davidnewhall** [comment]
UPDATED: Unpackerr now uses a dedicated user in the systemd unit file and linux packages. The correct fix now days is to add the `unpackerr` user to the `debian-transmission` group and set the umask so the group can write.
