### ISSUE TITLE
Watched folder question

### ISSUE THREAD

**Issue by influx3k** [davidnewhall/unpackerr#49]
Hi, quick question, can you set a watched folder in Unpackerr to the same folder that the download client (in this case, Transmission) uses to download to?  I just didn't know if that could potentially cause problems because Unpackerr is looking at that folder anyways.  I've been thinking about adding that as a watched folder for items manually added to Transmission that have not been added by Radarr/Sonarr.  Thanks.

**Comment by davidnewhall** [comment]
I haven't used transmission enough to know for sure, but you'd want to set the download path to a folder other than your watched folder, then *move* the download into the watched folder after the download is done. 

If transmission creates a folder in the watched folder and begins pumping data into it, unpackerr will not work with that. It'll try to extract it, wont be able to, and wont look at it again..

**Comment by influx3k** [comment]
Sorry, I was talking about a watched folder in unpackerr, not in Transmission.  Transmission does have its own watch folder, but I'd like to set a watched folder in unpackerr to extract downloaded files that were manually added to Transmission and not downloaded through Radarr/Sonarr.  Was just wondering if that would work if the two folders were the same.

**Comment by davidnewhall** [comment]
I knew exactly what you were asking. Let me edit the answer to be more clear....

**Comment by influx3k** [comment]
Ok, thanks for getting back to me.

**Comment by influx3k** [comment]
> You'll want to set the download path [in transmission] to a folder other than your [unpackerr] watched folder, then _move_ the download into the watched folder after the download is done.

So Transmission has an "incomplete" folder where the file(s) are saves during the download and a "complete" folder where they are automatically moved to when finished.  Could the "complete" folder be a unapckerr watched folder?  Unpacker will be working in the folder for items downloaded by Radarr and Sonarr... but would that work for items manually added to Transmission and downloaded in the same way?

**Comment by davidnewhall** [comment]
I would generally say "yes" that should work, but once you mention radarr and sonarr operate from the same folder the answer becomes "probably not." That's because it'll end up trying (and probably successfully) to extract the items twice. You can at least try it, but there's nothing going to exclude radarr/sonarr items from the folder watcher routine. 

Maybe you should run it without sonarr/radarr integration and a watched folder only, and see how it works out for you.

**Comment by davidnewhall** [comment]
Please re-open this issue or make a new issue if I can help further!

**Comment by davidnewhall** [comment]
A working beta version is available with even more bug fixes. **Extracted files are now always moved back into the same folder as the compressed file they were extracted from.** Please try it out and let me know how it works out for you. https://github.com/davidnewhall/unpackerr/releases/tag/v0.7.2-beta7

On docker: `docker pull golift/unpackerr:0.7.2-beta7`
