### ISSUE TITLE
It doesnt work?

### ISSUE THREAD

**Issue by eihns** [davidnewhall/unpackerr#50]
I wonder if im doing something wrong or if this script is very limited.

Im running unraid (hotio/unpackerr)

Im using radarr and sonarr.

`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='unpackerr' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'UN_SONARR_0_URL'='http://192.168.86.103:8989' -e 'UN_SONARR_0_API_KEY'='893dceb9d3d24780a9de953910f6ee99' -e 'UN_RADARR_0_URL'='http://192.168.86.103:7878' -e 'UN_RADARR_0_API_KEY'='c457fead5f41479c8e2243f830ea3488' -e 'UN_RADARR_0_PATH'='/downloads/completed/Filme' -e 'UN_SONARR_0_PATH'='/downloads/completed/Serien' -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='002' -e 'ARGS'='' -e 'DEBUG'='no' -e 'UN_DEBUG'='false' -v '/mnt/cache/appdata/unpackerr':'/config':'rw' -v '/mnt/user/downloads/':'/downloads':'rw' -e DEBUG=yes --restart=unless-stopped -c=64 --network=filesharing 'hotio/unpackerr' 
`

It seems to work (start)
2020/09/27 13:53:10 [Radarr] Updated (http://radarr:7878): 4 Items Queued
2020/09/27 13:53:11 [Sonarr] Updated (http://Sonarr:8989): 1860 Items Queued
2020/09/27 13:53:11 [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

2020/09/27 13:53:11 [Sonarr] Updated (http://Sonarr:8989): 1860 Items Queued
2020/09/27 13:53:11 [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

2020/09/27 13:54:10 [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

But it doesnt do anything.

"/downloads" is for radarr, sonarr and unpackerr "/mnt/user/downloads" - so that should be correct.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-start-container: executing...

----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=99
PGID=100

2
TZ=Europe/Berlin
ARGS=

s
----------------------------------------------------------------------

Executing usermod...
Applying permissions to /config
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] 01-configure-app: executing...
No custom "unpackerr.conf" found. Using defaults.
[cont-init.d] 01-configure-app: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020/09/27 13:55:25 Unpackerr v0.7.0- Starting! (PID: 221) 2020-09-27 13:55:25.371954402 +0200 CEST m=+0.001036722
2020/09/27 13:55:25 ==> Startup Settings <==
2020/09/27 13:55:25 => Sonarr Config: 1 server: http://Sonarr:8989 @ /downloads (apikey: true, timeout: 10s)
2020/09/27 13:55:25 => Radarr Config: 1 server: http://radarr:7878 @ /downloads (apikey: true, timeout: 10s)
2020/09/27 13:55:25 => Lidarr Config: 1 server: (apikey: false, timeout: 10s)
2020/09/27 13:55:25 => Folder Config: 0 paths
2020/09/27 13:55:25 => Parallel: 1
2020/09/27 13:55:25 => Interval: 2m0s
2020/09/27 13:55:25 => Delete Delay: 5m0s
2020/09/27 13:55:25 => Start Delay: 1m0s
2020/09/27 13:55:25 => Retry Delay: 5m0s
2020/09/27 13:55:25 => Debug / Quiet: false / false
2020/09/27 13:55:25 => Log File: /config/app/unpackerr.log
2020/09/27 13:55:25 [Radarr] Updated (http://radarr:7878): 4 Items Queued
2020/09/27 13:55:26 [Sonarr] Updated (http://Sonarr:8989): 1861 Items Queued
2020/09/27 13:56:25 [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

2020/09/27 13:57:25 [Radarr] Updated (http://radarr:7878): 4 Items Queued
2020/09/27 13:57:25 [Radarr] Updated (http://radarr:7878): 4 Items Queued
2020/09/27 13:57:26 [Sonarr] Updated (http://Sonarr:8989): 1861 Items Queued
2020/09/27 13:57:26 [Unpackerr] Queue: [0 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
```

So im wondering sonarr is reporting "NAME No files found are eligible for import in /downloads/completed/Serien/NAME" does that count as "completed"? (https://github.com/davidnewhall/unpackerr When Unpackerr finds an item in Sonarr or Radarr or Lidarr the download location is checked for a .rar file. If an extractable archive exists, and Sonarr/Radarr/Lidarr has status=Completed from your download client Unpackerr will extract the file. Files are extracted to a temporary folder, and then moved back into the download location for Completed Download Handling to import them. When the item falls out of the (Radarr/Sonarr/Lidarr) queue, the extracted files are deleted.) 

1.) How should it ever become "completed" when its not unrared... do i miss something? :D

2.) And... Im mean, Why only check for "*.rar?" What about e.g. "*.r00"? 

3.) Would it be possible to remove .rars which cant be unrared?

I dont see how this should/could work?!

Im currently literally unraring 2000+ files manually :D If someone has an idea what im doing wrong, please help me...  (i hope it works and im just too stupid)

**Comment by TRaSH-** [comment]
Please don't tell me you're using this with a usenet program like nzbget or sabnzbd.
If you do then your last line is correct.

**Comment by eihns** [comment]
> Please don't tell me you're using this with a usenet program like nzbget or sabnzbd.
> If you do then your last line is correct.

Im using it with nzbget, in which i ofc disabled unraring. Im tryin to use another program/docker for unraring because nzbget fails to unrar rars inside a rar, or .01 rar files.

**Comment by TRaSH-** [comment]
To be honest I never seen rars in rars except for applications and games for a certain reason.

Verzonden met ProtonMail Mobile

-------- Oorspronkelijk bericht --------
Aan 27 sep. 2020 15:37, eihns schreef:

**Comment by eihns** [comment]
Try download german content, you get so much trash.

Also big problem is many files are .1 instead of .mkv....

**Comment by eihns** [comment]
OKay, ive got it working with the folder watch...

Can i make the suggestion that it also try to extract .01
2020/09/27 15:45:42 [Folder] Extraction Error: /downloads/completed/Serien/Akte.X.S05E20.German.WS.BDRip.x264-RIPLEY-xpost: unknown filetype: /downloads/completed/Serien/Akte.X.S05E20.German.WS.BDRip.x264-RIPLEY-xpost/r-aktex.s05e20-sd.r00

**Comment by TRaSH-** [comment]
Normally a rar always consist of a .rar file followed by the .rxx if yours don't have it it means it's borked and the people who made this pack know shit.
Personally I would put that release group on my shitlist

**Comment by eihns** [comment]
> Normally a rar always consist of a .rar file followed by the .rxx if yours don't have it it means it's borked and the people who made this pack know shit.
> Personally I would put that release group on my shitlist

You dont understand, our community in german got destroyed some years back, this crap is all we have.

I can understand english movies and series, but other ppl in my family not so i need to download german stuff.

1.) There are rars which include rars.
2.) there are rars where inside are .1 and .2 sometimes which just needs to be renamed to .mkv
3.) many imcomplete crap

**Comment by TRaSH-** [comment]
i know how rars in rars look like,
and if done correctly you also get a .rar inside the main rar pack. (let's say i know how files get upped to usenet)

if you get .1 .2 it's often because they got them double with the same name because of bad naming from the start.
so if you say the .1 .2 needs to be renamed to a .mkv  it means it doesn't need to be unpacked in the first place ? 

i've seen a nzbget script ones that does unpacking to a second stage.

i don't know if unpackarr does unrar in rars inside a rar.
i think ti should be possible if they where correctly done from start with a .rar to start with.

**Comment by eihns** [comment]
if you get .1 .2 it's often because they got them double with the same name because of bad naming from the start.
so if you say the .1 .2 needs to be renamed to a .mkv it means it doesn't need to be unpacked in the first place ?

Yes, its these releases which include the .bats "for safe renaming" and "run this in linux.sh" (;))

**Comment by TRaSH-** [comment]
The .bat file does the renaming correctly i presume ?
Wonder why they make it so complicated
because you can manage that much smarter with using a par/rar rename.

![image](https://user-images.githubusercontent.com/6155095/94367353-6ad4c200-00de-11eb-8a76-e6e7f814957c.png)

**Comment by eihns** [comment]
Most of the bats i see are not malicios, but im defeintly not running these... ;)

I guess they do it to make it harder for law enforcement... 

i tried all of the nzbget scripts, tehy are heavily outdated and remove "good" (bad) releases...

Does unpackerr delete releases which does not include any extractable things?

**Comment by davidnewhall** [comment]
> 1.) How should it ever become "completed" when its not unrared... do i miss something? :D

Yes, you missed that this app only works with torrents downloaders. Sonarr and Radarr handle those differently than NZB downloads.

> 2.) And... Im mean, Why only check for ".rar?" What about e.g. ".r00"?

If a `.rar` file is not present when the item reaches `Completed` then it will look for ` r.00` file. Code:
https://github.com/golift/xtractr/blob/master/files.go#L91-L93

> 3.) Would it be possible to remove .rars which cant be unrared?

Not by this application.
<hr>

It sounds like you want this app to do things it wasn't quite designed to do. I've had folks report success using the "folder watcher" feature in this app. You may want to try to incorporate that into your workflow, but I'm not sure how the NZB client handles moving completed downloads. If you can configure the download client to move the completed download folder into an "unpackerr watched" folder then you may be able to pull this off.

My NZB downloader unars for me. Curious: What have you found inside those downloads that you need to further extract? subs maybe?

**Comment by eihns** [comment]
> > 1.) How should it ever become "completed" when its not unrared... do i miss something? :D
> 
> Yes, you missed that this app only works with torrents downloaders. Sonarr and Radarr handle those differently than NZB downloads.
> 
> > 2.) And... Im mean, Why only check for ".rar?" What about e.g. ".r00"?
> 
> If a `.rar` file is not present when the item reaches `Completed` then it will look for ` .r00` file; [code](https://github.com/golift/xtractr/blob/master/files.go#L91-L93). But you also pasted this:
> 
> ```
> 2020/09/27 15:45:42 [Folder] Extraction Error: /downloads/completed/Serien/Name: unknown filetype: /downloads/completed/Serien/Name/Name.r00
> ```
> 
> ^ this is a [bug](https://github.com/golift/xtractr/blob/master/files.go#L104) I will fix soon.
> 
> > 3.) Would it be possible to remove .rars which cant be unrared?
> 
> Not by this application.
> 
> > Does this docker unrar rars inside a rar?
> 
> Yes.
> 
> > Does unpackerr delete releases which does not include any extractable things?
> 
> No, it wont delete anything unless it's successful (or has a bug).
> 
> It sounds like you want this app to do things it wasn't quite designed to do. I've had folks report success using the "folder watcher" feature in this app. You may want to try to incorporate that into your workflow, but I'm not sure how the NZB client handles moving completed downloads. If you can configure the download client to move the completed download folder into an "unpackerr watched" folder then you may be able to pull this off.
> 
> My NZB downloader unars for me. Curious: What have you found inside those downloads that you need to further extract? subs maybe?

The watch folder seems to work.  You said it should look for r00... which it doesnt do..

**Comment by davidnewhall** [comment]
> Currently nzbget is just placing everything in /downloads, i want unpackerr to watch that folder and extract if neccessary (and rars inside rars). Should be doable?

You should not download into the unpackerr watched folder. It's designed to have folders moved into the watched folder. ie. this is the expected workflow:
```
mkdir movie.folder  
touch movie.folder/file.rar
mv movie.folder /unpackerr/watched.folder
```

If you download directly to the watch folder many things will be missed.

> Why you cant add a delete failed .rars option

Because the chance of that failure happening due to this software is higher than the chance of it happening because of a bad download.

> isnt this also something usefull for torrents? Dont you get sometimes incomplete or otherwise not extractable files?

no and no. That's an nzb problem only.

**Comment by davidnewhall** [comment]
This should be fixed in the next release. If you want to try it now, use the `bugs` tag on the `golift/unpackerr` Docker image.

**Comment by davidnewhall** [comment]
A working beta version is available with even more bug fixes. Please try it out and let me know how it works out for you. https://github.com/davidnewhall/unpackerr/releases/tag/v0.7.2-beta7

On docker: `docker pull golift/unpackerr:0.7.2-beta7`

I also noticed I previously said:
> You should not download into the unpackerr watched folder.

I still stand by that, but for the most part, this may be fine. It will be fine as long as a download does not stall. Unpackerr will attempt to extract things in the watched folder once they stop being written to. If it attempts to unpack early it will just fail and the item will remain unpacked.
