### ISSUE TITLE
Change unpacked file permission

### ISSUE THREAD

**Issue by bounty1342** [davidnewhall/unpackerr#54]
Is there a way to change the permission of the files just unpacked ?

**Comment by davidnewhall** [comment]
Not right now. What's the problem? I generally recommend running this as the same user as your download and the arr apps. Works best when they all have the same permissions.

**Comment by JakobLund** [comment]
I am currently unable to delete extracted files from my windows computer, which is what I normally use to clean files from my server. Is there a way to fix my issue?

**Comment by davidnewhall** [comment]
Yes, but I don't have enough information to tell you.

**Comment by JakobLund** [comment]
*arr doesn't move the files in my case, since I need the files to seed. This is why I manually go through folders that are not needed anymore.

**Comment by davidnewhall** [comment]
You don't seed extracted files.

**Comment by JakobLund** [comment]
Not all files from a torrent is in .rar format and *arr is either move/copy ALL kinds of video files. It is not a solution for me to let them get moved since the other 95% of my torrents can't seed.

**Comment by davidnewhall** [comment]
What can I do to make this work for you?

**Comment by JakobLund** [comment]
Would it be possible to write files with a custom mask? This is possible with deluge by using UMask=xxx in the service file. I tried the same method with unpackerr but with no result

**Comment by davidnewhall** [comment]
I'll have to look into that. It's [currently hard coded](https://github.com/golift/xtractr/blob/master/rar.go#L43-L50) to `0755`, and changing that looks like it'll require an interface update to the library.

**Comment by JakobLund** [comment]
I'm a little confused by your questions but I'll try and answer them.
I am able to delete all rar files inside the folder but it is only the extracted file which i am unable to delete. Overriding the mask of the extracted file would solve it.

**Comment by jawilson** [comment]
In the event someone else comes across this in the future and the linked PR's aren't obvious, you can now set the environment variables `UN_FILE_MODE` (default `0644`) and `UN_DIR_MODE` (default `0755`) to control the file/folder modes which are part of the [global settings](https://unpackerr.zip/docs/install/configuration#global-settings).
