### ISSUE TITLE
Unpackerr Waiting

### ISSUE THREAD

**Issue by Kalembang** [davidnewhall/unpackerr#55]
It appears that unpackerr was able to find the rar files, but it will not extract anything. 
The log file states:
2020/10/14 04:30:02 [Unpackerr] Queue: [24 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]
It seems to just continuously keep the files in the waiting queue. Confirmed the files are 100% downloaded in Sonarr

**Comment by Kalembang** [comment]
I confirmed the /downloads is the same path as sonarr, and radarr
Running in Unraid Docker.
Downloads Location: /mnt/user/Media/Torrents/
Sonarr Download Path: /mnt/user/Media/Torrents/

**Comment by Kalembang** [comment]
I confirmed the /downloads is the same path as sonarr, and radarr
Running in Unraid Docker.
Downloads Location: /mnt/user/Media/Torrents/
Sonarr Download Path: /mnt/user/Media/Torrents/
Also have tried Sonarr Download Path: /mnt/user/Media/Torrents/Completed

Sonarr: Configured path (/mnt/user/Media/Torrents/The.Simpsons.S29E05.iNTERNAL.MULTi.1080p.WEB.H264-CiELOS, err: stat /mnt/user/Media/Torrents/The.Simpsons.S29E05.iNTERNAL.MULTi.1080p.WEB.H264-CiELOS: no such file or directory) does not exist; trying path found in status message: /data/Completed/The.Simpsons.S29E05.iNTERNAL.MULTi.1080p.WEB.H264-CiELOS
2020/10/14 05:00:04.910338 handlers.go:117: [Sonarr] Waiting for Start Delay: The.Simpsons.S29E05.iNTERNAL.MULTi.1080p.WEB.H264-CiELOS (1m0s remains)
2020/10/14 05:00:04.910368 sonarr.go:83: [DEBUG] Sonarr (Removed): Completed (torrent:100%): The.Simpsons.S29E05.iNTERNAL.MULTi.1080p.WEB.H264-CiELOS (Ep: Grampy, Can Ya Hear Me)

**Comment by davidnewhall** [comment]
Turn on debug.

**Comment by Kalembang** [comment]
Set debug log to true which is where I pulled that info from. Is there something specific that you need from the debug log?

**Comment by davidnewhall** [comment]
All you've provided are two logs line. One of them says it looked in two locations and couldn't find your files. Short of any other logs lines, it seems the issue is with what you've set `path` to, or what folders you've mapped into the container. You haven't told me any of that so I can only guess.

**Comment by Kalembang** [comment]
[Log.txt](https://github.com/davidnewhall/unpackerr/files/5390147/Log.txt)

Ohhh! I use binhex-sonarr and binhex-radarr which does use /data/ not /downloads/
So, to use your docker I would have to switch to my radarr/sonarr to one that uses /data/?

**Comment by davidnewhall** [comment]
You just need to set the `path` variables correctly. Try `/data/Completed` and mount your files (`/mnt/user/Media/Torrents/`) in as `/data` instead of `/downloads`.

**Comment by Kalembang** [comment]
@davidnewhall You sir are a godsend!! You saved me so much time and frustration! THANK YOU THANK YOU THANK YOU!

**Comment by davidnewhall** [comment]
A working beta version is available. Please try it out and let me know how it works out for you. https://github.com/davidnewhall/unpackerr/releases/tag/v0.7.2-beta7

On docker: `docker pull golift/unpackerr:0.7.2-beta7`
