### ISSUE TITLE
No support for armv7l (Raspberry pi 4)

### ISSUE THREAD

**Issue by JakobLund** [davidnewhall/unpackerr#57]
Currently there is no support for the armv7l architecture. Would this be possible to support?

**Comment by davidnewhall** [comment]
I'm not immediately familiar with `armv7l`. None of the existing arm builds work? What error do they produce?

**Comment by JakobLund** [comment]
The error happens when running the install script, but upon further inspection it seems that armv7l is not checked for. I assume that armhf would work too. Trying it out now.

**Comment by JakobLund** [comment]
This is the error btw:
 ==> [ERROR] Unknown Architecture: armv7l
 ==> Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
 ==> Please report this, along with the above OS details:
     https://github.com/davidnewhall/unpackerr/issues/new

**Comment by davidnewhall** [comment]
Got it! Yes, please let me know if the armhf build works for you and I'll update the install script.

**Comment by JakobLund** [comment]
I managed to install it with armv7l and it is now running as a service. However, I do not have any data to test it with at this moment but I assume that would work fine too 👍 

Great job on this application. I am sure it will provide a great use for me when I have it fully set-up
