### ISSUE TITLE
 ==> [ERROR] Unknown Architecture: armv7l

### ISSUE THREAD

**Issue by springjools** [davidnewhall/unpackerr#58]
==> [ERROR] Unknown Architecture: armv7l
 ==> Linux jovian 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
 ==> Please report this, along with the above OS details:
     https://github.com/davidnewhall/unpackerr/issues/new

**Comment by davidnewhall** [comment]
Thanks! I'll get the install script fixed soon! dup: #57

**Comment by davidnewhall** [comment]
Can you show me the curl / bash command you used to invoke this and get this error message? I'm actually confused because the script does have `*armv7*` in it as an identifier, but it seems like the glob match in your bash is not working. Can you also show me the output of `bash --version` ? Thanks!

**Comment by springjools** [comment]
Yes, I used this (from readme):
wget -qO- https://raw.githubusercontent.com/davidnewhall/unpackerr/master/scripts/install.sh | sudo sh

And:

bash --version
GNU bash, version 5.0.16(1)-release (arm-unknown-linux-gnueabihf)

Maybe that's the reason. I'm on bullseye/sid on debian 10 for raspberry

**Comment by davidnewhall** [comment]
ooohh.. I think that's the problem. The readme says `sh` but the script is for `bash`. 

Can you see if this works?
```
wget -qO- https://raw.githubusercontent.com/davidnewhall/unpackerr/master/scripts/install.sh | sudo bash
```

**Comment by springjools** [comment]
Yes, it works. Thanks. Sorry, I should have understood that fix myself.

**Comment by davidnewhall** [comment]
You're the second person to report this exact same issue. Definitely a _me_ problem and the readme is _wrong_. I'm updating it now. Thank you for your feedback!
