### ISSUE TITLE
Not unrar if .rar are in folder into an another

### ISSUE THREAD

**Issue by fana13** [davidnewhall/unpackerr#60]
Hi, 

I'm on Debian 10 with last unpackerr version.
My conf it's like this
```
# TV Series / Episodes
[[sonarr]]
   url = "http://127.0.0.1:8989"
   api_key = "myapikey"
   # File system path where downloaded Sonarr items are located.
   path = "/media/Data/torrents/Postprocess"
# Default protocols is torrents. Alternative: "torrents,usenet"
   protocols = "torrents"

# Movies
[[radarr]]
  url = "http://127.0.0.1:7878"
  api_key = "myapikey"
  # File system path where downloaded Radarr items are located.
  path = "/media/Data/torrents/Postprocess"
# Default protocols is torrents. Alternative: "torrents,usenet"
   protocols = "torrents"

# Music
[[lidarr]]
  url = "http://127.0.0.1:8686"
  api_key = "myapikey"
  # File system path where downloaded Lidarr items are located.
  path = "/media/Data/torrents/Postprocess"
# Default protocols is torrents. Alternative: "torrents,usenet"
   protocols = "torrents"
# folder will be decompressed. This has *nothing* to do with Sonarr/Lidarr/Radarr.
[[folder]]
  path = "/media/Data/torrents/Postprocess"
  # Delete extracted items this long after extraction. Set to 0 to disable. Uses Go Duration.
  delete_after = "10m"
  # Delete original items after successful extraction? true/false, no quotes. Honors delete_after.
  delete_original = true
  # Move extracted files into original folder? If false, files go into an _unpacked folder.
  move_back = false
```
I've modify the unpackerr.service to add user and group with good permissions and reload it

Now to explain my issue, have got a complete season in Postprocess folder, into this folder i've got a folder for each episode.
Into each episode folder have got rar files to extract.
So structure is like /Postprocess/Season1/Episode1
In this configuration unpackerr doesn't unrar anything, here is the log file
[unpackerr.log](https://github.com/davidnewhall/unpackerr/files/5568107/unpackerr.log)

But if i move manually each episode on Postprocess root, unpackerr do the job !

Anyway I can't choose another structure...
Sonnar download complete season, move it into Postprocess folder and unpackerr should working alone, no ?

Thanks :)

**Comment by davidnewhall** [comment]
I see where you moved the season folders into the watched extraction folder. It seems to have extracted all of those. Does the "problem" you describe appear in the log file? If so, what time stamp should I look for? What is the name of the folder that did not extract? Did that folder have other folders in it? ..and those folders had the extractable items?

I think, as it is right now, it will only extract files 1 level deep. Going deeper levels gets a bit more complicated as you have to avoid overwriting things. I can look into it though.

**Comment by fana13** [comment]
Before 16:30 structure folders is /Postprocess/Season1/Episode1 /Episode2 etc...
.rar files are in folders Episode1 Episode2 etc...
In this configuration unpackerr unrar nothing.
After 16:30 i moved manually folder by supress the first folder, the Season1 folder which contain each folder episode.
Structure folders after that is /Postprocess/Episode1 /Episode2 etc...
In this configuration unpackerr unrar all files correctly.

Thanks for your time, unpackerr is really good

**Comment by davidnewhall** [comment]
So, when you copied the multi-level folder into the watched folder, unpackerr didn't even acknowledge it? There was just nothing in the log for that action?

**Comment by davidnewhall** [comment]
You've configured this all incorrectly. The `Folder` feature should not be the same path as your *arr apps. It's unrelated and not meant to be used in tandem with those. That will undoubtedly cause undesired behavior.

There is a typo in the config file. The Proto needs to be `torrent`, and this is why none of the arr triggers are working. Disable/remove the folder config and fix the typo.

**Comment by fana13** [comment]
Ok i understand my mistake.
Thank for your help

**Comment by davidnewhall** [comment]
A working beta version is available. Please try it out and let me know how it works out for you. https://github.com/davidnewhall/unpackerr/releases/tag/v0.7.2-beta7

On docker: `docker pull golift/unpackerr:0.7.2-beta7`
