### ISSUE TITLE
proposal: log rotation

### ISSUE THREAD

**Issue by napei** [davidnewhall/unpackerr#68]
If possible could log rotation or truncation be implemented?

![image](https://user-images.githubusercontent.com/8946502/100177953-1f486400-2f27-11eb-943a-53c9fcb5317e.png)

Perhaps similar to how sonarr handles logs? Limiting to 1MB and adding multiple files etc..

Unless you use sublime text you have no hope of opening a 334 MB log file

Admittedly I left debug logging on, but still raises a point.

![image](https://user-images.githubusercontent.com/8946502/100178042-4868f480-2f27-11eb-9c85-a97461e7e3f8.png)

**Comment by davidnewhall** [comment]
Second request for this today, I guess so.

**Comment by austinwbest** [comment]
hahaha, good thought :)

**Comment by davidnewhall** [comment]
This is added. Default is 10 files at 10 Mb. Configurable.

**Comment by davidnewhall** [comment]
A working beta version is available now that should resolve this issue. Please try it out and let me know how it works out for you. https://github.com/davidnewhall/unpackerr/releases/tag/v0.7.2-beta7

On docker: `docker pull golift/unpackerr:0.7.2-beta7`

**Comment by napei** [comment]
@davidnewhall appears to work. I added several MB of rubbish to the file to force it and after restarting the application it correctly made a new log file. (ignore its size it's just so it's `> 10MB`)

![image](https://user-images.githubusercontent.com/8946502/100415097-6c673a00-30cf-11eb-8415-787cd9ef2caf.png)

**Comment by davidnewhall** [comment]
If you turn on debug the rotation size will be 20Mb (unless you change it in the config). The app prints out the log file info on startup including rotation size/file count. I've already had one report from a windows user (@austinwbest) that it's not working correctly, but he also has another weird issue where the app just stops printing logs. Mine rotate the first log, but the second hasn't reached 20Mb yet, so will find out soon if it's working correctly for me.

**Comment by napei** [comment]
Just an update. All appears to be working.

![image](https://user-images.githubusercontent.com/8946502/101971148-4622cc00-3c83-11eb-993e-c38e3e1a3e95.png)

**Comment by davidnewhall** [comment]
Excellent!
