### ISSUE TITLE
Requests: Windows Installer Package && Minimize to Tray || Windows Service

### ISSUE THREAD

**Issue by davidnewhall** [davidnewhall/unpackerr#71]
Look into Creating a windows installer package.
- From @napei ([here](https://github.com/davidnewhall/unpackerr/issues/41#issuecomment-669010993)):
    - Check out https://github.com/mh-cbon/go-msi for building msi packages (which I think exists in github actions too), and there are examples for writing a windows service here
    - There is also https://github.com/judwhite/go-svc for writing services. I personally haven't done this, but I think that these options are pretty baseline for what people do.
 - Figure out how much work a minimize-to-tray option vs a windows service option is.

Done:
  - ~Put the example config file into the zip file with the windows binary.~
  - ~Windows section to readme.~
  - ~Discord link to readme.~
  - ~Repo badges to readme.~ Not doing this now.

If you have requests, file in below.

**Comment by napei** [comment]
Change the default configuration directory to `%userprofile%\.unpackerr` for windows, and `~\.unpackerr` for linux. This is more inline with most applications that I've used that follow this dot-directory style, with it being in the user's home path.

**Comment by davidnewhall** [comment]
> Change the default configuration directory to %userprofile%\.unpackerr for windows, and ~\.unpackerr for linux

This makes sense on windows and maybe even macOS, but for Linux the packages create an `unpackerr` user and group and systemd runs the application as this combo. This allows a user to run their apps as different users, but assign file permissions and group membership to allow access among apps. This is the most common way I've seen to run a daemon on Linux.

**Comment by austinwbest** [comment]
> Change the default configuration directory to `%userprofile%\.unpackerr` for windows, and `~\.unpackerr` for linux. This is more inline with most applications that I've used that follow this dot-directory style, with it being in the user's home path.
> 

I would agree excepting that the main purpose is for arr apps, all of which are programdata on windows

**Comment by davidnewhall** [comment]
I'm adding a new setup that looks in a number of places for a config file. All of the above are in the paths list.

**Comment by davidnewhall** [comment]
A tray icon is forthcoming.

**Comment by davidnewhall** [comment]
So I've got a tray icon for windows and macOS. It's pretty minimal but it opens the door to more things. I'm unlikely to create an `msi` installer any time soon. It requires building on Windows, and I'm not ready for that can of worms. I did add some better defaults for the GUI apps for config and log files. Next release will have these features.
