### ISSUE TITLE
Feature request: Additional webhook functionality

### ISSUE THREAD

**Issue by BRTPOB** [davidnewhall/unpackerr#73]
As requested, here's the GitHub issue for Telegram functionality with the webhooks portion of Unpackerr.

EDIT (by @davidnewhall): Also add generic web hooks for other applications such as Discord. - Dec 27

**Comment by davidnewhall** [comment]
resources:
https://github.com/Radarr/Radarr/tree/develop/src/NzbDrone.Core/Notifications/Telegram
https://telegram.org/apps#source-code
https://core.telegram.org/bots

- Create a pluggable webhook interface that allows changing data structures based on URL or URL path parameter.

**Comment by davidnewhall** [comment]
@BRTPOB honestly, this looks like a lot more setup than I think I want in Unpackerr. I can't find any simple web hook functionality for telegram. It seems like all "conversations" require an interaction. In other words, I can't figure out how to send a message to a user without that message first sending a message to Unpackerr. I do not want inputs into Unpackerr like this.

If you can show me a way to send telegram messages without an interactive bot, I'd reconsider quickly.

**Comment by davidnewhall** [comment]
The latest beta adds the ability to pass in your own custom HTTP POST template. If you [or anyone] can figure out how to send a webhook message to telegram, I can help you make a template that works in Unpackerr. I will keep looking into this; I think it's possible.
