### ISSUE TITLE
Extraction Error: invalid cross-device link

### ISSUE THREAD

**Issue by dunamos** [davidnewhall/unpackerr#76]
Hello, 

I'm trying to use Unpackerr with sonarr and radarr. 
It detects well the two *arr instances, detects when a .rar is present, but does not achieve to extract this archive, I have the error in wrote in the title. 

I have a ubuntu server on version 20.04 LTS, all the app are in docker. 
I'm also using mergerfs to merge two disks together. And my downloads folder is in the mergerfs array. I have no problem with it in any docker I have. But seeing the error I get using unpackerr, maybe its coming from there ? 

If you need more info or anything please ask.

**Comment by davidnewhall** [comment]
Please give me full log lines. `invalid cross-device link` is simply not showing me enough data to know what operation triggered the error.

**Comment by dunamos** [comment]
`2020/12/10 10:30:29 Extraction Started: B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ, items in queue: 0
2020/12/10 10:30:29 [Unpackerr] Queue: [63 waiting] [0 queued] [1 extracting] [4 extracted] [0 imported] [0 failed] [0 deleted]
2020/12/10 10:30:29 [Unpackerr] Totals: [76 restarted] [1 finished] [164|164 webhooks] [0 stacks]
2020/12/10 10:30:29 Error: Renaming Temp File: /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred/_unpackerred.biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264-subs.rar.txt to /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ/Subs/_unpackerred.biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264-subs.rar.txt: rename /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred/_unpackerred.biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264-subs.rar.txt /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ/Subs/_unpackerred.biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264-subs.rar.txt: invalid cross-device link
2020/12/10 10:30:29 Error: Renaming Temp File: /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.idx to /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ/Subs/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.idx: rename /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.idx /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ/Subs/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.idx: invalid cross-device link
2020/12/10 10:30:29 Error: Renaming Temp File: /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.rar to /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ/Subs/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.rar: rename /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.rar /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ/Subs/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.rar: invalid cross-device link
2020/12/10 10:30:29 Error: Renaming Temp File: /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.sub to /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ/Subs/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.sub: rename /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.sub /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ/Subs/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.sub: invalid cross-device link
2020/12/10 10:30:29 Deleted (recursively): /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred
2020/12/10 10:30:29 Extraction Error: B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ: rename /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ_unpackerred/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.sub /downloads/B-Movie.Lust.and.Sound.In.West-Berlin.1979-1989.2015.1080p.BluRay.x264-BiQ/Subs/biq-b-movie.lust.and.sound.in.west-berlin.1979-1989.2015.1080p.bluray.x264.sub: invalid cross-device link`

**Comment by davidnewhall** [comment]
Unpackerr made a new folder in `/downloads/`, unpacked things into it, and then tried to `rename` those things back to the original folder inside `/downloads/`. This is very much a problem being produced by the file system, that for most configurations, never happens.

If you need this fixed in unpackerr, it will take me some time to do, but it can be done.

The alternative is to figure out if you can tune mergerfs (I know nothing about it, sorry), to allow `rename` on the filesystem, or at least in the `/downloads/` folder. It's basically treating every folder (at least in `/downloads`) as an independent file system. It may be that this fs just does not allow rename. I'm not sure.

Please let me/the Internet know what you figure out, and if you need me to build a workaround for this. The problem with the workaround is that it will use `copy` instead of `rename` and if your *arr app tries to import before the copy is finished, it may import an incomplete file. If you have your *arr apps set to use `hard links` you wont have this race condition. Just things to consider and make sure you set correctly if we go this route.

**Comment by dunamos** [comment]
Thanks for your answer, it directed me to the right tracks. 
I found the following indications on mergerfs github : https://github.com/trapexit/mergerfs#rename--link
I had to change a flag in my fstab, now its working.
It seems to be more of a workaround than the proper way to handle unpackerr's rename but its working for now. 
Thanks :)

**Comment by davidnewhall** [comment]
I'll make this work in the next release, but it may not be for a few weeks to a few months. I'm glad you found a workaround to get you unblocked! I'll leave this open and comment again when a fix is ready for you.

**Comment by maxi1134** [comment]
Hi there!

Which flag did you had to use exactly on that page?

I am encountering this message as well while using Mergerfs.
Sorry for the bad English, it is my third language.
Merci!

**Comment by davidnewhall** [comment]
@maxi1134 Try the latest beta: https://github.com/davidnewhall/unpackerr/releases/tag/v0.8.0-beta3

This release includes a `copy` fallback when `move` does not work.

**Comment by maxi1134** [comment]
Seems to work!

Thanks a lot!

**Comment by davidnewhall** [comment]
Sweet! Please let me know if you run into any problems so I can fix them before that beta goes not-beta.
