### ISSUE TITLE
Unpackerr is now extracting downloads that aren't initiated by Radarr or Sonarr

### ISSUE THREAD

**Issue by influx3k** [davidnewhall/unpackerr#79]
I recently noticed that Unpackerr is now extracting downloads that aren't initiated by Radarr or Sonarr.  Sometimes I will manually download something outside of Sonarr or Radarr and Unpackerr is automatically extracting it.  I never set up a watch folder in the config file for fear of it interfering with a download that was initiated by Radarr/Sonarr, since the download folder is the same in either scenario (which it would extract anyways). So I guess this isn't a problem per se, but just not expected.  Was the a recent change in functionality?  Is Unpackerr supposed to be doing that?

Using Transmission 3.00, Radarr 3.0.1.4259 and Sonarr 3.0.4.1026.

Edit: Could this be due to using Radarr and Sonarr v3?

**Comment by davidnewhall** [comment]
Unpackerr only considers files from an *arr app for extraction. The only way it'll extract something that did not come from sonarr/radarr is if that _something_ is in a folder that Sonarr or Radarr are using for a download. Or, if you configure a watched folder.

The v3 apps work fine. They still have the old v2 endpoints that unpackerr uses. The next version of unpackerr probably won't support v2 sonarr/radarr......

The logs should tell you why it extracted something you didn't expect it to. If you can share those, we can figure it out. Feel free to find me on Discord if you'd rather exchange data privately.

**Comment by davidnewhall** [comment]
We found that Sonarr and Radarr are auto-adding things from Transmissions. Thanks for working with me to figure it out!
