### ISSUE TITLE
Add discord specific webhook

### ISSUE THREAD

**Issue by napei** [davidnewhall/unpackerr#82]
I use discord webhooks, but every other application I use has schemas for discord that can talk directly to the webhook. I don't really want to sign up for another site (discordnotifier), invite bots, and all that. And this pattern would make it a bit easier to implement others like slack, telegram, etc... 

This isn't all that challenging either, as the data unpackerr needs to send is relatively basic.

https://discord.com/developers/docs/resources/webhook

This is the same as the arr apps, with a discord specific webhook trigger. There would be a config option for `discord` under webhooks or something like that.

Happy to open a PR for this as it's a side issue and not of major importance.

**Comment by davidnewhall** [comment]
I've been putting a lot of time into the [discordnotifier-client application](http://github.com/Go-Lift-TV/discordnotifier-client), but will get back to unpackerr to add these new features soon. Going to combine this with #73.
