### ISSUE TITLE
Folders do not work in Docker: fsnotify fails. Create alternative?

### ISSUE THREAD

**Issue by CptanPanic** [davidnewhall/unpackerr#85]
I am using unpackerr docker version, with a config file. I have set a Folder option, and see it in the start of the log, that it is watching the directory, but I currently have a subfolder in that folder that has some zip files, and it doesn't seem to be doing anything with it. If I look in the logs, I see the periodic checking of Sonarr/Radarr, but it never says anything again about Folder. What am I missing?

**Comment by davidnewhall** [comment]
> What am I missing?

Not sure, please share the config.

**Comment by CptanPanic** [comment]
> > What am I missing?
> 
> Not sure, please share the config.

```
[[folder]]
## Windows paths must use two backslashes: "C:\\Some\\Folder\\To\\Watch"
  path = "/mnt/media/downloads/torrents/qbittorrent/magazines"
## Delete extracted or original files this long after extraction. Set to 0 to disable all deletes. Uses Go Duration.
  delete_after = "0"
## Delete extracted files after successful extraction? true/false, no quotes. Honors delete_after.
  delete_files = false
## Delete original items after successful extraction? true/false, no quotes. Honors delete_after.
  delete_original = false
## Move extracted files into original folder? If false, files go into an _unpackerred folder.
  move_back = false
```

```
docker logs unpackerr | grep Folder
2021/01/15 18:39:13  => Folder Config: 1 path: /mnt/media/downloads/torrents/qbittorrent/magazines (delete after:0s, delete orig:false, move back:false, event buffer:20000)
2021/01/15 18:39:13 [Folder] Watching: /mnt/media/downloads/torrents/qbittorrent/magazines
```

**Comment by davidnewhall** [comment]
It can't watch folders on network volumes. It uses fsnotify, which wont work across a network.

**Comment by CptanPanic** [comment]
> It can't watch folders on network volumes. It uses fsnotify, which wont work across a network.
> 
> EDIT: Recommend running this on the same system that holds the real file system with the files.

Ah that is it then. Thanks.

**Comment by CptanPanic** [comment]
Actually that didn't work either, maybe it  fsnotify doesn't work inside a docker container? I am on Linux, and am mapping a docker volume directory inside container to a local directory on server. But am not getting any action from unpackerr

**Comment by davidnewhall** [comment]
I intend to test this, just haven't had time.

Can you show me the docker command that starts your container?

**Comment by CptanPanic** [comment]
> I intend to test this, just haven't had time.
> 
> Can you show me the docker command that starts your container?


docker run -d  -v /home/downloads:/downloads  --restart unless-stopped --name unpackerr -v /home/unpackerr/unpackerr.conf:/etc/unpackerr/unpackerr.conf golift/unpackerr

**Comment by davidnewhall** [comment]
I finally tested this. It does not work unless the docker container and the host use the same file system. That's almost never how you run a docker container, so this feature almost certainly does not work in Docker. :(

Many other folks complain about the same thing here: https://github.com/fsnotify/fsnotify/issues/292 - for reference, this link goes to the glang `fsnotify` library which Unpackerr uses. This is an unfortunate limitation in how Docker daemon translates file systems. The file change notifications never make it through to the Docker container. 

I'm afraid there is no fix for this with the current code.

I could make a web server in Unpackerr and give you a way to `POST` extraction triggers. I do not like this idea personally (more code overhead), but if you think you'd make use of it, let me know and we can discuss more if it meets your needs.

**Comment by davidnewhall** [comment]
TODO: add folder-polling interval-based mechanism so Docker users may use the `Folder` feature in Unpackerr.

**Comment by davidnewhall** [comment]
The latest release includes support for polling folders in Docker Please give it a try and let me know your thoughts!

`docker pull golift/unpackerr:latest`

**Comment by CptanPanic** [comment]
So I tried this and have a few thoughts/issues
1. So this doesn't work if the watched folder is a mounted cifs drive.
2. If I config watched folder to be on docker host, it does pickup changes, but I get an error. Any ideas?
```
2021/03/24 14:03:38.947074 folder.go:244: [Folder] Extraction Started: /data/downloads/test2, items in queue: 0
2021/03/24 14:03:38.947183 queue.go:206: [DEBUG] Extracting File: /data/downloads/test2/elm0521a.zip to /data/downloads/test2_unpackerred
2021/03/24 14:03:38.966749 queue.go:206: [DEBUG] Extracting File: /data/downloads/test2_unpackerred/elm0521l.rar to /data/downloads/test2_unpackerred
2021/03/24 14:03:39.577749 files.go:186: Deleted (recursively): /data/downloads/test2_unpackerred
2021/03/24 14:03:39.577815 folder.go:248: [Folder] Extraction Error: /data/downloads/test2: copying io: open /data/downloads/test2_unpackerred/elm0521l.r00: no such file or directory
```

**Comment by davidnewhall** [comment]
> So this doesn't work if the watched folder is a mounted cifs drive.

CIFS mounted and passed into Docker. You really go the extra mile to break things. :) I have no idea about this, the code I'm using polls folders so I would expect this to work just the same. I'll try to test it myself.

>  but I get an error

I know where that error is, but I've never seen it come up. It looks like you're missing some of your archive. There should probably be more zip files with more rar files in them. Is unpackerr extracting them out of order, or are there missing files?

**Comment by davidnewhall** [comment]
Please try the new beta release. I think it solves all these problems. 🤞 If you're not running in Docker, add this to your config to turn on folder-polling. **Do not add it inside a `[[folder]]` block**; it's separate.
```ini
[folders]
interval = "5s"
```

If you are running in Docker then polling should be automatic @ `1s`. You can tune it with `-e UN_FOLDERS_INTERVAL=5s`. 

If polling CIFS in Docker is what _does not work_, then I may have no way to fix that if this doesn't do it.

`docker pull golift/unpackerr:0.9.2-beta1` or https://github.com/davidnewhall/unpackerr/releases/tag/v0.9.2-beta1

**Comment by CptanPanic** [comment]
@davidnewhall unfortunately it didn't work. This case is complicated, as the files come as a set of zip files, and inside each zip is a corresponding rar file. (rar, r01, r02, ...)  I can't tell for sure since it deletes the directory after it fails, but could it be that it is only unzipping the first file, and trying to unrar then without unzipping everything first?

**Comment by davidnewhall** [comment]
Turn on debug, do it again, and send me the output please.

**Comment by davidnewhall** [comment]
I specifically re-wrote half the extraction code to deal with the use case you've described, so I need to see why it failed for you while it works for me.  I am familiar with rar sets being zipped. I don't know why, but I've seen it plenty of times and I know what you've got there. This should work. Make sure you use that beta tag I provided, and please send me the output with debug turned on. 

- Rewrite to support extraction in the correct order: https://github.com/golift/xtractr/pull/5

**Comment by CptanPanic** [comment]
@davidnewhall thanks, so I found a problem whereas I wasn't actually running the beta image, was just pulling beta image, but latest was being run. I was able to test on local and cifs folders, and everything is working great. Thanks.

**Comment by davidnewhall** [comment]
Yay! Thank you for the update! I'll cut a new release soon (I was waiting for your confirmation).
