### ISSUE TITLE
How to check if unpackerr works?

### ISSUE THREAD

**Issue by paubala** [davidnewhall/unpackerr#87]
Hi all,

I'm a complete noob, slowly learning my ropes around Linux, docker, etc.

I installed unpackerr because I had a couple of releases failing to import because they were multipart .rar. However, I don't normally encounter .rar in my indexers. How can I check if unpackerr works? Anyone has a go-to release I can try? Or some keywords I can try?

**Comment by davidnewhall** [comment]
Great question! Wish I had a better answer. Download stuff and watch the unpackerr output/logs.

**Comment by plsharevme** [comment]
today i also 1st time use unpackerr , after downloads the rar , wait for while, it auto unrar > import > delete unrar files 

Well done. perfect !!

**Comment by paubala** [comment]
> today i also 1st time use unpackerr , after downloads the rar , wait for while, it auto unrar > import > delete unrar files 
> 
> 
> 
> Well done. perfect !!

Can you point me to an indexer or release or way to search for one that uses RAR? My indexers dont usually use rar but theres the odd release every now and then.

**Comment by davidnewhall** [comment]
Still haven't found anything? It's pretty hard for others to point you to compressed releases, especially if your tracker doesn't have many. I suggest getting a bunch of things. Good chance 1 will be compressed.
