### ISSUE TITLE
install error on Ubuntu 20.04

### ISSUE THREAD

**Issue by Mitnick84** [davidnewhall/unpackerr#88]
Hello, i tried to install but i get this error on my Ubuntu Server:

(1:675)# wget -qO- https://golift.io/unpackerr/raw/master/scripts/install.sh | sudo bash
<-------------------------------------------------->
 ==> Downloading: https://github.com/davidnewhall/unpackerr/releases/download/v0.7.2/unpackerr-0.7.2-246.x86_64.rpm
 ==> To Location: /tmp/unpackerr-0.7.2-246.x86_64.rpm
 ==> Downloaded. Installing the package!
 ==> Executing: rpm -Uvh /tmp/unpackerr-0.7.2-246.x86_64.rpm
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
error: Failed dependencies:
        /bin/sh is needed by unpackerr-0.7.2-246.x86_64
<-------------------------------------------------->

(1:674)# sudo apt-get install alien
Reading package lists... Done
Building dependency tree
Reading state information... Done
alien is already the newest version (8.95).

**Comment by davidnewhall** [comment]
This happened because you installed `rpm` on your system. You should download and install the deb file instead. Like this:
```
wget -qO- https://golift.io/unpackerr/raw/master/scripts/install.sh | sudo bash deb
```
