### ISSUE TITLE
No extractable files found: Linux with all apps on one server/file system

### ISSUE THREAD

**Issue by Eddie563** [davidnewhall/unpackerr#90]
Similar issue to https://github.com/davidnewhall/unpackerr/issues/48

Something has stopped working for me. similar issue as above however its not the same. This has been working fine. It seems these DL's have a folder in the root named sample. in the root there also .rar's and its not picking them up to extract.

running on Ubuntu 20.04 and permissions are set correctly and has been working fine.

```
eddie@challenger:~$ sudo systemctl status unpackerr.service
● unpackerr.service - unpackerr - Extracts downloads so Radarr, Sonarr, Lidarr or Readarr may import them.
     Loaded: loaded (/lib/systemd/system/unpackerr.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-01-21 07:46:54 GMT; 6 days ago
   Main PID: 963 (unpackerr)
      Tasks: 15 (limit: 38414)
     Memory: 16.4M
     CGroup: /system.slice/unpackerr.service
             └─963 /usr/bin/unpackerr

Jan 27 07:56:55 challenger unpackerr[963]: 2021/01/27 07:56:55 [Unpackerr] Totals: [0 restarted] [9 finished] [0|0 webhooks] [0 stacks]
Jan 27 07:57:55 challenger unpackerr[963]: 2021/01/27 07:57:55 [Unpackerr] Queue: [3 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
Jan 27 07:57:55 challenger unpackerr[963]: 2021/01/27 07:57:55 [Unpackerr] Totals: [0 restarted] [9 finished] [0|0 webhooks] [0 stacks]
Jan 27 07:58:55 challenger unpackerr[963]: 2021/01/27 07:58:55 [Radarr] Updated (http://127.0.0.1:7878): 0 Items Queued
Jan 27 07:58:55 challenger unpackerr[963]: 2021/01/27 07:58:55 [Sonarr] Updated (http://127.0.0.1:8989): 4 Items Queued
Jan 27 07:58:55 challenger unpackerr[963]: 2021/01/27 07:58:55 [Sonarr] Completed item still waiting: Gold.Rush.Freddy.Dodges.Mine.Rescue.S01E02.For.Petes.Sake.1080p.WEB.h264-B2B, no extractable files found at: /downloads/Gold.Rush.Freddy.Dodges.Mine.Rescue.S01E02.For.Petes.Sake.1080p.WEB.h264-B2B (stat err: stat /downloads/Gold.Rush.Freddy.Dodges.Mine.Rescue.S01E02.For.Petes.Sake.1080p.WEB.h264-B2B: no such file or directory)
Jan 27 07:58:55 challenger unpackerr[963]: 2021/01/27 07:58:55 [Sonarr] Completed item still waiting: 9-1-1.Lone.Star.S02E02.1080p.WEB.H264-CAKES, no extractable files found at: /downloads/9-1-1.Lone.Star.S02E02.1080p.WEB.H264-CAKES (stat err: stat /downloads/9-1-1.Lone.Star.S02E02.1080p.WEB.H264-CAKES: no such file or directory)
Jan 27 07:58:55 challenger unpackerr[963]: 2021/01/27 07:58:55 [Sonarr] Completed item still waiting: The.Expanse.S05E09.1080p.WEB.H264-GLHF, no extractable files found at: /downloads/The.Expanse.S05E09.1080p.WEB.H264-GLHF (stat err: stat /downloads/The.Expanse.S05E09.1080p.WEB.H264-GLHF: no such file or directory)
Jan 27 07:58:55 challenger unpackerr[963]: 2021/01/27 07:58:55 [Unpackerr] Queue: [3 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
Jan 27 07:58:55 challenger unpackerr[963]: 2021/01/27 07:58:55 [Unpackerr] Totals: [0 restarted] [9 finished] [0|0 webhooks] [0 stacks]
```

**Comment by Eddie563** [comment]
Thanks david, seen you edited and now i know how to do it with the '''

**Comment by davidnewhall** [comment]
Show me your config. It's in the startup messages. Logs are probably in /var/log/syslog.
```
sudo grep unpackerr /var/log/{syslog,messages}
```

Where are your files? It's looking in `/downloads`

**Comment by Eddie563** [comment]
'''
# TV Series / Episodes
[[sonarr]]
   url = "http://127.0.0.1:8989"
   api_key = "MyAPI"
   # File system path where downloaded Sonarr items are located.
#   paths = ["/downloads"]
# Default protocols is torrent. Alternative: "torrent,usenet"
#   protocols = "torrent"

# Movies
[[radarr]]
  url = "http://127.0.0.1:7878"
  api_key = "MyAPI"
  # File system path where downloaded Radarr items are located.
#  paths = ["/downloads"]
# Default protocols is torrents. Alternative: "torrent,usenet"
#   protocols = "torrent"


Log
'''
/var/log/syslog:Jan 27 09:22:55 eddiecloud unpackerr[963]: 2021/01/27 09:22:55 [Radarr] Updated (http://127.0.0.1:7878): 0 Items Queued
/var/log/syslog:Jan 27 09:22:55 eddiecloud unpackerr[963]: 2021/01/27 09:22:55 [Sonarr] Updated (http://127.0.0.1:8989): 4 Items Queued
/var/log/syslog:Jan 27 09:22:55 eddiecloud unpackerr[963]: 2021/01/27 09:22:55 [Sonarr] Completed item still waiting: Gold.Rush.Freddy.Dodges.Mine.Rescue.S01E02.For.Petes.Sake.1080p.WEB.h264-B2B, no extractable files found at: /downloads/Gold.Rush.Freddy.Dodges.Mine.Rescue.S01E02.For.Petes.Sake.1080p.WEB.h264-B2B (stat err: stat /downloads/Gold.Rush.Freddy.Dodges.Mine.Rescue.S01E02.For.Petes.Sake.1080p.WEB.h264-B2B: no such file or directory)
/var/log/syslog:Jan 27 09:22:55 eddiecloud unpackerr[963]: 2021/01/27 09:22:55 [Sonarr] Completed item still waiting: 9-1-1.Lone.Star.S02E02.1080p.WEB.H264-CAKES, no extractable files found at: /downloads/9-1-1.Lone.Star.S02E02.1080p.WEB.H264-CAKES (stat err: stat /downloads/9-1-1.Lone.Star.S02E02.1080p.WEB.H264-CAKES: no such file or directory)
/var/log/syslog:Jan 27 09:22:55 eddiecloud unpackerr[963]: 2021/01/27 09:22:55 [Sonarr] Completed item still waiting: The.Expanse.S05E09.1080p.WEB.H264-GLHF, no extractable files found at: /downloads/The.Expanse.S05E09.1080p.WEB.H264-GLHF (stat err: stat /downloads/The.Expanse.S05E09.1080p.WEB.H264-GLHF: no such file or directory)
/var/log/syslog:Jan 27 09:22:55 eddiecloud unpackerr[963]: 2021/01/27 09:22:55 [Unpackerr] Queue: [3 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
/var/log/syslog:Jan 27 09:22:55 eddiecloud unpackerr[963]: 2021/01/27 09:22:55 [Unpackerr] Totals: [0 restarted] [9 finished] [0|0 webhooks] [0 stacks]
'''

My files are located in /eddie/rtorrent/downloads which would make the client location /downloads. as you can see from the log above 9 have already completed successfully. The ones that have stopped have a folder called sample in the same directory as the .rar.

A friend, who's server is configured the same, is displaying the same issue and his download has a folder called sample also.

**Comment by davidnewhall** [comment]
I'm not entirely sure what you mean what you say your download folder is named `sample`. None of the logs nor configurations you've provided contain that word, so it's not clear where you're seeing it. If you're describing the content of the download, a `sample` folder is normal. 

> My files are located in /eddie/rtorrent/downloads which would make the client location /downloads. 

Can you elaborate on this? if the files are in `/eddie/rtorrent/downloads`, what makes them also be in `/downloads`?

**Comment by Eddie563** [comment]
as an example in the folder /eddie/rtorrent/downloads/The.Expanse.S05E09.1080p.WEB.H264-GLHF there is a folder called sample, in this folder is a sample mkv file. also in the above path are the rar files. only downloads that have this sample folder are failing. if a download does not contain a sample folder, the rar unpacks, copies and then deletes the unpacked file.

**Comment by Eddie563** [comment]
Path updated in the config and is now working as expected. I have no idea how it was working before when there was no sample folder in the download.

**Comment by davidnewhall** [comment]
The app is resilient. It looks at the error message from Sonarr to find the path. When there is a sample folder Sonarr's error message changes to "sample detected" instead of "no files found in /path/to/files" (paraphrasing both of these). When there's a sample folder, unpackerr doesn't get the path from Sonarr (it's just not there). When there is not a sample folder, unpackerr gets the path from Sonarr because it's in the error message. Setting the `paths` variable is the correct fix.
