### ISSUE TITLE
install

### ISSUE THREAD

**Issue by sbh7600** [davidnewhall/unpackerr#91]
Hello!

im a little confused here, how do i install it?

1.
###
###

does that mean remove # from :
#[[sonarr]]
#   api_key = "fdsfsdfsdsdfsdf"

**Comment by davidnewhall** [comment]
Yes.

**Comment by sbh7600** [comment]
Thanks :) 
and remove # from #   paths = ["/downloads"] so it looks the right place for the downloaded stuff?

**Comment by davidnewhall** [comment]
Correct.

**Comment by sbh7600** [comment]
Great thanks a million :-)

**Comment by sbh7600** [comment]
Great, thanks a million :-)
