### ISSUE TITLE
Not working if there is a sample file

### ISSUE THREAD

**Issue by INTELBB** [davidnewhall/unpackerr#99]
I noticed that if there is a sample folder with example: movie-sample.mkv, unpackerr doesn't do anything.
Trouble is that a lot of rared downloads have sample with it.
Is there a workoround?
I'm using unpackerr on unraid.

**Comment by davidnewhall** [comment]
This simply means the application isn't properly configured. Hopefully looking at the output/logs helps understand. Please set the `paths` variables for your apps correctly.

**Comment by INTELBB** [comment]
Hmm... not shure how to map then... Can you take a look at my mapping?

This is my sonarr container setting, and unpackerr...


![sonarr](https://user-images.githubusercontent.com/33225575/108491147-d4c75100-72a3-11eb-8578-81200b173748.PNG)
![unpackerr](https://user-images.githubusercontent.com/33225575/108491157-d6911480-72a3-11eb-9895-a5d11c386069.PNG)

**Comment by davidnewhall** [comment]
It looks like you changed `/downloads` to `/data` in your `path` variables. 

Search your unpackerr logs for this phrase "trying path found in status message" and show me the lines that contain it. Those lines show the correct path you should be setting.

**Comment by INTELBB** [comment]
Yes i did, I have /data in sonarr, should i switch back to /downloads?

**Comment by davidnewhall** [comment]
If you show me the log line I requested I can provide better advice.

**Comment by INTELBB** [comment]
No such line in logs

**Comment by davidnewhall** [comment]
That makes it hard for me to believe it extract something without a sample folder. heh

**Comment by INTELBB** [comment]
`2021/01/12 21:31:07 Unpackerr v0.7.2- Starting! (PID: 223) 2021-01-12 21:31:07.540074577 +0100 CET m=+0.001709292
2021/01/12 21:31:07 ==> GoLift Discord: https://golift.io/discord <==
2021/01/12 21:31:07 ==> Startup Settings <==
2021/01/12 21:31:07  => Sonarr Config: 1 server: http://10.10.10.10:8989/, apikey:true, timeout:10s, verify ssl:false, protos:torrent, paths:["/downloads"]
2021/01/12 21:31:07  => Radarr Config: 1 server: http://10.10.10.10:7878/, apikey:true, timeout:10s, verify ssl:false, protos:torrent, paths:["/downloads"]
2021/01/12 21:31:07  => Lidarr Config: 1 server: , apikey:false, timeout:10s, verify ssl:false, protos:torrent, paths:["/downloads"]
2021/01/12 21:31:07  => Readarr Config: 0 servers
2021/01/12 21:31:07  => Folder Config: 0 paths, event buffer: 20000
2021/01/12 21:31:07  => Parallel: 1
2021/01/12 21:31:07  => Interval: 2m0s
2021/01/12 21:31:07  => Delete Delay: 5m0s
2021/01/12 21:31:07  => Start Delay: 1m0s
2021/01/12 21:31:07  => Retry Delay: 5m0s
2021/01/12 21:31:07  => Debug / Quiet: false / false
2021/01/12 21:31:07  => Directory & File Modes: fd & d4
2021/01/12 21:31:07  => Log File: /config/app/unpackerr.log (10 @ 10Mb)
2021/01/12 21:31:07  => Webhook Configs: 0 URLs
2021/01/12 21:31:07 [Sonarr] Updated (http://10.10.10.10:8989/): 1 Items Queued
2021/01/12 21:31:07 [Radarr] Updated (http://10.10.10.10:7878/): 1 Items Queued
2021/01/12 21:31:07 [Sonarr] Waiting for Start Delay: Vikings.S06E20.1080p.WEB.H264-GLHF (1m0s remains)
2021/01/12 21:31:07 [Radarr] Waiting for Start Delay: Honest.Thief.2020.720p.BluRay.x264-PiGNUS (1m0s remains)
2021/01/12 21:32:07 [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
2021/01/12 21:32:07 [Unpackerr] Totals: [0 restarted] [0 finished] [0|0 webhooks] [0 stacks]
2021/01/12 21:33:07 [Sonarr] Updated (http://10.10.10.10:8989/): 1 Items Queued
2021/01/12 21:33:07 [Radarr] Updated (http://10.10.10.10:7878/): 1 Items Queued
2021/01/12 21:33:07 [Sonarr] Completed item still waiting: Vikings.S06E20.1080p.WEB.H264-GLHF, no extractable files found at: /data/completed/Vikings.S06E20.1080p.WEB.H264-GLHF (stat err: stat /data/completed/Vikings.S06E20.1080p.WEB.H264-GLHF: no such file or directory)
2021/01/12 21:33:07 [Radarr] Completed item still waiting: Honest.Thief.2020.720p.BluRay.x264-PiGNUS, no extractable files found at: /data/completed/Honest.Thief.2020.720p.BluRay.x264-PiGNUS (stat err: stat /data/completed/Honest.Thief.2020.720p.BluRay.x264-PiGNUS: no such file or directory)
2021/01/12 21:33:07 [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
2021/01/12 21:33:07 [Unpackerr] Totals: [0 restarted] [0 finished] [0|0 webhooks] [0 stacks]
2021/01/12 21:34:07 [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
2021/01/12 21:34:07 [Unpackerr] Totals: [0 restarted] [0 finished] [0|0 webhooks] [0 stacks]
2021/01/12 21:35:07 [Sonarr] Updated (http://10.10.10.10:8989/): 1 Items Queued
2021/01/12 21:35:07 [Radarr] Updated (http://10.10.10.10:7878/): 1 Items Queued
2021/01/12 21:35:07 [Sonarr] Completed item still waiting: Vikings.S06E20.1080p.WEB.H264-GLHF, no extractable files found at: /data/completed/Vikings.S06E20.1080p.WEB.H264-GLHF (stat err: stat /data/completed/Vikings.S06E20.1080p.WEB.H264-GLHF: no such file or directory)
2021/01/12 21:35:07 [Radarr] Completed item still waiting: Honest.Thief.2020.720p.BluRay.x264-PiGNUS, no extractable files found at: /data/completed/Honest.Thief.2020.720p.BluRay.x264-PiGNUS (stat err: stat /data/completed/Honest.Thief.2020.720p.BluRay.x264-PiGNUS: no such file or directory)
2021/01/12 21:35:07 [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
2021/01/12 21:35:07 [Unpackerr] Totals: [0 restarted] [0 finished] [0|0 webhooks] [0 stacks]
2021/01/12 21:36:07 [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
2021/01/12 21:36:07 [Unpackerr] Totals: [0 restarted] [0 finished] [0|0 webhooks] [0 stacks]
2021/01/12 21:37:06 [unpackerr] Need help? GoLift Discord: https://golift.io/discord
=====> Exiting! Caught Signal: terminated
2021/01/12 21:37:11 Unpackerr v0.7.2- Starting! (PID: 221) 2021-01-12 21:37:11.943132064 +0100 CET m=+0.001394565
2021/01/12 21:37:11 ==> GoLift Discord: https://golift.io/discord <==
2021/01/12 21:37:11 ==> Startup Settings <==
2021/01/12 21:37:11  => Sonarr Config: 1 server: http://10.10.10.10:8989/, apikey:true, timeout:10s, verify ssl:false, protos:torrent, paths:["/downloads"]
2021/01/12 21:37:11  => Radarr Config: 1 server: http://10.10.10.10:7878/, apikey:true, timeout:10s, verify ssl:false, protos:torrent, paths:["/downloads"]
2021/01/12 21:37:11  => Lidarr Config: 1 server: , apikey:false, timeout:10s, verify ssl:false, protos:torrent, paths:["/downloads"]
2021/01/12 21:37:11  => Readarr Config: 0 servers
2021/01/12 21:37:11  => Folder Config: 0 paths, event buffer: 20000
2021/01/12 21:37:11  => Parallel: 1
2021/01/12 21:37:11  => Interval: 2m0s
2021/01/12 21:37:11  => Delete Delay: 5m0s
2021/01/12 21:37:11  => Start Delay: 1m0s
2021/01/12 21:37:11  => Retry Delay: 5m0s
2021/01/12 21:37:11  => Debug / Quiet: false / false
2021/01/12 21:37:11  => Directory & File Modes: fd & d4
2021/01/12 21:37:11  => Log File: /config/app/unpackerr.log (10 @ 10Mb)
2021/01/12 21:37:11  => Webhook Configs: 0 URLs
2021/01/12 21:37:11 [Sonarr] Updated (http://10.10.10.10:8989/): 1 Items Queued
2021/01/12 21:37:11 [Radarr] Updated (http://10.10.10.10:7878/): 1 Items Queued
2021/01/12 21:37:11 [Sonarr] Waiting for Start Delay: Vikings.S06E20.1080p.WEB.H264-GLHF (1m0s remains)
2021/01/12 21:37:11 [Radarr] Waiting for Start Delay: Honest.Thief.2020.720p.BluRay.x264-PiGNUS (1m0s remains)
2021/01/12 21:38:11 [Unpackerr] Queue: [2 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
2021/01/12 21:38:11 [Unpackerr] Totals: [0 restarted] [0 finished] [0|0 webhooks] [0 stacks]
2021/01/12 21:39:11 [Radarr] Updated (http://10.10.10.10:7878/): 1 Items Queued
2021/01/12 21:39:11 [Sonarr] Updated (http://10.10.10.10:8989/): 1 Items Queued
2021/01/12 21:39:11 [Sonarr] Extraction Queued: /data/completed/Vikings.S06E20.1080p.WEB.H264-GLHF, extractable files: 1, items in queue: 0
2021/01/12 21:39:11 [Radarr] Extraction Queued: /data/completed/Honest.Thief.2020.720p.BluRay.x264-PiGNUS, extractable files: 1, items in queue: 1
2021/01/12 21:39:11 [Unpackerr] Queue: [0 waiting] [2 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]
2021/01/12 21:39:11 [Unpackerr] Totals: [0 restarted] [0 finished] [0|0 webhooks] [1 stacks]
2021/01/12 21:39:11 Extraction Started: Vikings.S06E20.1080p.WEB.H264-GLHF, items in queue: 0
`

**Comment by davidnewhall** [comment]
Set paths to `/data/completed/`

**Comment by davidnewhall** [comment]
It also seems weird that you have download location twice in your unraid template.

**Comment by INTELBB** [comment]
That did the trick, data/completed
Thank you.
That's new, I didn't have that before (that last path config).
Ill try to start over with unpackerr now that you fixed my paths ;)

**Comment by INTELBB** [comment]
Yup, started from scratch, no more double paths...
Thank you for ur help

**Comment by davidnewhall** [comment]
No prob, glad it's working!
